namespace ZibStack.NET.Log.Attributes;

internal static class AttributeSources
{
    public const string ZibLogAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Marks a class for ZibStack.Log source generation.
            /// The generator will create interceptors for all methods decorated with <see cref="LogAttribute"/>.
            /// </summary>
            /// <example>
            /// Basic usage — the generator auto-detects the <c>ILogger</c> field:
            /// <code>
            /// [ZibLog]
            /// public class OrderService
            /// {
            ///     private readonly ILogger&lt;OrderService&gt; _logger;
            ///
            ///     [Log]
            ///     public Order PlaceOrder(int id) { ... }
            /// }
            /// </code>
            /// </example>
            /// <example>
            /// Multiple ILogger fields — specify which one to use:
            /// <code>
            /// [ZibLog(LoggerField = "_auditLogger")]
            /// public class PaymentService
            /// {
            ///     private readonly ILogger&lt;PaymentService&gt; _logger;
            ///     private readonly ILogger&lt;PaymentService&gt; _auditLogger;
            /// }
            /// </code>
            /// </example>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("SMARTLOG_ATTRIBUTES")]
            internal sealed class ZibLogAttribute : global::System.Attribute
            {
                /// <summary>
                /// Name of the ILogger field to use. If null, the generator auto-detects the first ILogger/ILogger&lt;T&gt; field.
                /// </summary>
                /// <example>
                /// <code>
                /// [ZibLog(LoggerField = "_auditLogger")]
                /// public class PaymentService { ... }
                /// </code>
                /// </example>
                public string? LoggerField { get; set; }
            }
        }
        """;

    public const string LogAttribute = """
        // <auto-generated/>
        #nullable enable

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Marks a method for automatic logging. The source generator will create an interceptor
            /// that logs method entry, exit, parameters, return values, and exceptions.
            /// </summary>
            /// <example>
            /// Basic — logs entry, exit, all params, return value, and elapsed time at Information level:
            /// <code>
            /// [Log]
            /// public Order PlaceOrder(int customerId, string product) { ... }
            /// // log: Entering OrderService.PlaceOrder(customerId: 42, product: Widget)
            /// // log: Exited OrderService.PlaceOrder in 53ms -> Order { Id = 7 }
            /// </code>
            /// </example>
            /// <example>
            /// Custom log levels — Debug for entry/exit, Critical on exception:
            /// <code>
            /// [Log(EntryExitLevel = ZibLogLevel.Debug, ExceptionLevel = ZibLogLevel.Critical)]
            /// public decimal CalculateTotal(int orderId) { ... }
            /// </code>
            /// </example>
            /// <example>
            /// Minimal logging — no params, no return value, no stopwatch (health checks, hot paths):
            /// <code>
            /// [Log(LogParameters = false, LogReturnValue = false, MeasureElapsed = false)]
            /// public void Ping() { ... }
            /// // log: Entering MyService.Ping()
            /// // log: Exited MyService.Ping
            /// </code>
            /// </example>
            /// <example>
            /// Custom messages:
            /// <code>
            /// [Log(EntryMessage = "Processing payment for order {orderId}", ExitMessage = "Payment completed in {ElapsedMs}ms")]
            /// public Task&lt;Receipt&gt; ProcessPaymentAsync(int orderId) { ... }
            /// </code>
            /// </example>
            /// <example>
            /// Combined with parameter attributes:
            /// <code>
            /// [Log]
            /// public void Charge(int orderId, [Sensitive] string creditCard, [NoLog] byte[] rawPayload)
            /// // log: Entering PaymentService.Charge(orderId: 42, creditCard: ***)
            /// // rawPayload is excluded entirely
            /// </code>
            /// </example>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("SMARTLOG_ATTRIBUTES")]
            internal sealed class LogAttribute : global::System.Attribute
            {
                /// <summary>
                /// Log level for entry/exit messages. Use <see cref="ZibLogLevel"/> constants.
                /// Default: <see cref="ZibLogLevel.Information"/> (2).
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(EntryExitLevel = ZibLogLevel.Debug)]       // entry/exit at Debug
                /// [Log(EntryExitLevel = ZibLogLevel.Warning)]     // entry/exit at Warning
                /// [Log(EntryExitLevel = ZibLogLevel.Trace)]       // entry/exit at Trace (most verbose)
                /// </code>
                /// </example>
                public int EntryExitLevel { get; set; } = 2;

                /// <summary>
                /// Log level used when the method throws an exception.
                /// Default: <see cref="ZibLogLevel.Error"/> (4).
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(ExceptionLevel = ZibLogLevel.Critical)]  // exceptions logged as Critical
                /// [Log(ExceptionLevel = ZibLogLevel.Warning)]   // exceptions logged as Warning
                /// </code>
                /// </example>
                public int ExceptionLevel { get; set; } = 4;

                /// <summary>
                /// Whether to log parameter values on entry. Default: <c>true</c>.
                /// Set to <c>false</c> for methods with many or large parameters.
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(LogParameters = false)]
                /// public void Import(List&lt;Record&gt; records) { ... }
                /// // log: Entering DataService.Import()     — no param values
                /// </code>
                /// </example>
                public bool LogParameters { get; set; } = true;

                /// <summary>
                /// Whether to log the return value on exit. Default: <c>true</c>.
                /// Set to <c>false</c> for methods returning large objects or sensitive data.
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(LogReturnValue = false)]
                /// public UserProfile GetProfile(int userId) { ... }
                /// // log: Exited UserService.GetProfile in 12ms     — no return value
                /// </code>
                /// </example>
                public bool LogReturnValue { get; set; } = true;

                /// <summary>
                /// Whether to measure and log elapsed time. Default: <c>true</c>.
                /// Set to <c>false</c> for trivial methods where Stopwatch overhead matters.
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(MeasureElapsed = false)]
                /// public void Ping() { ... }
                /// // log: Entering HealthService.Ping()
                /// // log: Exited HealthService.Ping         — no elapsed time
                /// </code>
                /// </example>
                public bool MeasureElapsed { get; set; } = true;

                /// <summary>
                /// Custom entry log message template. If null, a default message is generated.
                /// <para><b>Available placeholders:</b> method parameter names from the signature.</para>
                /// <list type="bullet">
                ///   <item><c>{paramName}</c> — value of the parameter (e.g. <c>{orderId}</c>, <c>{product}</c>)</item>
                /// </list>
                /// <para>Parameters marked with <c>[Sensitive]</c> will be logged as <c>***</c>.
                /// Parameters marked with <c>[NoLog]</c> are excluded entirely.</para>
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(EntryMessage = "Processing payment for order {orderId}, amount: {amount}")]
                /// public Receipt Pay(int orderId, decimal amount) { ... }
                /// // log: Processing payment for order 42, amount: 99.99
                ///
                /// [Log(EntryMessage = "Authenticating {username}")]
                /// public bool Login(string username, [Sensitive] string password) { ... }
                /// // log: Authenticating john     (password is masked as ***)
                /// </code>
                /// </example>
                public string? EntryMessage { get; set; }

                /// <summary>
                /// Custom exit log message template. If null, a default message is generated.
                /// <para><b>Available placeholders:</b></para>
                /// <list type="bullet">
                ///   <item><c>{ElapsedMs}</c> — elapsed time in milliseconds (requires <c>MeasureElapsed = true</c>)</item>
                ///   <item><c>{Result}</c> — string representation of the return value (requires <c>LogReturnValue = true</c>)</item>
                /// </list>
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(ExitMessage = "Payment completed in {ElapsedMs}ms, receipt: {Result}")]
                /// public Receipt Pay(int orderId, decimal amount) { ... }
                /// // log: Payment completed in 127ms, receipt: Receipt { Id = 9 }
                /// </code>
                /// </example>
                public string? ExitMessage { get; set; }

                /// <summary>
                /// Custom exception log message template. If null, a default message is generated.
                /// <para><b>Available placeholders:</b></para>
                /// <list type="bullet">
                ///   <item><c>{ElapsedMs}</c> — elapsed time in milliseconds (requires <c>MeasureElapsed = true</c>)</item>
                /// </list>
                /// </summary>
                /// <example>
                /// <code>
                /// [Log(ExceptionMessage = "Payment for order {orderId} failed after {ElapsedMs}ms")]
                /// public Receipt Pay(int orderId) { ... }
                /// // log: Payment for order 42 failed after 127ms
                /// //      System.InvalidOperationException: Insufficient funds
                /// </code>
                /// </example>
                public string? ExceptionMessage { get; set; }

                /// <summary>
                /// How complex objects (non-primitive parameters and return values) are serialized in logs.
                /// Use <see cref="ObjectLogMode"/> constants. Default: <see cref="ObjectLogMode.Json"/> (2).
                /// </summary>
                /// <example>
                /// <code>
                /// // JSON (default) — full object as JSON string:
                /// [Log(ObjectLogging = ObjectLogMode.Json)]
                /// public Order GetOrder(int id) { ... }
                /// // log: Exited GetOrder in 3ms -> {"Id":1,"Product":"Widget","Total":29.97}
                ///
                /// // Destructure — Serilog-style {@param}, providers that support it show structured data:
                /// [Log(ObjectLogging = ObjectLogMode.Destructure)]
                /// public Order GetOrder(int id) { ... }
                /// // log (Serilog): Exited GetOrder in 3ms -> Order { Id = 1, Product = "Widget" }
                /// // log (Console): Exited GetOrder in 3ms -> ZibStack.NET.Log.Sample.Order
                ///
                /// // ToString — uses object.ToString(), you control the output:
                /// [Log(ObjectLogging = ObjectLogMode.ToString)]
                /// public Order GetOrder(int id) { ... }
                /// // log: Exited GetOrder in 3ms -> ZibStack.NET.Log.Sample.Order  (unless ToString() is overridden)
                /// </code>
                /// </example>
                public int ObjectLogging { get; set; } = 1;
            }
        }
        """;

    public const string NoLogAttribute = """
        // <auto-generated/>

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Excludes a parameter entirely from log output. Use this for large objects,
            /// binary data, or parameters that add noise to logs.
            /// For sensitive data that should appear as "***", use <see cref="SensitiveAttribute"/> instead.
            /// </summary>
            /// <example>
            /// <code>
            /// [Log]
            /// public void Upload(string fileName, [NoLog] byte[] fileContent, [NoLog] Stream stream)
            /// // log: Entering StorageService.Upload(fileName: report.pdf)
            /// // fileContent and stream are excluded entirely from the log message
            ///
            /// // On return value — excludes return value from exit logs:
            /// [Log]
            /// [return: NoLog]
            /// public byte[] GetFile(string name) { ... }
            /// // log: Exited GetFile in 5ms     (no return value logged)
            /// </code>
            /// </example>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue | global::System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("SMARTLOG_ATTRIBUTES")]
            internal sealed class NoLogAttribute : global::System.Attribute
            {
            }
        }
        """;

    public const string SensitiveAttribute = """
        // <auto-generated/>

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Marks a parameter as sensitive. Its value will be masked as <c>"***"</c> in log output.
            /// The parameter name still appears in the log, only the value is hidden.
            /// For parameters that should be excluded entirely, use <see cref="NoLogAttribute"/> instead.
            /// </summary>
            /// <example>
            /// <code>
            /// [Log]
            /// public bool Authenticate(string username, [Sensitive] string password)
            /// // log: Entering AuthService.Authenticate(username: john, password: ***)
            /// </code>
            /// </example>
            /// <example>
            /// <code>
            /// [Log]
            /// public void Charge(int orderId, [Sensitive] string creditCard, [Sensitive] string cvv)
            /// // log: Entering PaymentService.Charge(orderId: 42, creditCard: ***, cvv: ***)
            ///
            /// // On return value — masks the result in exit logs:
            /// [Log]
            /// [return: Sensitive]
            /// public string GetApiKey(int userId) { ... }
            /// // log: Exited GetApiKey in 2ms -> ***
            /// </code>
            /// </example>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.ReturnValue | global::System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
            [global::System.Diagnostics.Conditional("SMARTLOG_ATTRIBUTES")]
            internal sealed class SensitiveAttribute : global::System.Attribute
            {
            }
        }
        """;

    public const string ZibLogLevel = """
        // <auto-generated/>

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Log level constants matching <c>Microsoft.Extensions.Logging.LogLevel</c> values.
            /// Use these in <see cref="LogAttribute"/> properties to avoid referencing LogLevel directly.
            /// </summary>
            /// <example>
            /// <code>
            /// [Log(EntryExitLevel = ZibLogLevel.Debug)]                                      // verbose logging
            /// [Log(EntryExitLevel = ZibLogLevel.Warning)]                                    // only important calls
            /// [Log(EntryExitLevel = ZibLogLevel.Trace, ExceptionLevel = ZibLogLevel.Critical)]  // trace + loud errors
            /// </code>
            /// </example>
            internal static class ZibLogLevel
            {
                /// <summary>Most verbose level. Use for detailed diagnostic tracing.</summary>
                public const int Trace = 0;
                /// <summary>Debugging information, typically disabled in production.</summary>
                public const int Debug = 1;
                /// <summary>General operational events. Default level for <see cref="LogAttribute"/>.</summary>
                public const int Information = 2;
                /// <summary>Unexpected events that do not cause failures.</summary>
                public const int Warning = 3;
                /// <summary>Errors and exceptions. Default level for <see cref="LogAttribute.ExceptionLevel"/>.</summary>
                public const int Error = 4;
                /// <summary>Critical failures requiring immediate attention.</summary>
                public const int Critical = 5;
                /// <summary>Logging is disabled.</summary>
                public const int None = 6;
            }
        }
        """;

    public const string ObjectLogMode = """
        // <auto-generated/>

        namespace ZibStack.NET.Log
        {
            /// <summary>
            /// Controls how complex objects (non-primitive types) are serialized in log output.
            /// Use these constants in <see cref="LogAttribute.ObjectLogging"/>.
            /// </summary>
            /// <example>
            /// <code>
            /// [Log(ObjectLogging = ObjectLogMode.Json)]         // {"Id":1,"Product":"Widget"}
            /// [Log(ObjectLogging = ObjectLogMode.Destructure)]  // {@order} — Serilog structured logging
            /// [Log(ObjectLogging = ObjectLogMode.ToString)]     // ZibStack.NET.Log.Sample.Order (or custom ToString())
            /// </code>
            /// </example>
            internal static class ObjectLogMode
            {
                /// <summary>
                /// Uses <c>object.ToString()</c>. Override <c>ToString()</c> on your types for custom output.
                /// </summary>
                public new const int ToString = 0;

                /// <summary>
                /// Uses Serilog-style destructuring (<c>{@param}</c>). Logging providers that support
                /// structured logging (Serilog, Seq, Application Insights) will capture object properties.
                /// Providers without destructuring support fall back to <c>ToString()</c>.
                /// </summary>
                public const int Destructure = 1;

                /// <summary>
                /// Serializes the object to JSON using <c>System.Text.Json.JsonSerializer</c>.
                /// Works with any logging provider. Default mode.
                /// </summary>
                public const int Json = 2;
            }
        }
        """;

    public const string InterceptsLocationAttribute = """
        // <auto-generated/>

        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
            sealed file class InterceptsLocationAttribute : global::System.Attribute
            {
                public InterceptsLocationAttribute(string filePath, int line, int character)
                {
                }
            }
        }
        """;
}
