using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace ZibStack.NET.Log.Analyzers;

/// <summary>
/// Catches placements of <c>[Log]</c> that the source generator can't or won't intercept,
/// so consumers see an actionable error/warning in the IDE instead of "logs just don't
/// show up at runtime". This complements the source generator's own <c>SL0005</c>
/// (static method) diagnostic with several other dead-end placements.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class LogAttributeValidityAnalyzer : DiagnosticAnalyzer
{
    private const string LogAttributeFullName = "ZibStack.NET.Log.LogAttribute";

    // Keep IDs in the ZLOG0NN family so they group with the other Log analyzer diagnostics
    // in suppression UIs and editorconfig files.
    public const string PrivateMemberId = "ZLOG010";
    public const string RefReturnId = "ZLOG011";
    public const string PrivateContainingTypeId = "ZLOG012";
    public const string ExtensionMethodId = "ZLOG013";

    private static readonly DiagnosticDescriptor PrivateMemberRule = new(
        PrivateMemberId,
        title: "[Log] cannot intercept private/file-scoped methods",
        messageFormat: "[Log] on '{0}' won't intercept anything — generated extension-method interceptors cannot reach private members. Make the method internal+ or remove the attribute.",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "C# interceptors generated by ZibStack.NET.Log are extension methods placed in a separate static class. Extension methods can't see private members of their `this` argument, so the interceptor will never bind to the call site and the [Log] attribute silently no-ops at runtime.");

    private static readonly DiagnosticDescriptor RefReturnRule = new(
        RefReturnId,
        title: "[Log] cannot intercept ref/ref-readonly returning methods",
        messageFormat: "[Log] on '{0}' won't intercept — ref/ref readonly return types are not supported by the generated interceptor (no way to alias the result through the logging wrapper). Remove the attribute or refactor the return.",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor PrivateContainingTypeRule = new(
        PrivateContainingTypeId,
        title: "[Log] on a method whose containing type is private/file-scoped",
        messageFormat: "[Log] on '{0}' won't intercept — the containing type '{1}' is not visible to the generated extension-method interceptor (declared in a separate ZibStack.Generated namespace).",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ExtensionMethodRule = new(
        ExtensionMethodId,
        title: "[Log] on extension methods is not supported",
        messageFormat: "[Log] on extension method '{0}' has no effect — the generator wraps a method by emitting another extension method on the same receiver type, which would conflict with the original. Move the logging concern into the called method instead.",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
        => ImmutableArray.Create(PrivateMemberRule, RefReturnRule, PrivateContainingTypeRule, ExtensionMethodRule);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeMethod, SymbolKind.Method);
    }

    private static void AnalyzeMethod(SymbolAnalysisContext ctx)
    {
        var method = (IMethodSymbol)ctx.Symbol;
        if (method.MethodKind != MethodKind.Ordinary) return;

        bool methodHasLog = HasLogAttribute(method);
        bool typeHasLog = method.ContainingType is { } ct && HasLogAttribute(ct);
        if (!methodHasLog && !typeHasLog) return;

        // Static methods are diagnosed by the source generator (SL0005); do not duplicate.
        if (method.IsStatic) return;

        // Class-level [Log] only applies to PUBLIC instance members, so a private member
        // under a class-level [Log] simply isn't included — no need to warn separately.
        // We only flag the explicit method-level case here.
        if (methodHasLog && method.DeclaredAccessibility == Accessibility.Private)
        {
            Report(ctx, PrivateMemberRule, method, method.Name);
        }

        if (method.ReturnsByRef || method.ReturnsByRefReadonly)
        {
            Report(ctx, RefReturnRule, method, method.Name);
        }

        if (method.IsExtensionMethod)
        {
            Report(ctx, ExtensionMethodRule, method, method.Name);
        }

        // Walk up containing types — if any are private, the interceptor in the separate
        // ZibStack.Generated namespace can't reach them.
        for (var t = method.ContainingType; t is not null; t = t.ContainingType)
        {
            if (t.DeclaredAccessibility == Accessibility.Private)
            {
                Report(ctx, PrivateContainingTypeRule, method, method.Name, t.Name);
                break;
            }
        }
    }

    private static bool HasLogAttribute(ISymbol symbol)
        => symbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == LogAttributeFullName);

    private static void Report(SymbolAnalysisContext ctx, DiagnosticDescriptor rule, ISymbol symbol, params object[] args)
    {
        var loc = symbol.Locations.FirstOrDefault(l => l.IsInSource) ?? symbol.Locations.FirstOrDefault();
        if (loc is null) return;
        ctx.ReportDiagnostic(Diagnostic.Create(rule, loc, args));
    }
}
