using System.Collections.Generic;
using System.Text;

namespace ZibStack.NET.Core;

public partial class CoreGenerator
{
    private static string GeneratePartialFromSource(PartialFromInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName}");
        sb.AppendLine("{");

        foreach (var prop in info.Properties)
        {
            foreach (var attr in prop.ValidationAttributes)
                sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public PatchField<{prop.DisplayTypeName}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        sb.AppendLine($"    public void ApplyTo({info.TargetTypeName} target)");
        sb.AppendLine("    {");
        foreach (var prop in info.Properties)
        {
            var bang = NeedsNullForgiving(prop) ? "!" : "";
            sb.AppendLine($"        if ({prop.PropertyName}.HasValue) target.{prop.PropertyName} = {prop.PropertyName}.Value{bang};");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool NeedsNullForgiving(UtilsPropertyInfo prop)
        => !prop.IsValueType && !prop.IsNullable;

    /// <summary>
    /// Plain-shape generator used by [PickFrom] and [OmitFrom].
    /// Emits properties with their original types (NOT PatchField) and a static
    /// FromEntity(source) factory that copies the included properties from the source.
    /// No ApplyTo — these utility types model TypeScript Pick&lt;T,K&gt;/Omit&lt;T,K&gt;
    /// which are pure projections, not partial-update DTOs.
    /// </summary>
    private static string GeneratePlainShapeSource(PartialFromInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName}");
        sb.AppendLine("{");

        foreach (var prop in info.Properties)
        {
            foreach (var attr in prop.ValidationAttributes)
                sb.AppendLine($"    {attr}");
            sb.AppendLine($"    public {prop.DisplayTypeName} {prop.PropertyName} {{ get; init; }} = default!;");
        }

        sb.AppendLine();
        sb.AppendLine($"    public static {info.ClassName} FromEntity({info.TargetTypeName} source) => new()");
        sb.AppendLine("    {");
        foreach (var prop in info.Properties)
            sb.AppendLine($"        {prop.PropertyName} = source.{prop.PropertyName},");
        sb.AppendLine("    };");

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Plain-shape generator for [IntersectFrom]. Emits properties with their original
    /// types (deduplicated by name across sources), plus a FromEntity per source that
    /// fills only that source's properties, plus an ApplyTo per source that writes the
    /// matching properties back. No PatchField — intersect is a structural composition,
    /// not a partial update.
    /// </summary>
    private static string GenerateIntersectPlainSource(IntersectInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName}");
        sb.AppendLine("{");

        // Deduplicate properties by name (first source wins).
        var seen = new HashSet<string>();
        var allProps = new List<UtilsPropertyInfo>();
        foreach (var target in info.TargetTypes)
        {
            foreach (var prop in target.Properties)
            {
                if (seen.Add(prop.PropertyName))
                {
                    allProps.Add(prop);
                    foreach (var attr in prop.ValidationAttributes)
                        sb.AppendLine($"    {attr}");
                    sb.AppendLine($"    public {prop.DisplayTypeName} {prop.PropertyName} {{ get; init; }} = default!;");
                }
            }
        }

        // FromEntity per source: fills only the matching source's properties.
        // The rest stay default. To merge multiple sources, chain { ...FromEntity(a), ... } with-expression.
        foreach (var target in info.TargetTypes)
        {
            sb.AppendLine();
            sb.AppendLine($"    public static {info.ClassName} FromEntity({target.TypeName} source) => new()");
            sb.AppendLine("    {");
            foreach (var prop in target.Properties)
                sb.AppendLine($"        {prop.PropertyName} = source.{prop.PropertyName},");
            sb.AppendLine("    };");
        }

        // ApplyTo per source: writes back the matching properties.
        foreach (var target in info.TargetTypes)
        {
            sb.AppendLine();
            sb.AppendLine($"    public void ApplyTo({target.TypeName} target)");
            sb.AppendLine("    {");
            foreach (var prop in target.Properties)
                sb.AppendLine($"        target.{prop.PropertyName} = this.{prop.PropertyName};");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
