namespace ZibStack.NET.Core;

public partial class CoreGenerator
{
    // ─── Utility type attributes ────────────────────────────────────────

    private const string PartialFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Core
{
    /// <summary>
    /// Generates a partial class with PatchField properties for all public properties of the target type,
    /// plus an ApplyTo method. Similar to TypeScript's Partial&lt;T&gt;.
    /// The decorated class must be partial.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class PartialFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public PartialFromAttribute(System.Type targetType) => TargetType = targetType;
    }
}
";

    private const string IntersectFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Core
{
    /// <summary>
    /// Generates a partial record that intersects properties from multiple types.
    /// Apply multiple times to combine types (like TypeScript's &amp; operator).
    /// The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class IntersectFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public IntersectFromAttribute(System.Type targetType) => TargetType = targetType;
    }
}
";

    private const string PickFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Core
{
    /// <summary>Like TypeScript Pick&lt;T, K&gt;. Generates a partial record with only the listed properties.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class PickFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public string[] Properties { get; }
        public PickFromAttribute(System.Type targetType, params string[] properties)
        {
            TargetType = targetType;
            Properties = properties;
        }
    }
}
";

    private const string OmitFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Core
{
    /// <summary>Like TypeScript Omit&lt;T, K&gt;. Generates a partial record with all properties except the listed ones.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class OmitFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public string[] Properties { get; }
        public OmitFromAttribute(System.Type targetType, params string[] properties)
        {
            TargetType = targetType;
            Properties = properties;
        }
    }
}
";

    private const string DestructurableAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Core
{
    /// <summary>
    /// Marks a type as destructurable. Enables JS-style destructuring via generated
    /// <c>PickXxx()</c> extension methods, where <c>Xxx</c> is the concatenation of
    /// property names in PascalCase. The generator scans usages and emits matching
    /// methods + 'rest' types on demand.
    /// </summary>
    /// <example>
    /// <code>
    /// [Destructurable]
    /// public partial class Person
    /// {
    ///     public string Name { get; set; } = """";
    ///     public int Id { get; set; }
    ///     public string Email { get; set; } = """";
    /// }
    ///
    /// // Usage:
    /// var (name, id, rest) = person.PickNameId();
    /// // rest is PersonRest_NameId { Email }
    /// </code>
    /// </example>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class DestructurableAttribute : System.Attribute { }
}
";

    // ─── Relationship attributes ────────────────────────────────────────

    private const string OneToManyAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Core
{
    /// <summary>Declares a one-to-many relationship on a navigation property (e.g. ICollection&lt;T&gt;).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class OneToManyAttribute : System.Attribute
    {
        /// <summary>Foreign key property name on the child type. Auto-detected by convention if omitted.</summary>
        public string? ForeignKey { get; set; }
        /// <summary>UI display label for the relationship.</summary>
        public string? Label { get; set; }
        /// <summary>Override table schema URL for the child. Resolved from child's [UiTable] if omitted.</summary>
        public string? SchemaUrl { get; set; }
        /// <summary>Override form schema URL for the child. Resolved from child's [UiForm] if omitted.</summary>
        public string? FormSchemaUrl { get; set; }
    }
}
";

    private const string OneToOneAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Core
{
    /// <summary>Declares a one-to-one relationship on a navigation property.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class OneToOneAttribute : System.Attribute
    {
        /// <summary>Foreign key property name. For OneToOne, looked up on the parent type by convention.</summary>
        public string? ForeignKey { get; set; }
        /// <summary>UI display label for the relationship.</summary>
        public string? Label { get; set; }
        /// <summary>Override table schema URL. Resolved from target's [UiTable] if omitted.</summary>
        public string? SchemaUrl { get; set; }
        /// <summary>Override form schema URL. Resolved from target's [UiForm] if omitted.</summary>
        public string? FormSchemaUrl { get; set; }
    }
}
";

    // ─── Entity / child table attributes ────────────────────────────────

    private const string EntityAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Core
{
    /// <summary>Opt-in: generates IEntityTypeConfiguration&lt;T&gt; for EF Core from this model's properties and relationships.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class EntityAttribute : System.Attribute
    {
        /// <summary>Override the database table name. Defaults to the class name.</summary>
        public string? TableName { get; set; }
        /// <summary>Database schema (e.g. ""dbo"").</summary>
        public string? Schema { get; set; }
    }
}
";

}
