using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace ZibStack.NET.TypeGen.Generator;

/// <summary>
/// Produces an OpenAPI 3.1 document from a <see cref="SchemaModel"/>. MVP coverage:
/// <c>info</c>, <c>components/schemas</c> populated from <c>[GenerateTypes]</c>
/// classes/enums. <c>paths</c> are out of scope until the <c>[CrudApi]</c>
/// integration ships in a follow-up.
///
/// <para>
/// Format follows the file extension on <see cref="OpenApiSettings.OutputPath"/>:
/// <c>.json</c> emits JSON, anything else emits YAML.
/// </para>
/// </summary>
internal static class OpenApiEmitter
{
    public static IReadOnlyList<EmittedFile> Emit(SchemaModel model, GlobalSettings settings)
    {
        var oa = settings.OpenApi;
        var emitJson = oa.OutputPath.EndsWith(".json", System.StringComparison.OrdinalIgnoreCase);

        // Stamp global flags onto classes so emitter helpers can read them without
        // threading settings through every call.
        foreach (var cls in model.Classes) cls.QueryDsl = settings.HasQueryDsl;

        // Resolve emitted schema names — ['Order' if no override, otherwise OpenApiSchemaName].
        // Stored back so $ref resolution works across classes referencing each other.
        foreach (var cls in model.Classes)
        {
            if (cls.OpenApiIgnore || (cls.Targets & TypeTarget.OpenApi) == 0) continue;
            cls.EmittedName = cls.OpenApiNameOverride ?? cls.SourceName;
        }
        foreach (var en in model.Enums)
        {
            if (en.OpenApiIgnore || (en.Targets & TypeTarget.OpenApi) == 0) continue;
            en.EmittedName = en.OpenApiNameOverride ?? en.SourceName;
        }

        var nameByCSharp = new Dictionary<string, string>();
        foreach (var c in model.Classes)
            if (!c.OpenApiIgnore && (c.Targets & TypeTarget.OpenApi) != 0)
                nameByCSharp[c.CSharpFullName] = c.EmittedName;
        foreach (var e in model.Enums)
            if (!e.OpenApiIgnore && (e.Targets & TypeTarget.OpenApi) != 0)
                nameByCSharp[e.CSharpFullName] = e.EmittedName;

        var content = emitJson
            ? EmitJson(model, oa, nameByCSharp)
            : EmitYaml(model, oa, nameByCSharp);

        // Split path into dir + filename. If the user gave only a filename, route it
        // under the first emitting class's OutputDir so `[GenerateTypes(OutputDir="generated")]`
        // keeps the schema next to its TypeScript siblings instead of dumping in the root.
        var path = oa.OutputPath.Replace('\\', '/');
        var lastSlash = path.LastIndexOf('/');
        string dir;
        string file;
        if (lastSlash >= 0)
        {
            dir = path.Substring(0, lastSlash);
            file = path.Substring(lastSlash + 1);
        }
        else
        {
            var firstCls = model.Classes.FirstOrDefault(c => !c.OpenApiIgnore && (c.Targets & TypeTarget.OpenApi) != 0);
            var firstEn = model.Enums.FirstOrDefault(e => !e.OpenApiIgnore && (e.Targets & TypeTarget.OpenApi) != 0);
            dir = firstCls?.OutputDir ?? firstEn?.OutputDir ?? ".";
            file = path;
        }

        return new[] { new EmittedFile(TypeTarget.OpenApi, dir, file, content) };
    }

    // ── YAML emitter (default) ──────────────────────────────────────────────

    private static string EmitYaml(SchemaModel model, OpenApiSettings oa, IReadOnlyDictionary<string, string> nameByCSharp)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# @generated by ZibStack.NET.TypeGen — do not edit");
        sb.AppendLine($"openapi: {oa.OpenApiVersion}");
        sb.AppendLine("info:");
        sb.AppendLine($"  title: {YamlString(oa.Title)}");
        sb.AppendLine($"  version: {YamlString(oa.Version)}");
        if (!string.IsNullOrEmpty(oa.Description))
            sb.AppendLine($"  description: {YamlString(oa.Description!)}");
        EmitPathsYaml(sb, model, nameByCSharp);
        sb.AppendLine("components:");
        sb.AppendLine("  schemas:");

        foreach (var cls in model.Classes)
        {
            if (cls.OpenApiIgnore || (cls.Targets & TypeTarget.OpenApi) == 0) continue;
            EmitClassYaml(sb, cls, nameByCSharp, indent: "    ");
        }
        foreach (var en in model.Enums)
        {
            if (en.OpenApiIgnore || (en.Targets & TypeTarget.OpenApi) == 0) continue;
            EmitEnumYaml(sb, en, indent: "    ");
        }

        // PaginatedResponseOf{Class} auxiliary schemas for every GetList-enabled CRUD class.
        EmitPaginatedWrappersYaml(sb, model, indent: "    ");

        return sb.ToString();
    }

    // ── paths emission (driven by [CrudApi]) ─────────────────────────────────

    /// <summary>
    /// Emits the full <c>paths:</c> block from any class carrying <c>[CrudApi]</c>.
    /// Convention: response shape is the class itself (<c>$ref</c> by emitted name);
    /// request bodies are <c>Create{Class}Request</c> / <c>Update{Class}Request</c> —
    /// users are responsible for ensuring those exist as schemas (typically by also
    /// putting <c>[GenerateTypes]</c> on the request DTOs).
    /// </summary>
    private static void EmitPathsYaml(StringBuilder sb, SchemaModel model, IReadOnlyDictionary<string, string> nameByCSharp)
    {
        var crudClasses = model.Classes.Where(c => c.Crud is not null && (c.Targets & TypeTarget.OpenApi) != 0).ToList();
        if (crudClasses.Count == 0) { sb.AppendLine("paths: {}"); return; }

        sb.AppendLine("paths:");
        foreach (var cls in crudClasses)
        {
            var route = ResolveRoute(cls);
            var keyType = ResolveKeyParamType(cls);
            var collectionPath = "/" + route.TrimStart('/');
            var itemPath = collectionPath + "/{" + LowerFirst(cls.Crud!.KeyProperty) + "}";
            var ops = cls.Crud.Operations;

            // Group by path so multiple verbs share a single key.
            var collectionVerbs = new List<(string Verb, System.Action<StringBuilder> Emit)>();
            var itemVerbs = new List<(string Verb, System.Action<StringBuilder> Emit)>();

            if ((ops & CrudOperations.GetList) != 0)
                collectionVerbs.Add(("get", b => EmitListOpYaml(b, cls)));
            if ((ops & CrudOperations.Create) != 0)
                collectionVerbs.Add(("post", b => EmitCreateOpYaml(b, cls)));
            if ((ops & CrudOperations.GetById) != 0)
                itemVerbs.Add(("get", b => EmitGetByIdOpYaml(b, cls, keyType)));
            if ((ops & CrudOperations.Update) != 0)
                itemVerbs.Add(("patch", b => EmitUpdateOpYaml(b, cls, keyType)));
            if ((ops & CrudOperations.Delete) != 0)
                itemVerbs.Add(("delete", b => EmitDeleteOpYaml(b, cls, keyType)));

            if (collectionVerbs.Count > 0) EmitPathBlockYaml(sb, collectionPath, collectionVerbs);
            if (itemVerbs.Count > 0) EmitPathBlockYaml(sb, itemPath, itemVerbs);

            // Bulk ops sit on separate sub-paths — the Dto generator puts them under
            // /bulk and /bulk-delete. Emit only if their flag bit is set.
            if ((ops & CrudOperations.BulkCreate) != 0)
                EmitPathBlockYaml(sb, collectionPath + "/bulk",
                    new() { ("post", b => EmitBulkCreateOpYaml(b, cls)) });
            if ((ops & CrudOperations.BulkDelete) != 0)
                EmitPathBlockYaml(sb, collectionPath + "/bulk-delete",
                    new() { ("post", b => EmitBulkDeleteOpYaml(b, cls, keyType)) });
        }
    }

    private static void EmitPathBlockYaml(StringBuilder sb, string path, List<(string Verb, System.Action<StringBuilder> Emit)> verbs)
    {
        sb.AppendLine($"  {path}:");
        foreach (var (verb, emit) in verbs)
        {
            sb.AppendLine($"    {verb}:");
            emit(sb);
        }
    }

    private static void EmitListOpYaml(StringBuilder sb, SchemaClass cls)
    {
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: list{cls.EmittedName}");
        EmitListQueryParamsYaml(sb, cls);
        sb.AppendLine("      responses:");
        sb.AppendLine("        '200':");
        sb.AppendLine("          description: OK");
        sb.AppendLine("          content:");
        sb.AppendLine("            application/json:");
        sb.AppendLine($"              schema: {{ $ref: '#/components/schemas/{PaginatedSchemaName(cls)}' }}");
    }

    private static string PaginatedSchemaName(SchemaClass cls) => $"PaginatedResponseOf{cls.EmittedName}";

    private static void EmitListQueryParamsYaml(StringBuilder sb, SchemaClass cls)
    {
        // page + pageSize are always emitted by the Dto generator — match them unconditionally.
        // filter/sort/select/count only exist when ZibStack.NET.Query is referenced.
        sb.AppendLine("      parameters:");
        EmitQueryParamYaml(sb, "page", "integer", "int32", "Page number (1-based).");
        EmitQueryParamYaml(sb, "pageSize", "integer", "int32", "Items per page.");
        if (cls.QueryDsl)
        {
            EmitQueryParamYaml(sb, "filter", "string", null, "Filter DSL — 'Field>value,Field2=*text'.");
            EmitQueryParamYaml(sb, "sort", "string", null, "Sort DSL — '-Field,Field2' (prefix '-' for desc).");
            EmitQueryParamYaml(sb, "select", "string", null, "Projection — 'Field1,Field2'.");
            EmitQueryParamYaml(sb, "count", "boolean", null, "When true, returns only { count: int }.");
        }
    }

    private static void EmitQueryParamYaml(StringBuilder sb, string name, string typeKey, string? fmtKey, string description)
    {
        sb.AppendLine($"        - name: {name}");
        sb.AppendLine("          in: query");
        sb.AppendLine($"          description: {YamlString(description)}");
        sb.AppendLine("          schema:");
        sb.AppendLine($"            type: {typeKey}");
        if (fmtKey != null) sb.AppendLine($"            format: {fmtKey}");
    }

    private static void EmitBulkCreateOpYaml(StringBuilder sb, SchemaClass cls)
    {
        var req = $"Create{cls.SourceName}Request";
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: bulkCreate{cls.EmittedName}");
        sb.AppendLine("      requestBody:");
        sb.AppendLine("        required: true");
        sb.AppendLine("        content:");
        sb.AppendLine("          application/json:");
        sb.AppendLine("            schema:");
        sb.AppendLine("              type: array");
        sb.AppendLine($"              items: {{ $ref: '#/components/schemas/{req}' }}");
        sb.AppendLine("      responses:");
        sb.AppendLine("        '201':");
        sb.AppendLine("          description: Created");
        sb.AppendLine("          content:");
        sb.AppendLine("            application/json:");
        sb.AppendLine("              schema:");
        sb.AppendLine("                type: array");
        sb.AppendLine($"                items: {{ $ref: '#/components/schemas/{cls.EmittedName}' }}");
    }

    private static void EmitBulkDeleteOpYaml(StringBuilder sb, SchemaClass cls, (string TypeKey, string? FmtKey) keyType)
    {
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: bulkDelete{cls.EmittedName}");
        sb.AppendLine("      requestBody:");
        sb.AppendLine("        required: true");
        sb.AppendLine("        content:");
        sb.AppendLine("          application/json:");
        sb.AppendLine("            schema:");
        sb.AppendLine("              type: array");
        sb.AppendLine($"              items: {{ type: {keyType.TypeKey}{(keyType.FmtKey is null ? "" : $", format: {keyType.FmtKey}")} }}");
        sb.AppendLine("      responses:");
        sb.AppendLine("        '204':");
        sb.AppendLine("          description: No Content");
    }

    /// <summary>
    /// For each CRUD class with GetList enabled, emits a <c>PaginatedResponseOf{Class}</c>
    /// schema whose shape mirrors <c>ZibStack.NET.Dto.PaginatedResponse&lt;T&gt;</c> at runtime.
    /// Called from the components/schemas block so list endpoints can <c>$ref</c> to it.
    /// </summary>
    private static void EmitPaginatedWrappersYaml(StringBuilder sb, SchemaModel model, string indent)
    {
        foreach (var cls in model.Classes)
        {
            if (cls.Crud is null || (cls.Crud.Operations & CrudOperations.GetList) == 0) continue;
            if ((cls.Targets & TypeTarget.OpenApi) == 0 || cls.OpenApiIgnore) continue;
            EmitPaginatedSchemaYaml(sb, cls, indent);
        }
    }

    private static void EmitPaginatedSchemaYaml(StringBuilder sb, SchemaClass cls, string indent)
    {
        sb.AppendLine($"{indent}{PaginatedSchemaName(cls)}:");
        sb.AppendLine($"{indent}  type: object");
        sb.AppendLine($"{indent}  required: [items, totalCount, page, pageSize, totalPages, hasNextPage, hasPreviousPage]");
        sb.AppendLine($"{indent}  properties:");
        sb.AppendLine($"{indent}    items:");
        sb.AppendLine($"{indent}      type: array");
        sb.AppendLine($"{indent}      items: {{ $ref: '#/components/schemas/{cls.EmittedName}' }}");
        foreach (var (n, t, f) in new[] {
            ("totalCount", "integer", "int32"),
            ("page", "integer", "int32"),
            ("pageSize", "integer", "int32"),
            ("totalPages", "integer", "int32"),
        })
        {
            sb.AppendLine($"{indent}    {n}: {{ type: {t}, format: {f} }}");
        }
        sb.AppendLine($"{indent}    hasNextPage: {{ type: boolean }}");
        sb.AppendLine($"{indent}    hasPreviousPage: {{ type: boolean }}");
    }

    private static void EmitCreateOpYaml(StringBuilder sb, SchemaClass cls)
    {
        var req = $"Create{cls.SourceName}Request";
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: create{cls.EmittedName}");
        sb.AppendLine("      requestBody:");
        sb.AppendLine("        required: true");
        sb.AppendLine("        content:");
        sb.AppendLine("          application/json:");
        sb.AppendLine($"            schema: {{ $ref: '#/components/schemas/{req}' }}");
        sb.AppendLine("      responses:");
        sb.AppendLine("        '201':");
        sb.AppendLine("          description: Created");
        sb.AppendLine("          content:");
        sb.AppendLine("            application/json:");
        sb.AppendLine($"              schema: {{ $ref: '#/components/schemas/{cls.EmittedName}' }}");
    }

    private static void EmitGetByIdOpYaml(StringBuilder sb, SchemaClass cls, (string TypeKey, string? FmtKey) keyType)
    {
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: get{cls.EmittedName}ById");
        EmitKeyParamYaml(sb, cls.Crud!.KeyProperty, keyType);
        sb.AppendLine("      responses:");
        sb.AppendLine("        '200':");
        sb.AppendLine("          description: OK");
        sb.AppendLine("          content:");
        sb.AppendLine("            application/json:");
        sb.AppendLine($"              schema: {{ $ref: '#/components/schemas/{cls.EmittedName}' }}");
        sb.AppendLine("        '404':");
        sb.AppendLine("          description: Not Found");
    }

    private static void EmitUpdateOpYaml(StringBuilder sb, SchemaClass cls, (string TypeKey, string? FmtKey) keyType)
    {
        var req = $"Update{cls.SourceName}Request";
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: update{cls.EmittedName}");
        EmitKeyParamYaml(sb, cls.Crud!.KeyProperty, keyType);
        sb.AppendLine("      requestBody:");
        sb.AppendLine("        required: true");
        sb.AppendLine("        content:");
        sb.AppendLine("          application/json:");
        sb.AppendLine($"            schema: {{ $ref: '#/components/schemas/{req}' }}");
        sb.AppendLine("      responses:");
        sb.AppendLine("        '200':");
        sb.AppendLine("          description: OK");
        sb.AppendLine("          content:");
        sb.AppendLine("            application/json:");
        sb.AppendLine($"              schema: {{ $ref: '#/components/schemas/{cls.EmittedName}' }}");
    }

    private static void EmitDeleteOpYaml(StringBuilder sb, SchemaClass cls, (string TypeKey, string? FmtKey) keyType)
    {
        sb.AppendLine($"      tags: [{cls.EmittedName}]");
        sb.AppendLine($"      operationId: delete{cls.EmittedName}");
        EmitKeyParamYaml(sb, cls.Crud!.KeyProperty, keyType);
        sb.AppendLine("      responses:");
        sb.AppendLine("        '204':");
        sb.AppendLine("          description: No Content");
    }

    private static void EmitKeyParamYaml(StringBuilder sb, string keyName, (string TypeKey, string? FmtKey) keyType)
    {
        sb.AppendLine("      parameters:");
        sb.AppendLine($"        - name: {LowerFirst(keyName)}");
        sb.AppendLine("          in: path");
        sb.AppendLine("          required: true");
        sb.AppendLine("          schema:");
        sb.AppendLine($"            type: {keyType.TypeKey}");
        if (keyType.FmtKey != null) sb.AppendLine($"            format: {keyType.FmtKey}");
    }

    /// <summary>
    /// Resolves the route per <c>[CrudApi]</c> conventions: explicit <c>Route</c>
    /// wins; otherwise <c>api/{prefix}/{pluralized-class-name}</c>. Pluralization
    /// is naive (append <c>s</c>) — irregular nouns (Bus → Buses, Person → People)
    /// must use the explicit <c>Route</c> override.
    /// </summary>
    private static string ResolveRoute(SchemaClass cls)
    {
        var crud = cls.Crud!;
        if (!string.IsNullOrEmpty(crud.Route)) return crud.Route!;
        var prefix = crud.RoutePrefix?.Trim('/');
        var middle = string.IsNullOrEmpty(prefix) ? "" : prefix + "/";
        return $"api/{middle}{Pluralize(cls.SourceName).ToLowerInvariant()}";
    }

    private static string Pluralize(string name) => name + "s";

    private static string LowerFirst(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);

    /// <summary>
    /// Looks up the property matching <c>Crud.KeyProperty</c> and translates its
    /// C# type to OpenAPI type/format. Falls back to <c>integer/int32</c> when
    /// the property isn't found — same default as <c>[CrudApi]</c> assumes.
    /// </summary>
    private static (string TypeKey, string? FmtKey) ResolveKeyParamType(SchemaClass cls)
    {
        var key = cls.Properties.FirstOrDefault(p =>
            string.Equals(p.SourceName, cls.Crud!.KeyProperty, System.StringComparison.Ordinal));
        if (key is null) return ("integer", "int32");
        var mapped = MapCSharpToOpenApi(key.CSharpTypeFullName, new Dictionary<string, string>());
        return (mapped.TypeKey, mapped.FmtKey);
    }

    private static void EmitClassYaml(StringBuilder sb, SchemaClass cls, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        // Polymorphic base → `oneOf` with `discriminator.mapping`. Variants emit
        // as their own schemas (via ordinary EmitClassYaml on the variant); this
        // base schema just points at them.
        if (cls.PolymorphicVariants.Count > 0 && cls.PolymorphicDiscriminator is not null)
        {
            var variantRefs = cls.PolymorphicVariants
                .Select(v => (v, name: nameByCSharp.TryGetValue(v.CSharpFullName, out var n) ? n : null))
                .Where(x => x.name is not null)
                .ToList();
            if (variantRefs.Count > 0)
            {
                sb.AppendLine($"{indent}{cls.EmittedName}:");
                sb.AppendLine($"{indent}  oneOf:");
                foreach (var (_, name) in variantRefs)
                    sb.AppendLine($"{indent}    - $ref: '#/components/schemas/{name}'");
                sb.AppendLine($"{indent}  discriminator:");
                sb.AppendLine($"{indent}    propertyName: {cls.PolymorphicDiscriminator}");
                sb.AppendLine($"{indent}    mapping:");
                foreach (var (v, name) in variantRefs)
                    sb.AppendLine($"{indent}      {v.DiscriminatorValue}: '#/components/schemas/{name}'");
                return;
            }
        }

        // Base in the emit set → allOf [{ $ref: base }, { type: object, properties: new-only }].
        // BUT: if our base is a polymorphic union, DON'T allOf into it — the base
        // is an abstract oneOf, not a concrete object. We still stamp the
        // discriminator literal via the normal props path (see EmitPropertyYaml).
        var baseRef = cls.BaseClassFullName is { } bfn
            && nameByCSharp.TryGetValue(bfn, out var bn)
            && cls.PolymorphicDiscriminatorValue is null
            ? bn : null;
        if (baseRef is not null)
        {
            sb.AppendLine($"{indent}{cls.EmittedName}:");
            sb.AppendLine($"{indent}  allOf:");
            sb.AppendLine($"{indent}    - $ref: '#/components/schemas/{baseRef}'");
            sb.AppendLine($"{indent}    - type: object");
            EmitClassBodyYaml(sb, cls, nameByCSharp, indent + "      ");
            return;
        }
        sb.AppendLine($"{indent}{cls.EmittedName}:");
        sb.AppendLine($"{indent}  type: object");
        EmitClassBodyYaml(sb, cls, nameByCSharp, indent + "  ");
    }

    private static void EmitClassBodyYaml(StringBuilder sb, SchemaClass cls, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        var emittedProps = cls.Properties.Where(p => !p.OpenApiIgnore).ToList();
        var required = emittedProps.Where(p => !IsEffectivelyNullable(p)).ToList();
        // Polymorphic variant: discriminator is always present + required.
        var hasDiscProp = cls.PolymorphicDiscriminatorValue is not null
            && cls.PolymorphicDiscriminatorPropertyOnVariant is not null;

        if (required.Count > 0 || hasDiscProp)
        {
            sb.AppendLine($"{indent}required:");
            if (hasDiscProp) sb.AppendLine($"{indent}  - {cls.PolymorphicDiscriminatorPropertyOnVariant}");
            foreach (var p in required)
                sb.AppendLine($"{indent}  - {p.OpenApiNameOverride ?? p.SourceName}");
        }

        if (emittedProps.Count > 0 || hasDiscProp)
        {
            sb.AppendLine($"{indent}properties:");
            if (hasDiscProp)
            {
                // Discriminator as a string with single-value enum — OpenAPI 3.0
                // idiom for pinning a literal.
                sb.AppendLine($"{indent}  {cls.PolymorphicDiscriminatorPropertyOnVariant}:");
                sb.AppendLine($"{indent}    type: string");
                sb.AppendLine($"{indent}    enum:");
                sb.AppendLine($"{indent}      - {cls.PolymorphicDiscriminatorValue}");
            }
            foreach (var p in emittedProps)
                EmitPropertyYaml(sb, p, nameByCSharp, indent + "  ");
        }

        // [JsonExtensionData] property → additionalProperties on the parent schema
        // itself. Permissive (`true`) when the dictionary value is object / JsonElement,
        // typed schema otherwise.
        if (cls.AllowsAdditionalProperties)
        {
            if (cls.AdditionalPropertiesValueCSharpType is null)
            {
                sb.AppendLine($"{indent}additionalProperties: true");
            }
            else
            {
                var inner = MapCSharpToOpenApi(cls.AdditionalPropertiesValueCSharpType, nameByCSharp);
                sb.AppendLine($"{indent}additionalProperties:");
                if (inner.RefTarget is not null)
                    sb.AppendLine($"{indent}  $ref: '#/components/schemas/{inner.RefTarget}'");
                else
                {
                    sb.AppendLine($"{indent}  type: {inner.TypeKey}");
                    if (inner.FmtKey is not null) sb.AppendLine($"{indent}  format: {inner.FmtKey}");
                }
            }
        }
    }

    private static void EmitPropertyYaml(StringBuilder sb, SchemaProperty prop, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        var name = prop.OpenApiNameOverride ?? prop.SourceName;
        sb.AppendLine($"{indent}{name}:");
        var (typeKey, fmtKey, refTarget, items) = ResolvePropertyShape(prop, nameByCSharp);
        if (refTarget != null)
        {
            // OpenAPI 3.0: nullable $ref needs allOf wrapping — a bare $ref can't carry siblings.
            if (IsEffectivelyNullable(prop))
            {
                sb.AppendLine($"{indent}  nullable: true");
                sb.AppendLine($"{indent}  allOf:");
                sb.AppendLine($"{indent}    - $ref: '#/components/schemas/{refTarget}'");
            }
            else
                sb.AppendLine($"{indent}  $ref: '#/components/schemas/{refTarget}'");
        }
        else
        {
            if (typeKey == "array")
            {
                sb.AppendLine($"{indent}  type: array");
                if (IsEffectivelyNullable(prop))
                    sb.AppendLine($"{indent}  nullable: true");
                sb.AppendLine($"{indent}  items:");
                if (items?.RefTarget != null)
                    sb.AppendLine($"{indent}    $ref: '#/components/schemas/{items.RefTarget}'");
                else
                {
                    sb.AppendLine($"{indent}    type: {items?.TypeKey ?? "object"}");
                    if (items?.FmtKey != null) sb.AppendLine($"{indent}    format: {items.FmtKey}");
                }
            }
            else if (typeKey == "dict")
            {
                sb.AppendLine($"{indent}  type: object");
                if (IsEffectivelyNullable(prop))
                    sb.AppendLine($"{indent}  nullable: true");
                sb.AppendLine($"{indent}  additionalProperties:");
                if (items?.RefTarget != null)
                    sb.AppendLine($"{indent}    $ref: '#/components/schemas/{items.RefTarget}'");
                else
                {
                    sb.AppendLine($"{indent}    type: {items?.TypeKey ?? "object"}");
                    if (items?.FmtKey != null) sb.AppendLine($"{indent}    format: {items.FmtKey}");
                }
            }
            else
            {
                sb.AppendLine($"{indent}  type: {typeKey}");
                if (fmtKey != null) sb.AppendLine($"{indent}  format: {fmtKey}");
                if (IsEffectivelyNullable(prop))
                    sb.AppendLine($"{indent}  nullable: true");
            }
        }

        // OpenApiProperty extras override / supplement the inferred shape.
        if (prop.OpenApiFormat != null)
            sb.AppendLine($"{indent}  format: {prop.OpenApiFormat}");
        if (prop.OpenApiDescription != null)
            sb.AppendLine($"{indent}  description: {YamlString(prop.OpenApiDescription)}");
        if (prop.OpenApiExample != null)
            sb.AppendLine($"{indent}  example: {YamlScalar(prop.OpenApiExample)}");

        // Validation-derived constraints — safe to emit even when not applicable
        // to the type (OpenAPI readers ignore minLength on integers, etc.).
        if (prop.MinLength is int minLen) sb.AppendLine($"{indent}  minLength: {minLen}");
        if (prop.MaxLength is int maxLen) sb.AppendLine($"{indent}  maxLength: {maxLen}");
        if (prop.Minimum is double minVal) sb.AppendLine($"{indent}  minimum: {FormatNumber(minVal)}");
        if (prop.Maximum is double maxVal) sb.AppendLine($"{indent}  maximum: {FormatNumber(maxVal)}");
        // Regex patterns commonly contain YAML-significant chars (|, *, ?, [, ~, &).
        // Always double-quote them — safer than relying on YamlString's heuristic.
        if (prop.Pattern is string pat)
            sb.AppendLine($"{indent}  pattern: \"{pat.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"");
    }

    /// <summary>Trim ".0" from whole-double values to keep YAML tidy (e.g. 100, not 100.0).</summary>
    private static string FormatNumber(double v) =>
        v == System.Math.Floor(v) && !double.IsInfinity(v)
            ? ((long)v).ToString(CultureInfo.InvariantCulture)
            : v.ToString(CultureInfo.InvariantCulture);

    private static void EmitEnumYaml(StringBuilder sb, SchemaEnum en, string indent)
    {
        sb.AppendLine($"{indent}{en.EmittedName}:");
        sb.AppendLine($"{indent}  type: string");
        sb.AppendLine($"{indent}  enum:");
        foreach (var m in en.Members)
            sb.AppendLine($"{indent}    - {m.Name}");
    }

    // ── JSON emitter (when OutputPath ends with .json) ──────────────────────

    private static string EmitJson(SchemaModel model, OpenApiSettings oa, IReadOnlyDictionary<string, string> nameByCSharp)
    {
        // Minimal hand-rolled JSON to avoid a Newtonsoft / System.Text.Json dependency in
        // the analyzer DLL. Generator analyzers run inside the compiler — pulling in big
        // libraries here is risky, so we serialize manually for the small surface area.
        var sb = new StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine($"  \"openapi\": {JsonString(oa.OpenApiVersion)},");
        sb.AppendLine("  \"info\": {");
        sb.AppendLine($"    \"title\": {JsonString(oa.Title)},");
        sb.Append($"    \"version\": {JsonString(oa.Version)}");
        if (!string.IsNullOrEmpty(oa.Description))
        {
            sb.AppendLine(",");
            sb.AppendLine($"    \"description\": {JsonString(oa.Description!)}");
        }
        else sb.AppendLine();
        sb.AppendLine("  },");
        EmitPathsJson(sb, model);
        sb.AppendLine("  \"components\": {");
        sb.AppendLine("    \"schemas\": {");

        var first = true;
        foreach (var cls in model.Classes)
        {
            if (cls.OpenApiIgnore || (cls.Targets & TypeTarget.OpenApi) == 0) continue;
            if (!first) sb.AppendLine(",");
            first = false;
            EmitClassJson(sb, cls, nameByCSharp, "      ");
        }
        foreach (var en in model.Enums)
        {
            if (en.OpenApiIgnore || (en.Targets & TypeTarget.OpenApi) == 0) continue;
            if (!first) sb.AppendLine(",");
            first = false;
            EmitEnumJson(sb, en, "      ");
        }
        foreach (var cls in model.Classes)
        {
            if (cls.Crud is null || (cls.Crud.Operations & CrudOperations.GetList) == 0) continue;
            if (cls.OpenApiIgnore || (cls.Targets & TypeTarget.OpenApi) == 0) continue;
            if (!first) sb.AppendLine(",");
            first = false;
            EmitPaginatedSchemaJson(sb, cls, "      ");
        }
        if (!first) sb.AppendLine();

        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitClassJson(StringBuilder sb, SchemaClass cls, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        // Inheritance: emit allOf[{$ref: base}, {type: object, ...}] when the base is
        // in the model. Otherwise fall back to a single {type: object, ...} block.
        var baseRef = cls.BaseClassFullName is { } bfn && nameByCSharp.TryGetValue(bfn, out var bn) ? bn : null;
        var emittedProps = cls.Properties.Where(p => !p.OpenApiIgnore).ToList();
        var required = emittedProps.Where(p => !IsEffectivelyNullable(p)).ToList();

        sb.AppendLine($"{indent}{JsonString(cls.EmittedName)}: {{");
        if (baseRef is not null)
        {
            sb.AppendLine($"{indent}  \"allOf\": [");
            sb.AppendLine($"{indent}    {{ \"$ref\": \"#/components/schemas/{baseRef}\" }},");
            sb.Append($"{indent}    {{ \"type\": \"object\"");
            WriteRequiredAndPropsJson(sb, emittedProps, required, nameByCSharp, indent + "    ");
            sb.AppendLine();
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}  ]");
        }
        else
        {
            sb.Append($"{indent}  \"type\": \"object\"");
            WriteRequiredAndPropsJson(sb, emittedProps, required, nameByCSharp, indent + "  ");
            sb.AppendLine();
        }
        sb.Append($"{indent}}}");
    }

    private static void WriteRequiredAndPropsJson(StringBuilder sb, List<SchemaProperty> emittedProps, List<SchemaProperty> required, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        if (required.Count > 0)
        {
            sb.AppendLine(",");
            sb.Append($"{indent}\"required\": [");
            sb.Append(string.Join(", ", required.Select(r => JsonString(r.OpenApiNameOverride ?? r.SourceName))));
            sb.Append(']');
        }
        if (emittedProps.Count > 0)
        {
            sb.AppendLine(",");
            sb.AppendLine($"{indent}\"properties\": {{");
            for (int i = 0; i < emittedProps.Count; i++)
            {
                EmitPropertyJson(sb, emittedProps[i], nameByCSharp, indent + "  ");
                if (i < emittedProps.Count - 1) sb.AppendLine(",");
                else sb.AppendLine();
            }
            sb.Append($"{indent}}}");
        }
    }

    private static void EmitPropertyJson(StringBuilder sb, SchemaProperty prop, IReadOnlyDictionary<string, string> nameByCSharp, string indent)
    {
        var name = prop.OpenApiNameOverride ?? prop.SourceName;
        sb.Append($"{indent}{JsonString(name)}: {{ ");
        var (typeKey, fmtKey, refTarget, items) = ResolvePropertyShape(prop, nameByCSharp);
        var nullable = IsEffectivelyNullable(prop);
        if (refTarget != null)
        {
            if (nullable)
                sb.Append($"\"nullable\": true, \"allOf\": [{{ \"$ref\": \"#/components/schemas/{refTarget}\" }}]");
            else
                sb.Append($"\"$ref\": \"#/components/schemas/{refTarget}\"");
        }
        else if (typeKey == "array")
        {
            sb.Append("\"type\": \"array\"");
            if (nullable) sb.Append(", \"nullable\": true");
            sb.Append(", \"items\": { ");
            if (items?.RefTarget != null)
                sb.Append($"\"$ref\": \"#/components/schemas/{items.RefTarget}\"");
            else
            {
                sb.Append($"\"type\": \"{items?.TypeKey ?? "object"}\"");
                if (items?.FmtKey != null) sb.Append($", \"format\": \"{items.FmtKey}\"");
            }
            sb.Append(" }");
        }
        else if (typeKey == "dict")
        {
            sb.Append("\"type\": \"object\"");
            if (nullable) sb.Append(", \"nullable\": true");
            sb.Append(", \"additionalProperties\": { ");
            if (items?.RefTarget != null)
                sb.Append($"\"$ref\": \"#/components/schemas/{items.RefTarget}\"");
            else
            {
                sb.Append($"\"type\": \"{items?.TypeKey ?? "object"}\"");
                if (items?.FmtKey != null) sb.Append($", \"format\": \"{items.FmtKey}\"");
            }
            sb.Append(" }");
        }
        else
        {
            sb.Append($"\"type\": \"{typeKey}\"");
            if (fmtKey != null) sb.Append($", \"format\": \"{fmtKey}\"");
            if (nullable) sb.Append(", \"nullable\": true");
        }
        if (prop.OpenApiDescription != null)
            sb.Append($", \"description\": {JsonString(prop.OpenApiDescription)}");
        if (prop.MinLength is int minLen) sb.Append($", \"minLength\": {minLen}");
        if (prop.MaxLength is int maxLen) sb.Append($", \"maxLength\": {maxLen}");
        if (prop.Minimum is double minVal) sb.Append($", \"minimum\": {FormatNumber(minVal)}");
        if (prop.Maximum is double maxVal) sb.Append($", \"maximum\": {FormatNumber(maxVal)}");
        if (prop.Pattern is string pat) sb.Append($", \"pattern\": {JsonString(pat)}");
        sb.Append(" }");
    }

    private static void EmitPaginatedSchemaJson(StringBuilder sb, SchemaClass cls, string indent)
    {
        sb.AppendLine($"{indent}{JsonString(PaginatedSchemaName(cls))}: {{");
        sb.AppendLine($"{indent}  \"type\": \"object\",");
        sb.AppendLine($"{indent}  \"required\": [\"items\", \"totalCount\", \"page\", \"pageSize\", \"totalPages\", \"hasNextPage\", \"hasPreviousPage\"],");
        sb.AppendLine($"{indent}  \"properties\": {{");
        sb.AppendLine($"{indent}    \"items\": {{ \"type\": \"array\", \"items\": {{ \"$ref\": \"#/components/schemas/{cls.EmittedName}\" }} }},");
        sb.AppendLine($"{indent}    \"totalCount\": {{ \"type\": \"integer\", \"format\": \"int32\" }},");
        sb.AppendLine($"{indent}    \"page\": {{ \"type\": \"integer\", \"format\": \"int32\" }},");
        sb.AppendLine($"{indent}    \"pageSize\": {{ \"type\": \"integer\", \"format\": \"int32\" }},");
        sb.AppendLine($"{indent}    \"totalPages\": {{ \"type\": \"integer\", \"format\": \"int32\" }},");
        sb.AppendLine($"{indent}    \"hasNextPage\": {{ \"type\": \"boolean\" }},");
        sb.AppendLine($"{indent}    \"hasPreviousPage\": {{ \"type\": \"boolean\" }}");
        sb.AppendLine($"{indent}  }}");
        sb.Append($"{indent}}}");
    }

    private static void EmitEnumJson(StringBuilder sb, SchemaEnum en, string indent)
    {
        sb.AppendLine($"{indent}{JsonString(en.EmittedName)}: {{");
        sb.AppendLine($"{indent}  \"type\": \"string\",");
        sb.Append($"{indent}  \"enum\": [");
        sb.Append(string.Join(", ", en.Members.Select(m => JsonString(m.Name))));
        sb.AppendLine("]");
        sb.Append($"{indent}}}");
    }

    /// <summary>
    /// JSON paths emitter. Mirrors <see cref="EmitPathsYaml"/> but produces compact
    /// JSON. Schema content is intentionally minimal: <c>$ref</c> + <c>responses</c> +
    /// <c>requestBody</c> + path parameters. Keeps in lockstep with YAML.
    /// </summary>
    private static void EmitPathsJson(StringBuilder sb, SchemaModel model)
    {
        var crudClasses = model.Classes.Where(c => c.Crud is not null && (c.Targets & TypeTarget.OpenApi) != 0).ToList();
        if (crudClasses.Count == 0) { sb.AppendLine("  \"paths\": {},"); return; }

        sb.AppendLine("  \"paths\": {");
        var pathEntries = new List<(string Path, List<(string Verb, string Body)> Verbs)>();
        foreach (var cls in crudClasses)
        {
            var route = "/" + ResolveRoute(cls).TrimStart('/');
            var keyType = ResolveKeyParamType(cls);
            var itemPath = route + "/{" + LowerFirst(cls.Crud!.KeyProperty) + "}";
            var ops = cls.Crud.Operations;

            var coll = new List<(string, string)>();
            var item = new List<(string, string)>();
            if ((ops & CrudOperations.GetList) != 0) coll.Add(("get", BuildListJson(cls)));
            if ((ops & CrudOperations.Create) != 0) coll.Add(("post", BuildCreateJson(cls)));
            if ((ops & CrudOperations.GetById) != 0) item.Add(("get", BuildGetByIdJson(cls, keyType)));
            if ((ops & CrudOperations.Update) != 0) item.Add(("patch", BuildUpdateJson(cls, keyType)));
            if ((ops & CrudOperations.Delete) != 0) item.Add(("delete", BuildDeleteJson(cls, keyType)));

            if (coll.Count > 0) pathEntries.Add((route, coll));
            if (item.Count > 0) pathEntries.Add((itemPath, item));

            if ((ops & CrudOperations.BulkCreate) != 0)
                pathEntries.Add((route + "/bulk", new() { ("post", BuildBulkCreateJson(cls)) }));
            if ((ops & CrudOperations.BulkDelete) != 0)
                pathEntries.Add((route + "/bulk-delete", new() { ("post", BuildBulkDeleteJson(cls, keyType)) }));
        }

        for (int i = 0; i < pathEntries.Count; i++)
        {
            var (path, verbs) = pathEntries[i];
            sb.Append($"    {JsonString(path)}: {{ ");
            for (int j = 0; j < verbs.Count; j++)
            {
                sb.Append($"\"{verbs[j].Verb}\": {verbs[j].Body}");
                if (j < verbs.Count - 1) sb.Append(", ");
            }
            sb.Append(" }");
            if (i < pathEntries.Count - 1) sb.Append(',');
            sb.AppendLine();
        }
        sb.AppendLine("  },");
    }

    private static string BuildListJson(SchemaClass cls) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"list{cls.EmittedName}\", " +
        $"\"parameters\": [{BuildListQueryParamsJson(cls)}], " +
        $"\"responses\": {{ \"200\": {{ \"description\": \"OK\", \"content\": {{ \"application/json\": " +
        $"{{ \"schema\": {{ \"$ref\": \"#/components/schemas/{PaginatedSchemaName(cls)}\" }} }} }} }} }} }}";

    private static string BuildListQueryParamsJson(SchemaClass cls)
    {
        var parts = new List<string>
        {
            QueryParamJson("page", "integer", "int32", "Page number (1-based)."),
            QueryParamJson("pageSize", "integer", "int32", "Items per page."),
        };
        if (cls.QueryDsl)
        {
            parts.Add(QueryParamJson("filter", "string", null, "Filter DSL."));
            parts.Add(QueryParamJson("sort", "string", null, "Sort DSL."));
            parts.Add(QueryParamJson("select", "string", null, "Projection."));
            parts.Add(QueryParamJson("count", "boolean", null, "Returns only { count } when true."));
        }
        return string.Join(", ", parts);
    }

    private static string QueryParamJson(string name, string typeKey, string? fmtKey, string description)
    {
        var fmt = fmtKey is null ? "" : $", \"format\": \"{fmtKey}\"";
        return $"{{ \"name\": \"{name}\", \"in\": \"query\", \"description\": {JsonString(description)}, " +
               $"\"schema\": {{ \"type\": \"{typeKey}\"{fmt} }} }}";
    }

    private static string BuildBulkCreateJson(SchemaClass cls) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"bulkCreate{cls.EmittedName}\", " +
        $"\"requestBody\": {{ \"required\": true, \"content\": {{ \"application/json\": {{ \"schema\": " +
        $"{{ \"type\": \"array\", \"items\": {{ \"$ref\": \"#/components/schemas/Create{cls.SourceName}Request\" }} }} }} }} }}, " +
        $"\"responses\": {{ \"201\": {{ \"description\": \"Created\", \"content\": {{ \"application/json\": " +
        $"{{ \"schema\": {{ \"type\": \"array\", \"items\": {{ \"$ref\": \"#/components/schemas/{cls.EmittedName}\" }} }} }} }} }} }} }}";

    private static string BuildBulkDeleteJson(SchemaClass cls, (string TypeKey, string? FmtKey) kt)
    {
        var fmt = kt.FmtKey is null ? "" : $", \"format\": \"{kt.FmtKey}\"";
        return $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"bulkDelete{cls.EmittedName}\", " +
               $"\"requestBody\": {{ \"required\": true, \"content\": {{ \"application/json\": {{ \"schema\": " +
               $"{{ \"type\": \"array\", \"items\": {{ \"type\": \"{kt.TypeKey}\"{fmt} }} }} }} }} }}, " +
               $"\"responses\": {{ \"204\": {{ \"description\": \"No Content\" }} }} }}";
    }

    private static string BuildCreateJson(SchemaClass cls) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"create{cls.EmittedName}\", " +
        $"\"requestBody\": {{ \"required\": true, \"content\": {{ \"application/json\": {{ \"schema\": " +
        $"{{ \"$ref\": \"#/components/schemas/Create{cls.SourceName}Request\" }} }} }} }}, " +
        $"\"responses\": {{ \"201\": {{ \"description\": \"Created\", \"content\": {{ \"application/json\": " +
        $"{{ \"schema\": {{ \"$ref\": \"#/components/schemas/{cls.EmittedName}\" }} }} }} }} }} }}";

    private static string BuildGetByIdJson(SchemaClass cls, (string TypeKey, string? FmtKey) kt) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"get{cls.EmittedName}ById\", " +
        $"\"parameters\": [{KeyParamJson(cls.Crud!.KeyProperty, kt)}], " +
        $"\"responses\": {{ \"200\": {{ \"description\": \"OK\", \"content\": {{ \"application/json\": " +
        $"{{ \"schema\": {{ \"$ref\": \"#/components/schemas/{cls.EmittedName}\" }} }} }} }}, " +
        $"\"404\": {{ \"description\": \"Not Found\" }} }} }}";

    private static string BuildUpdateJson(SchemaClass cls, (string TypeKey, string? FmtKey) kt) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"update{cls.EmittedName}\", " +
        $"\"parameters\": [{KeyParamJson(cls.Crud!.KeyProperty, kt)}], " +
        $"\"requestBody\": {{ \"required\": true, \"content\": {{ \"application/json\": {{ \"schema\": " +
        $"{{ \"$ref\": \"#/components/schemas/Update{cls.SourceName}Request\" }} }} }} }}, " +
        $"\"responses\": {{ \"200\": {{ \"description\": \"OK\", \"content\": {{ \"application/json\": " +
        $"{{ \"schema\": {{ \"$ref\": \"#/components/schemas/{cls.EmittedName}\" }} }} }} }} }} }}";

    private static string BuildDeleteJson(SchemaClass cls, (string TypeKey, string? FmtKey) kt) =>
        $"{{ \"tags\": [\"{cls.EmittedName}\"], \"operationId\": \"delete{cls.EmittedName}\", " +
        $"\"parameters\": [{KeyParamJson(cls.Crud!.KeyProperty, kt)}], " +
        $"\"responses\": {{ \"204\": {{ \"description\": \"No Content\" }} }} }}";

    private static string KeyParamJson(string keyName, (string TypeKey, string? FmtKey) kt)
    {
        var fmt = kt.FmtKey is null ? "" : $", \"format\": \"{kt.FmtKey}\"";
        return $"{{ \"name\": \"{LowerFirst(keyName)}\", \"in\": \"path\", \"required\": true, " +
               $"\"schema\": {{ \"type\": \"{kt.TypeKey}\"{fmt} }} }}";
    }

    // ── shared mapping ──────────────────────────────────────────────────────

    /// <summary>
    /// Resolves the emitted shape for one property. Fluent <c>OpenApiRef</c> wins
    /// (emit <c>$ref</c> to the named schema, ignore inferred type entirely);
    /// fluent <c>OpenApiType</c> overrides the primary type but keeps inferred
    /// items / format unless those are also overridden. With no overrides this is
    /// just <see cref="MapCSharpToOpenApi"/> — backwards-compatible default.
    /// </summary>
    private static (string TypeKey, string? FmtKey, string? RefTarget, OpenApiTypeMapping? Items) ResolvePropertyShape(
        SchemaProperty prop, IReadOnlyDictionary<string, string> nameByCSharp)
    {
        if (prop.OpenApiRefOverride is { } refName)
            return ("$ref", null, refName, null);
        // `[UseType<T>]` — cross-target override. If T is in the model, emit a
        // $ref; if not, fall through (the target lives outside the schema — user
        // should supply OpenApiRefOverride or OpenApiTypeOverride explicitly).
        if (prop.TargetTypeCSharpFqn is { } useTypeFqn
            && nameByCSharp.TryGetValue(useTypeFqn, out var useTypeName))
            return ("$ref", null, useTypeName, null);
        var inferred = MapCSharpToOpenApi(prop.CSharpTypeFullName, nameByCSharp);
        if (prop.OpenApiTypeOverride is { } typeOverride)
            // Drop the inferred format — it was chosen to match the inferred type
            // (e.g. "double" for number) and doesn't carry over to the override.
            // The user's explicit OpenApiFormat (if any) is appended later by the caller.
            return (typeOverride, null, null, null);
        return inferred;
    }

    private sealed record OpenApiTypeMapping(string TypeKey, string? FmtKey, string? RefTarget);

    private static (string TypeKey, string? FmtKey, string? RefTarget, OpenApiTypeMapping? Items) MapCSharpToOpenApi(
        string cSharpType,
        IReadOnlyDictionary<string, string> nameByCSharp)
    {
        var t = cSharpType.TrimEnd('?');

        // PatchField<T> is ZibStack.NET.Dto's tri-state wrapper for Create/Update DTOs.
        // OpenAPI doesn't have a wire notion of tri-state — unwrap to the underlying
        // type so the schema reads like a plain field.
        var patchInner = ExtractGeneric(t, "PatchField");
        if (patchInner != null) return MapCSharpToOpenApi(patchInner, nameByCSharp);

        if (nameByCSharp.TryGetValue(t, out var refName))
            return ("$ref", null, refName, null);

        // Arrays / lists → type: array, items: ...
        if (t.EndsWith("[]"))
        {
            var inner = MapCSharpToOpenApi(t.Substring(0, t.Length - 2), nameByCSharp);
            return ("array", null, null, new OpenApiTypeMapping(inner.TypeKey, inner.FmtKey, inner.RefTarget));
        }
        var listInner = ExtractGeneric(t, "List", "IList", "ICollection", "IEnumerable", "IReadOnlyList", "IReadOnlyCollection");
        if (listInner != null)
        {
            var inner = MapCSharpToOpenApi(listInner, nameByCSharp);
            return ("array", null, null, new OpenApiTypeMapping(inner.TypeKey, inner.FmtKey, inner.RefTarget));
        }

        // Dictionary<K, V> → type: object with additionalProperties describing V.
        // OpenAPI only supports string keys, so K is ignored (same constraint as
        // JSON itself). Non-string key dicts still emit valid OpenAPI — the $ref
        // simply won't round-trip exact typing, but the shape is accurate enough
        // for consumers that serialize dicts to JSON objects.
        var dict = ExtractTwoGenericArgs(t, "Dictionary", "IDictionary", "IReadOnlyDictionary");
        if (dict != null)
        {
            var valueInner = MapCSharpToOpenApi(dict.Value.V, nameByCSharp);
            return ("dict", null, null, new OpenApiTypeMapping(valueInner.TypeKey, valueInner.FmtKey, valueInner.RefTarget));
        }

        return t switch
        {
            "string" => ("string", null, null, null),
            "bool" or "System.Boolean" => ("boolean", null, null, null),
            "byte" or "sbyte" => ("integer", "int32", null, null),
            "short" or "ushort" or "int" or "uint" or "System.Int32" => ("integer", "int32", null, null),
            "long" or "ulong" or "System.Int64" => ("integer", "int64", null, null),
            "float" or "System.Single" => ("number", "float", null, null),
            "double" or "System.Double" => ("number", "double", null, null),
            "decimal" or "System.Decimal" => ("number", "double", null, null),
            "System.Guid" or "Guid" => ("string", "uuid", null, null),
            "System.DateTime" or "DateTime" or "System.DateTimeOffset" or "DateTimeOffset" => ("string", "date-time", null, null),
            "System.DateOnly" or "DateOnly" => ("string", "date", null, null),
            "System.TimeOnly" or "TimeOnly" or "System.TimeSpan" or "TimeSpan" => ("string", "time", null, null),
            _ => ("object", null, null, null),
        };
    }

    private static (string K, string V)? ExtractTwoGenericArgs(string typeName, params string[] names)
    {
        var inner = ExtractGeneric(typeName, names);
        if (inner is null) return null;
        int depth = 0;
        for (int i = 0; i < inner.Length; i++)
        {
            if (inner[i] == '<') depth++;
            else if (inner[i] == '>') depth--;
            else if (inner[i] == ',' && depth == 0)
                return (inner.Substring(0, i).Trim(), inner.Substring(i + 1).Trim());
        }
        return null;
    }

    private static string? ExtractGeneric(string typeName, params string[] names)
    {
        foreach (var n in names)
        {
            var idx = typeName.IndexOf(n + "<", System.StringComparison.Ordinal);
            if (idx < 0) continue;
            if (idx > 0 && char.IsLetterOrDigit(typeName[idx - 1])) continue;
            int depth = 1;
            for (int i = idx + n.Length + 1; i < typeName.Length; i++)
            {
                if (typeName[i] == '<') depth++;
                else if (typeName[i] == '>') { depth--; if (depth == 0) return typeName.Substring(idx + n.Length + 1, i - idx - n.Length - 1); }
            }
        }
        return null;
    }

    private static bool IsEffectivelyNullable(SchemaProperty p) =>
        p.OpenApiNullableOverride ?? p.IsNullable;

    // ── YAML/JSON scalar formatters ──

    private static string YamlString(string s) =>
        s.Contains(':') || s.Contains('#') || s.Contains('\n') || s.StartsWith("'") || s.StartsWith("\"")
            ? $"\"{s.Replace("\"", "\\\"")}\""
            : s;

    private static string YamlScalar(object value) => value switch
    {
        string s => YamlString(s),
        bool b => b ? "true" : "false",
        null => "null",
        _ => System.Convert.ToString(value, CultureInfo.InvariantCulture) ?? "",
    };

    private static string JsonString(string s)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in s)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.Append($"\\u{(int)c:x4}");
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
