using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.EntityFramework;

[Generator]
public class EfCoreGenerator : IIncrementalGenerator
{
    private const string GenerateCrudStoresAttributeFqn = "ZibStack.NET.EntityFramework.GenerateCrudStoresAttribute";

    #region Embedded sources

    private const string GenerateCrudStoresAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.EntityFramework
{
    /// <summary>
    /// Place on a DbContext to auto-generate EfCrudStore implementations
    /// and a DI registration extension for every DbSet property.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class GenerateCrudStoresAttribute : System.Attribute { }
}
";

    private const string EfCrudStoreSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.EntityFramework
{
    /// <summary>
    /// Base EF Core implementation of <see cref=""ZibStack.NET.Dto.ICrudStore{TEntity,TKey}""/>.
    /// Override <see cref=""Set""/> to point to the correct DbSet.
    /// </summary>
    public abstract class EfCrudStore<TEntity, TKey, TContext> : ZibStack.NET.Dto.ICrudStore<TEntity, TKey>
        where TEntity : class
        where TContext : Microsoft.EntityFrameworkCore.DbContext
    {
        protected TContext Db { get; }
        protected abstract Microsoft.EntityFrameworkCore.DbSet<TEntity> Set { get; }

        protected EfCrudStore(TContext db) => Db = db;

        public virtual async System.Threading.Tasks.ValueTask<TEntity?> GetByIdAsync(TKey id, System.Threading.CancellationToken ct = default)
            => await Set.FindAsync(new object[] { id! }, ct);

        public virtual System.Linq.IQueryable<TEntity> Query()
            => Set.AsQueryable();

        public virtual async System.Threading.Tasks.ValueTask CreateAsync(TEntity entity, System.Threading.CancellationToken ct = default)
        {
            Set.Add(entity);
            await Db.SaveChangesAsync(ct);
        }

        public virtual async System.Threading.Tasks.ValueTask UpdateAsync(TEntity entity, System.Threading.CancellationToken ct = default)
        {
            await Db.SaveChangesAsync(ct);
        }

        public virtual async System.Threading.Tasks.ValueTask DeleteAsync(TEntity entity, System.Threading.CancellationToken ct = default)
        {
            Set.Remove(entity);
            await Db.SaveChangesAsync(ct);
        }
    }
}
";

    #endregion

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit attribute + base class when prerequisites are met
        var canEmit = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var hasEfCore = compilation.GetTypeByMetadataName("Microsoft.EntityFrameworkCore.DbContext") is not null;
            var hasCrudStore = compilation.GetTypeByMetadataName("ZibStack.NET.Dto.ICrudStore`2") is not null;
            return hasEfCore && hasCrudStore;
        });

        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateCrudStoresAttribute.g.cs", GenerateCrudStoresAttributeSource);
        });

        context.RegisterSourceOutput(canEmit, static (spc, can) =>
        {
            if (can)
                spc.AddSource("EfCrudStore.g.cs", EfCrudStoreSource);
        });

        // Find [GenerateCrudStores] on DbContext subclasses
        var dbContextInfos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateCrudStoresAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ExtractDbContextInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        var hasDI = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypeByMetadataName(
                "Microsoft.Extensions.DependencyInjection.IServiceCollection") is not null);

        context.RegisterSourceOutput(dbContextInfos.Combine(hasDI), static (spc, pair) =>
        {
            var (info, hasDi) = pair;
            GenerateStoresAndRegistration(spc, info, hasDi);
        });
    }

    private static DbContextInfo? ExtractDbContextInfo(GeneratorAttributeSyntaxContext context)
    {
        try
        {
            var symbol = (INamedTypeSymbol)context.TargetSymbol;

            // Verify it inherits from DbContext
            if (!InheritsFrom(symbol, "Microsoft.EntityFrameworkCore.DbContext"))
                return null;

            var contextName = symbol.Name;
            var contextFqn = symbol.ToDisplayString();
            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var dbSets = new List<DbSetEntry>();

            foreach (var member in symbol.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.DeclaredAccessibility != Accessibility.Public) continue;

                var propType = prop.Type as INamedTypeSymbol;
                if (propType is null || !propType.IsGenericType) continue;
                if (propType.ConstructedFrom.ToDisplayString() != "Microsoft.EntityFrameworkCore.DbSet<TEntity>")
                    continue;

                var entityType = propType.TypeArguments[0] as INamedTypeSymbol;
                if (entityType is null) continue;

                var keyProp = FindKeyProperty(entityType);
                if (keyProp is null) continue;

                dbSets.Add(new DbSetEntry(
                    prop.Name,
                    entityType.Name,
                    entityType.ToDisplayString(),
                    keyProp.Type.ToDisplayString()));
            }

            if (dbSets.Count == 0) return null;

            return new DbContextInfo(contextName, contextFqn, ns, dbSets);
        }
        catch
        {
            return null;
        }
    }

    private static IPropertySymbol? FindKeyProperty(INamedTypeSymbol entityType)
    {
        var allProps = GetAllProperties(entityType).ToList();

        // 1. Property with [Key] attribute
        var keyAttr = allProps.FirstOrDefault(p =>
            p.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.KeyAttribute"));
        if (keyAttr is not null) return keyAttr;

        // 2. Property named "Id"
        var id = allProps.FirstOrDefault(p => p.Name == "Id");
        if (id is not null) return id;

        // 3. Property named "{ClassName}Id"
        var classId = allProps.FirstOrDefault(p => p.Name == entityType.Name + "Id");
        return classId;
    }

    private static IEnumerable<IPropertySymbol> GetAllProperties(INamedTypeSymbol symbol)
    {
        var seen = new HashSet<string>();
        var current = symbol;
        while (current is not null)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is IPropertySymbol prop && seen.Add(prop.Name))
                    yield return prop;
            }
            current = current.BaseType;
            if (current?.SpecialType == SpecialType.System_Object) break;
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, string baseFqn)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.ToDisplayString() == baseFqn ||
                current.OriginalDefinition.ToDisplayString() == baseFqn)
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static void GenerateStoresAndRegistration(
        SourceProductionContext spc, DbContextInfo info, bool hasDI)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.EntityFramework from [GenerateCrudStores] on {info.ContextName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
            sb.AppendLine($"namespace {info.Namespace};");
        else
            sb.AppendLine("namespace ZibStack.NET.EntityFramework.Generated;");
        sb.AppendLine();

        // Emit concrete store classes
        foreach (var dbSet in info.DbSets)
        {
            sb.AppendLine($"public class {dbSet.EntityName}EfStore : ZibStack.NET.EntityFramework.EfCrudStore<{dbSet.EntityFqn}, {dbSet.KeyTypeFqn}, {info.ContextFqn}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public {dbSet.EntityName}EfStore({info.ContextFqn} db) : base(db) {{ }}");
            sb.AppendLine($"    protected override Microsoft.EntityFrameworkCore.DbSet<{dbSet.EntityFqn}> Set => Db.{dbSet.PropertyName};");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Emit DI registration extension
        if (hasDI)
        {
            sb.AppendLine($"public static class {info.ContextName}CrudStoreExtensions");
            sb.AppendLine("{");
            sb.AppendLine($"    public static Microsoft.Extensions.DependencyInjection.IServiceCollection Add{info.ContextName}CrudStores(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("    {");
            foreach (var dbSet in info.DbSets)
            {
                sb.AppendLine($"        Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<ZibStack.NET.Dto.ICrudStore<{dbSet.EntityFqn}, {dbSet.KeyTypeFqn}>, {dbSet.EntityName}EfStore>(services);");
            }
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        var hintName = info.ContextFqn.Replace(".", "_").Replace("<", "_").Replace(">", "_");
        spc.AddSource($"{hintName}.CrudStores.g.cs", sb.ToString());
    }

    // Data models — must be records/classes for Roslyn pipeline (no tuples across steps)
    private sealed class DbContextInfo
    {
        public string ContextName { get; }
        public string ContextFqn { get; }
        public string? Namespace { get; }
        public List<DbSetEntry> DbSets { get; }

        public DbContextInfo(string contextName, string contextFqn, string? ns, List<DbSetEntry> dbSets)
        {
            ContextName = contextName;
            ContextFqn = contextFqn;
            Namespace = ns;
            DbSets = dbSets;
        }
    }

    private sealed class DbSetEntry
    {
        public string PropertyName { get; }
        public string EntityName { get; }
        public string EntityFqn { get; }
        public string KeyTypeFqn { get; }

        public DbSetEntry(string propertyName, string entityName, string entityFqn, string keyTypeFqn)
        {
            PropertyName = propertyName;
            EntityName = entityName;
            EntityFqn = entityFqn;
            KeyTypeFqn = keyTypeFqn;
        }
    }
}
