using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.Dto;

public partial class DtoGenerator
{
    // ─── Embedded sources ──────────────────────────────────────────────

    private const string CreateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? Validator { get; set; }
    }
}
";

    private const string UpdateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class UpdateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? Validator { get; set; }
    }
}
";

    private const string CreateOrUpdateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateOrUpdateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? CreateValidator { get; set; }
        public System.Type? UpdateValidator { get; set; }
    }
}
";

    private const string CreateDtoForAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial record with PatchField properties, Validate(), and ToEntity()
    /// for an external type you don't control. The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateDtoForAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public CreateDtoForAttribute(System.Type targetType) => TargetType = targetType;
        public string[]? Ignore { get; set; }
        public string[]? Required { get; set; }
    }
}
";

    private const string UpdateDtoForAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial record with PatchField properties, Validate(), and ApplyTo()
    /// for an external type you don't control. The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class UpdateDtoForAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public UpdateDtoForAttribute(System.Type targetType) => TargetType = targetType;
        public string[]? Ignore { get; set; }
        public string[]? Immutable { get; set; }
    }
}
";

    private const string DtoTargetSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Flags controlling which generated DTOs a property appears in.</summary>
    [System.Flags]
    internal enum DtoTarget
    {
        Create   = 1,
        Update   = 2,
        Response = 4,
        Query    = 8,
        List     = 16,
        All      = Create | Update | Response | Query | List
    }
}
";

    private const string DtoIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Excludes a property from generated DTOs. Without arguments, excludes from
    /// Create, Update, and Query DTOs but <b>keeps</b> the property in Response
    /// (this matches the common pattern where <c>Id</c> is excluded from write DTOs
    /// but included in read responses). With a <see cref=""DtoTarget""/> argument,
    /// excludes from exactly the specified DTOs.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class DtoIgnoreAttribute : System.Attribute
    {
        public DtoTarget Target { get; }
        /// <summary>Excludes from Create + Update + Query (not Response, not List).</summary>
        public DtoIgnoreAttribute() => Target = DtoTarget.Create | DtoTarget.Update | DtoTarget.Query;
        /// <summary>Excludes from the specified targets only.</summary>
        public DtoIgnoreAttribute(DtoTarget target) => Target = target;
    }
}
";

    private const string DtoOnlyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Includes a property only in the specified DTOs. Inverse of <see cref=""DtoIgnoreAttribute""/>.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class DtoOnlyAttribute : System.Attribute
    {
        public DtoTarget Target { get; }
        public DtoOnlyAttribute(DtoTarget target) => Target = target;
    }
}
";

    private const string DtoNameAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class DtoNameAttribute : System.Attribute
    {
        public string Name { get; }
        public DtoNameAttribute(string name) => Name = name;
    }
}
";

    private const string ResponseDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class ResponseDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
    }
}
";


    private const string QueryDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>Generates a query/filter DTO with all properties nullable + ApplyFilter(IQueryable) + ApplySort(IQueryable). When ZibStack.NET.Query is referenced, also generates ApplyDslFilter, ApplyDslSort, ProjectFields. Sortable defaults to true — set Sortable=false to skip SortBy/SortDirection generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class QueryDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        /// <summary>When true (default), adds SortBy and SortDirection properties + ApplySort(IQueryable) method. Set to false for endpoints with a fixed result order (analytics, exports).</summary>
        public bool Sortable { get; set; } = true;
        /// <summary>Default sort property name (used when SortBy is null).</summary>
        public string? DefaultSort { get; set; }
        /// <summary>Default sort direction when SortDirection is null. Defaults to Asc.</summary>
        public ZibStack.NET.Dto.SortDirection DefaultSortDirection { get; set; }
    }
}
";

    private const string RenamePropertyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Renames a property from the source type in the generated DTO.
    /// Use with [CreateDtoFor] / [UpdateDtoFor]. ToEntity() and ApplyTo() map back to the original name.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class RenamePropertyAttribute : System.Attribute
    {
        public string OriginalName { get; }
        public string NewName { get; }
        public RenamePropertyAttribute(string originalName, string newName)
        {
            OriginalName = originalName;
            NewName = newName;
        }
    }
}
";

    private const string ImmutableAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Property is visible in Update DTO but skipped in ApplyTo().
    /// Useful for properties that can be set at creation but not changed later.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class ImmutableAttribute : System.Attribute { }
}
";

    private const string FlattenAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Flattens a nested object's properties into the parent DTO.
    /// Address.Street becomes AddressStreet, Address.City becomes AddressCity, etc.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class FlattenAttribute : System.Attribute { }
}
";

    private const string PaginatedResponseSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generic paginated response wrapper. Use with any ResponseDto or entity type.
    /// </summary>
    public record PaginatedResponse<T>
    {
        public System.Collections.Generic.IReadOnlyList<T> Items { get; init; } = System.Array.Empty<T>();
        public int TotalCount { get; init; }
        public int Page { get; init; }
        public int PageSize { get; init; }
        public int TotalPages => PageSize > 0 ? (int)System.Math.Ceiling((double)TotalCount / PageSize) : 0;
        public bool HasNextPage => Page < TotalPages;
        public bool HasPreviousPage => Page > 1;

        public static PaginatedResponse<T> Create(
            System.Collections.Generic.IReadOnlyList<T> items,
            int totalCount,
            int page,
            int pageSize)
        {
            return new PaginatedResponse<T>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize,
            };
        }

        public static async System.Threading.Tasks.Task<PaginatedResponse<T>> CreateAsync(
            System.Linq.IQueryable<T> query,
            int page,
            int pageSize,
            System.Threading.CancellationToken cancellationToken = default)
        {
            var totalCount = query.Count();
            var items = query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            return Create(items, totalCount, page, pageSize);
        }

        /// <summary>Maps items to a different type while preserving pagination metadata.</summary>
        public PaginatedResponse<TOut> Map<TOut>(System.Func<T, TOut> selector)
        {
            var mapped = new System.Collections.Generic.List<TOut>(Items.Count);
            foreach (var item in Items)
                mapped.Add(selector(item));

            return new PaginatedResponse<TOut>
            {
                Items = mapped,
                TotalCount = TotalCount,
                Page = Page,
                PageSize = PageSize,
            };
        }
    }
}
";

    private const string SortDirectionSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Sort direction for sortable query DTOs.</summary>
    public enum SortDirection
    {
        Asc,
        Desc
    }
}
";

    private const string DtoValidatorInterfaceSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Implement this interface to provide custom validation for a generated request class.
    /// Set via [Dto(CreateValidator = typeof(...))] or [Dto(UpdateValidator = typeof(...))].
    /// </summary>
    /// <summary>
    /// Validation result with per-property error grouping.
    /// Compatible with ASP.NET ProblemDetails via <see cref=""ToDictionary""/>.
    /// </summary>
    public sealed class DtoValidationResult
    {
        private readonly System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> _errors = new();

        /// <summary>True when there are no errors.</summary>
        public bool IsValid => _errors.Count == 0;

        /// <summary>Errors grouped by property name. Empty key = general errors.</summary>
        public System.Collections.Generic.IReadOnlyDictionary<string, string[]> Errors
        {
            get
            {
                var dict = new System.Collections.Generic.Dictionary<string, string[]>();
                foreach (var kv in _errors)
                    dict[kv.Key] = kv.Value.ToArray();
                return dict;
            }
        }

        /// <summary>Add an error for a specific property.</summary>
        public DtoValidationResult AddError(string property, string message)
        {
            if (!_errors.TryGetValue(property, out var list))
            {
                list = new System.Collections.Generic.List<string>();
                _errors[property] = list;
            }
            list.Add(message);
            return this;
        }

        /// <summary>Add a general error (not tied to a property).</summary>
        public DtoValidationResult AddError(string message) => AddError("""", message);

        /// <summary>Merge errors from another DtoValidationResult, optionally prefixing property names.</summary>
        public DtoValidationResult Merge(DtoValidationResult other, string? prefix = null)
        {
            foreach (var kv in other._errors)
            {
                var key = prefix is not null && kv.Key.Length > 0 ? prefix + ""."" + kv.Key
                        : prefix is not null ? prefix
                        : kv.Key;
                foreach (var msg in kv.Value)
                    AddError(key, msg);
            }
            return this;
        }

        /// <summary>Convert to dictionary for Results.ValidationProblem().</summary>
        public System.Collections.Generic.Dictionary<string, string[]> ToDictionary()
        {
            var dict = new System.Collections.Generic.Dictionary<string, string[]>();
            foreach (var kv in _errors)
                dict[kv.Key] = kv.Value.ToArray();
            return dict;
        }
    }

    public interface IDtoValidator<T>
    {
        DtoValidationResult Validate(T instance);
    }

    public interface ICanCreate<T>
    {
        T ToEntity();
    }

    public interface ICanApply<T>
    {
        void ApplyTo(T target);
    }

    public interface ICanValidate
    {
        DtoValidationResult Validate();
    }
}
";

    private const string FluentDtoValidatorSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Base class that bridges FluentValidation with ZibStack.NET.Dto validation.
    /// Extend this instead of AbstractValidator to use with [Dto(CreateValidator/UpdateValidator)].
    /// </summary>
    public abstract class FluentDtoValidator<T> : FluentValidation.AbstractValidator<T>, IDtoValidator<T>
    {
        DtoValidationResult IDtoValidator<T>.Validate(T instance)
        {
            var fluentResult = base.Validate(instance);
            var result = new DtoValidationResult();
            foreach (var failure in fluentResult.Errors)
                result.AddError(failure.PropertyName, failure.ErrorMessage);
            return result;
        }
    }
}
";

    private const string PatchFieldSchemaFilterSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Swagger/Swashbuckle schema filter that unwraps PatchField&lt;T&gt; to its inner type.
    /// Register via: options.SchemaFilter&lt;PatchFieldSchemaFilter&gt;();
    /// </summary>
    public sealed class PatchFieldSchemaFilter : Swashbuckle.AspNetCore.SwaggerGen.ISchemaFilter
    {
        public void Apply(Microsoft.OpenApi.Models.OpenApiSchema schema, Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext context)
        {
            var type = context.Type;
            if (!type.IsGenericType || type.GetGenericTypeDefinition() != typeof(PatchField<>))
                return;

            var innerType = type.GetGenericArguments()[0];
            var innerSchema = context.SchemaGenerator.GenerateSchema(innerType, context.SchemaRepository);

            schema.Type = innerSchema.Type;
            schema.Format = innerSchema.Format;
            schema.Reference = innerSchema.Reference;
            schema.Items = innerSchema.Items;
            schema.Properties = innerSchema.Properties;
            schema.Nullable = innerSchema.Nullable || (innerType.IsClass && !innerType.IsValueType);
            schema.Enum = innerSchema.Enum;
        }
    }
}
";

    private const string PatchFieldSchemaFilterV10Source = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Swagger/Swashbuckle 10+ schema filter that unwraps PatchField&lt;T&gt; to its inner type.
    /// Register via: options.SchemaFilter&lt;PatchFieldSchemaFilter&gt;();
    /// </summary>
    public sealed class PatchFieldSchemaFilter : Swashbuckle.AspNetCore.SwaggerGen.ISchemaFilter
    {
        public void Apply(Microsoft.OpenApi.IOpenApiSchema schema, Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext context)
        {
            var type = context.Type;
            if (!type.IsGenericType || type.GetGenericTypeDefinition() != typeof(PatchField<>))
                return;

            if (schema is not Microsoft.OpenApi.OpenApiSchema concrete) return;

            var innerType = type.GetGenericArguments()[0];
            var innerSchema = context.SchemaGenerator.GenerateSchema(innerType, context.SchemaRepository);

            if (innerSchema is Microsoft.OpenApi.OpenApiSchema concreteInner)
            {
                concrete.Type = concreteInner.Type;
                concrete.Format = concreteInner.Format;
                concrete.Items = concreteInner.Items;
                concrete.Enum = concreteInner.Enum;
            }

            concrete.Properties.Clear();
        }
    }
}
";
}
