using System.Collections.Generic;
using System.Text;

namespace ZibStack.NET.Dto;

public partial class DtoGenerator
{
    // CrudOperations flag values (must match enum)
    private const int OpGetById = 1;
    private const int OpGetList = 2;
    private const int OpCreate = 4;
    private const int OpUpdate = 8;
    private const int OpDelete = 16;
    private const int OpBulkCreate = 32;
    private const int OpBulkDelete = 64;

    // ApiStyle values (must match enum)
    private const int StyleMinimalApi = 0;
    private const int StyleController = 1;
    private const int StyleBoth = 2;

    private static string GenerateMinimalApiSource(CrudApiInfo info)
    {
        var sb = new StringBuilder();
        var entity = info.ClassName;
        var fqEntity = info.Namespace is not null ? $"{info.Namespace}.{entity}" : entity;
        var keyType = info.KeyTypeName;
        var storeType = $"ZibStack.NET.Dto.ICrudStore<{fqEntity}, {keyType}>";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [CrudApi] on {entity}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using ZibStack.NET.Dto;");

        if (info.Namespace is not null)
        {
            sb.AppendLine($"using {info.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace ?? "ZibStack.NET.Dto.Generated"};");
        sb.AppendLine();
        var dtoList = new List<string>();
        if (info.CreateRequestName != null) dtoList.Add($"<see cref=\"{info.CreateRequestName}\"/>");
        if (info.UpdateRequestName != null) dtoList.Add($"<see cref=\"{info.UpdateRequestName}\"/>");
        if (info.ResponseName != null) dtoList.Add($"<see cref=\"{info.ResponseName}\"/>");
        if (info.QueryName != null) dtoList.Add($"<see cref=\"{info.QueryName}\"/>");
        sb.AppendLine($"/// <summary>Auto-generated CRUD endpoints for <see cref=\"{entity}\"/>. Route: {info.Route}. DTOs: {string.Join(", ", dtoList)}</summary>");
        sb.AppendLine($"public static class {entity}Endpoints");
        sb.AppendLine("{");
        sb.AppendLine($"    public static RouteGroupBuilder Map{entity}Endpoints(this IEndpointRouteBuilder app, string? prefix = null, Action<RouteGroupBuilder>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var group = app.MapGroup(prefix ?? \"{info.Route}\")");
        sb.AppendLine($"            .WithTags(\"{entity}\");");
        sb.AppendLine();

        if (info.AuthorizePolicy is not null)
        {
            sb.AppendLine($"        group.RequireAuthorization(\"{info.AuthorizePolicy}\");");
            sb.AppendLine();
        }

        sb.AppendLine("        configure?.Invoke(group);");
        sb.AppendLine();

        // GET {id}
        if ((info.Operations & OpGetById) != 0)
        {
            sb.AppendLine($"        group.MapGet(\"{{id}}\", async ({keyType} id, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entity);");
            }
            var getByIdChain = $"}}).WithName(\"Get{entity}\")";
            if (info.GetByIdPolicy is not null)
                getByIdChain += $".RequireAuthorization(\"{info.GetByIdPolicy}\")";
            sb.AppendLine($"        {getByIdChain};");
            sb.AppendLine();
        }

        // GET list
        if ((info.Operations & OpGetList) != 0)
        {
            // Use ListResponseName (from [DtoIgnore(DtoTarget.List)]) if available, otherwise ResponseName
            var listResponseType = info.ListResponseName ?? info.ResponseName;
            var fqListResponse = info.HasResponseDto && listResponseType is not null
                ? (info.Namespace is not null ? $"{info.Namespace}.{listResponseType}" : listResponseType)
                : null;

            // DSL filter/sort/select params (when ZibStack.NET.Query is referenced)
            var dslParams = info.HasQueryDsl ? ", string? filter = null, string? sort = null, string? select = null, bool count = false" : "";
            var fqQuery = info.HasQueryDto && info.QueryName is not null
                ? (info.Namespace is not null ? $"{info.Namespace}.{info.QueryName}" : info.QueryName)
                : null;

            if (fqQuery is not null)
            {
                var asyncKeyword = info.HasQueryDsl ? "async " : "";
                sb.AppendLine($"        group.MapGet(\"\", {asyncKeyword}([Microsoft.AspNetCore.Http.AsParameters] {fqQuery} query,");
                sb.AppendLine($"            {storeType} store, int page = 1, int pageSize = 20{dslParams}, CancellationToken ct = default) =>");
                sb.AppendLine("        {");
                sb.AppendLine("            var q = store.Query();");
                sb.AppendLine(info.HasQueryDsl
                    ? "            q = query.Apply(q, filter, sort);"
                    : "            q = query.Apply(q);");
            }
            else
            {
                sb.AppendLine($"        group.MapGet(\"\", ({storeType} store, int page = 1, int pageSize = 20{dslParams}, CancellationToken ct = default) =>");
                sb.AppendLine("        {");
                sb.AppendLine("            var q = store.Query();");
            }

            // count=true — return just the count without fetching data
            if (info.HasQueryDsl)
            {
                sb.AppendLine("            if (count) return Results.Ok(new { count = q.Count() });");
            }

            // select= field projection (when ZibStack.NET.Query is referenced)
            if (info.HasQueryDsl && fqQuery is not null)
            {
                sb.AppendLine("            if (select is not null)");
                sb.AppendLine("            {");
                sb.AppendLine("                var fields = ZibStack.NET.Query.SelectParser.Parse(select);");
                sb.AppendLine($"                q = {fqQuery}.ApplyIncludes(q, fields);");
                sb.AppendLine("                var totalCount = q.Count();");
                sb.AppendLine("                var items = q.Skip((page - 1) * pageSize).Take(pageSize).ToList();");
                sb.AppendLine($"                var projected = items.Select(e => {fqQuery}.ProjectFields(e, fields)).ToList();");
                sb.AppendLine("                return Results.Ok(new { items = projected, totalCount, page, pageSize });");
                sb.AppendLine("            }");
            }

            if (fqListResponse is not null)
            {
                sb.AppendLine($"            var defaultProjected = {fqListResponse}.ProjectFrom(q);");
                if (info.HasQueryDsl)
                    sb.AppendLine($"            return Results.Ok(await PaginatedResponse<{fqListResponse}>.CreateAsync(defaultProjected, page, pageSize, ct));");
                else
                    sb.AppendLine($"            return PaginatedResponse<{fqListResponse}>.CreateAsync(defaultProjected, page, pageSize, ct);");
            }
            else
            {
                if (info.HasQueryDsl)
                    sb.AppendLine($"            return Results.Ok(await PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct));");
                else
                    sb.AppendLine($"            return PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct);");
            }
            sb.AppendLine($"        }}).WithName(\"Get{entity}List\"){(info.GetListPolicy is not null ? $".RequireAuthorization(\"{info.GetListPolicy}\")" : "")};");
            sb.AppendLine();
        }

        // POST
        if ((info.Operations & OpCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine($"        group.MapPost(\"\", async ({fqCreate} request, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var validation = request.{validateMethod}();");
            sb.AppendLine("            if (!validation.IsValid) return Results.ValidationProblem(validation.ToDictionary());");
            sb.AppendLine("            var entity = request.ToEntity();");
            sb.AppendLine("            await store.CreateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.CreatedAtRoute(\"Get{entity}\", new {{ id = entity.{info.KeyPropertyName} }}, {fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine($"            return Results.CreatedAtRoute(\"Get{entity}\", new {{ id = entity.{info.KeyPropertyName} }}, entity);");
            }
            var postChain = "        })";
            if (info.CreatePolicy is not null)
                postChain += $".RequireAuthorization(\"{info.CreatePolicy}\")";
            sb.AppendLine(postChain + ";");
            sb.AppendLine();
        }

        // PATCH
        if ((info.Operations & OpUpdate) != 0 && info.UpdateRequestName is not null)
        {
            var fqUpdate = info.Namespace is not null ? $"{info.Namespace}.{info.UpdateRequestName}" : info.UpdateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForUpdate" : "Validate";
            sb.AppendLine($"        group.MapPatch(\"{{id}}\", async ({keyType} id, {fqUpdate} request, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            sb.AppendLine($"            var validation = request.{validateMethod}();");
            sb.AppendLine("            if (!validation.IsValid) return Results.ValidationProblem(validation.ToDictionary());");
            sb.AppendLine("            request.ApplyTo(entity);");
            sb.AppendLine("            await store.UpdateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entity);");
            }
            var patchChain = "        })";
            if (info.UpdatePolicy is not null)
                patchChain += $".RequireAuthorization(\"{info.UpdatePolicy}\")";
            sb.AppendLine(patchChain + ";");
            sb.AppendLine();
        }

        // DELETE
        if ((info.Operations & OpDelete) != 0)
        {
            sb.AppendLine($"        group.MapDelete(\"{{id}}\", async ({keyType} id, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            sb.AppendLine("            await store.DeleteAsync(entity, ct);");
            sb.AppendLine("            return Results.NoContent();");
            var deleteChain = "        })";
            if (info.DeletePolicy is not null)
                deleteChain += $".RequireAuthorization(\"{info.DeletePolicy}\")";
            sb.AppendLine(deleteChain + ";");
            sb.AppendLine();
        }

        // BULK CREATE
        if ((info.Operations & OpBulkCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine($"        group.MapPost(\"bulk\", async (List<{fqCreate}> requests, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var allErrors = new DtoValidationResult();");
            sb.AppendLine("            for (var i = 0; i < requests.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var validation = requests[i].{validateMethod}();");
            sb.AppendLine("                allErrors.Merge(validation, $\"[{i}]\");");
            sb.AppendLine("            }");
            sb.AppendLine("            if (!allErrors.IsValid) return Results.ValidationProblem(allErrors.ToDictionary());");
            sb.AppendLine($"            var entities = new List<{fqEntity}>();");
            sb.AppendLine("            foreach (var request in requests)");
            sb.AppendLine("            {");
            sb.AppendLine("                var entity = request.ToEntity();");
            sb.AppendLine("                await store.CreateAsync(entity, ct);");
            sb.AppendLine("                entities.Add(entity);");
            sb.AppendLine("            }");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok(entities.Select(e => {fqResponse}.FromEntity(e)).ToList());");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entities);");
            }
            var bulkCreateChain = "        })";
            if (info.CreatePolicy is not null)
                bulkCreateChain += $".RequireAuthorization(\"{info.CreatePolicy}\")";
            sb.AppendLine(bulkCreateChain + ";");
            sb.AppendLine();
        }

        // BULK DELETE
        if ((info.Operations & OpBulkDelete) != 0)
        {
            sb.AppendLine($"        group.MapPost(\"bulk-delete\", async (List<{keyType}> ids, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var deleted = 0;");
            sb.AppendLine("            foreach (var id in ids)");
            sb.AppendLine("            {");
            sb.AppendLine("                var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("                if (entity is not null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    await store.DeleteAsync(entity, ct);");
            sb.AppendLine("                    deleted++;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return Results.Ok(new { deleted });");
            var bulkDeleteChain = "        })";
            if (info.DeletePolicy is not null)
                bulkDeleteChain += $".RequireAuthorization(\"{info.DeletePolicy}\")";
            sb.AppendLine(bulkDeleteChain + ";");
            sb.AppendLine();
        }

        sb.AppendLine("        return group;");
        sb.AppendLine("    }");

        // Generate permission filter helper if [ColumnPermission] attributes exist
        if (info.ColumnPermissions.Count > 0 && info.HasResponseDto && info.ResponseName is not null)
        {
            var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Nulls restricted properties on the response based on user claims.</summary>");
            sb.AppendLine($"    public static {fqResponse} ApplyColumnPermissions({fqResponse} response, System.Security.Claims.ClaimsPrincipal? user)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (user is null) return response;");
            foreach (var kv in info.ColumnPermissions)
            {
                sb.AppendLine($"        if (!user.HasClaim(\"permission\", \"{kv.Value}\") && !user.IsInRole(\"{kv.Value}\"))");
                sb.AppendLine($"            response = response with {{ {kv.Key} = default }};");
            }
            sb.AppendLine("        return response;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateControllerSource(CrudApiInfo info)
    {
        var sb = new StringBuilder();
        var entity = info.ClassName;
        var fqEntity = info.Namespace is not null ? $"{info.Namespace}.{entity}" : entity;
        var keyType = info.KeyTypeName;
        var storeType = $"ZibStack.NET.Dto.ICrudStore<{fqEntity}, {keyType}>";
        var controllerName = $"{entity}CrudController";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [CrudApi] on {entity}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using ZibStack.NET.Dto;");

        if (info.Namespace is not null)
        {
            sb.AppendLine($"using {info.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace ?? "ZibStack.NET.Dto.Generated"};");
        sb.AppendLine();

        if (info.AuthorizePolicy is not null)
            sb.AppendLine($"[Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.AuthorizePolicy}\")]");

        sb.AppendLine("[ApiController]");
        sb.AppendLine($"[Route(\"{info.Route}\")]");
        sb.AppendLine($"public partial class {controllerName} : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {storeType} _store;");
        sb.AppendLine();
        sb.AppendLine($"    public {controllerName}({storeType} store) => _store = store;");

        // GET {id}
        if ((info.Operations & OpGetById) != 0)
        {
            sb.AppendLine();
            if (info.GetByIdPolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.GetByIdPolicy}\")]");
            sb.AppendLine("    [HttpGet(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> GetById({keyType} id, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("        return Ok(entity);");
            }
            sb.AppendLine("    }");
        }

        // GET list
        if ((info.Operations & OpGetList) != 0)
        {
            sb.AppendLine();
            if (info.GetListPolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.GetListPolicy}\")]");
            if (info.HasQueryDto && info.QueryName is not null)
            {
                var fqQuery = info.Namespace is not null ? $"{info.Namespace}.{info.QueryName}" : info.QueryName;
                sb.AppendLine("    [HttpGet]");
                sb.AppendLine($"    public async Task<IActionResult> GetList([FromQuery] {fqQuery} query, int page = 1, int pageSize = 20, CancellationToken ct = default)");
                sb.AppendLine("    {");
                sb.AppendLine("        var q = query.Apply(_store.Query());");
            }
            else
            {
                sb.AppendLine("    [HttpGet]");
                sb.AppendLine("    public async Task<IActionResult> GetList(int page = 1, int pageSize = 20, CancellationToken ct = default)");
                sb.AppendLine("    {");
                sb.AppendLine("        var q = _store.Query();");
            }

            var ctrlListType = info.ListResponseName ?? info.ResponseName;
            var fqCtrlList = info.HasResponseDto && ctrlListType is not null
                ? (info.Namespace is not null ? $"{info.Namespace}.{ctrlListType}" : ctrlListType)
                : null;
            if (fqCtrlList is not null)
            {
                sb.AppendLine($"        var projected = {fqCtrlList}.ProjectFrom(q);");
                sb.AppendLine($"        var result = await PaginatedResponse<{fqCtrlList}>.CreateAsync(projected, page, pageSize, ct);");
            }
            else
            {
                sb.AppendLine($"        var result = await PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct);");
            }
            sb.AppendLine("        return Ok(result);");
            sb.AppendLine("    }");
        }

        // POST
        if ((info.Operations & OpCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine();
            if (info.CreatePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.CreatePolicy}\")]");
            sb.AppendLine("    [HttpPost]");
            sb.AppendLine($"    public async Task<IActionResult> Create([FromBody] {fqCreate} request, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var validation = request.{validateMethod}();");
            sb.AppendLine("        if (!validation.IsValid) { foreach (var kv in validation.Errors) foreach (var msg in kv.Value) ModelState.AddModelError(kv.Key, msg); return ValidationProblem(); }");
            sb.AppendLine("        var entity = request.ToEntity();");
            sb.AppendLine("        await _store.CreateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return CreatedAtAction(nameof(GetById), new {{ id = entity.{info.KeyPropertyName} }}, {fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine($"        return CreatedAtAction(nameof(GetById), new {{ id = entity.{info.KeyPropertyName} }}, entity);");
            }
            sb.AppendLine("    }");
        }

        // PATCH
        if ((info.Operations & OpUpdate) != 0 && info.UpdateRequestName is not null)
        {
            var fqUpdate = info.Namespace is not null ? $"{info.Namespace}.{info.UpdateRequestName}" : info.UpdateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForUpdate" : "Validate";
            sb.AppendLine();
            if (info.UpdatePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.UpdatePolicy}\")]");
            sb.AppendLine("    [HttpPatch(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> Update({keyType} id, [FromBody] {fqUpdate} request, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            sb.AppendLine($"        var validation = request.{validateMethod}();");
            sb.AppendLine("        if (!validation.IsValid) { foreach (var kv in validation.Errors) foreach (var msg in kv.Value) ModelState.AddModelError(kv.Key, msg); return ValidationProblem(); }");
            sb.AppendLine("        request.ApplyTo(entity);");
            sb.AppendLine("        await _store.UpdateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("        return Ok(entity);");
            }
            sb.AppendLine("    }");
        }

        // DELETE
        if ((info.Operations & OpDelete) != 0)
        {
            sb.AppendLine();
            if (info.DeletePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.DeletePolicy}\")]");
            sb.AppendLine("    [HttpDelete(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> Delete({keyType} id, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            sb.AppendLine("        await _store.DeleteAsync(entity, ct);");
            sb.AppendLine("        return NoContent();");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCodeMap(CrudApiInfo info)
    {
        var sb = new StringBuilder();
        var entity = info.ClassName;
        var ns = info.Namespace;
        // Fully-qualify crefs so F12 / Go-to-Definition resolves regardless of which
        // file the user is in or whether using directives are in scope. Bare names
        // worked when the user happened to have ZibStack.NET.Dto + entity namespace
        // imported — fragile, especially across solutions with multiple namespaces.
        // Note: Rider has a known bug where clicking these crefs in the QuickInfo
        // popup raises "Malformed URL: psi_element://cref://T:..." for source-gen
        // targets even with EmitCompilerGeneratedFiles=true. Works in VS; in Rider
        // navigate via Ctrl+Click on the type name in actual call sites instead.
        string Cref(string typeName) => ns is null ? typeName : $"{ns}.{typeName}";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// <b>Generated artifacts for <c>{entity}</c>.</b>");
        sb.AppendLine("/// Files live under <c>obj/&lt;config&gt;/&lt;tfm&gt;/generated/ZibStack.NET.Dto/</c>");
        sb.AppendLine($"/// — search for <c>{entity.Replace("?", "_").Replace("<", "_").Replace(">", "_")}.*.g.cs</c>.");
        sb.AppendLine("/// <list type=\"bullet\">");
        if (info.CreateRequestName != null)
            sb.AppendLine($"/// <item><description>Create DTO: <see cref=\"{Cref(info.CreateRequestName)}\"/> — <c>ToEntity()</c>, <c>Validate()</c></description></item>");
        if (info.UpdateRequestName != null)
            sb.AppendLine($"/// <item><description>Update DTO: <see cref=\"{Cref(info.UpdateRequestName)}\"/> — <c>ApplyTo(target)</c>, <c>Validate()</c></description></item>");
        if (info.ResponseName != null)
            sb.AppendLine($"/// <item><description>Response: <see cref=\"{Cref(info.ResponseName)}\"/> — <c>FromEntity(entity)</c>, <c>ProjectFrom(IQueryable)</c></description></item>");
        if (info.ListResponseName != null)
            sb.AppendLine($"/// <item><description>List item: <see cref=\"{Cref(info.ListResponseName)}\"/> — <c>ProjectFrom(IQueryable)</c></description></item>");
        if (info.QueryName != null)
            sb.AppendLine($"/// <item><description>Query: <see cref=\"{Cref(info.QueryName)}\"/> — <c>ApplyFilter()</c>, <c>ApplySort()</c>, <c>Apply(IQueryable)</c></description></item>");
        sb.AppendLine($"/// <item><description>Endpoints: <see cref=\"{Cref(entity + "Endpoints")}\"/> — <c>Map{entity}Endpoints(this IEndpointRouteBuilder)</c></description></item>");
        sb.AppendLine("/// </list>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"partial class {entity} {{ }}");

        return sb.ToString();
    }
}
