namespace ZibStack.NET.Dto;

/// <summary>
/// PostInit-injected source for the fluent <c>IDtoConfigurator</c> DSL — a
/// project-wide alternative to scattering <c>[CreateDto]</c> / <c>[UpdateDto]</c>
/// / <c>[ResponseDto]</c> / <c>[QueryDto]</c> markers across model files.
/// Per-property attributes (<c>[DtoIgnore]</c>, <c>[DtoOnly]</c>, <c>[DtoName]</c>,
/// <c>[Flatten]</c>) and <c>[CrudApi]</c> stay on the model — locality wins for
/// per-property concerns and CRUD endpoints have a runtime aspect worth flagging
/// at declaration time. Cross-type bindings (<c>[CreateDtoFor]</c>, <c>[UpdateDtoFor]</c>)
/// also stay since they declare a partial record's relationship to an external type.
/// </summary>
public partial class DtoGenerator
{
    // Single string — interfaces + options classes share namespace and need to
    // appear in one compilation unit so cross-references resolve.
    private const string ConfiguratorSource = @"// <auto-generated by ZibStack.NET.Dto />
#nullable enable
using System;
using System.Linq.Expressions;

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Project-wide DTO configuration. Implement once per project; the generator
    /// auto-discovers the type and parses the <c>Configure</c> method body at
    /// compile time. Body is never invoked at runtime — all arguments must be
    /// literal expressions or constants.
    /// </summary>
    internal interface IDtoConfigurator
    {
        void Configure(IDtoBuilder builder);
    }

    /// <summary>Top-level fluent entry point. Currently only <c>ForType&lt;T&gt;()</c>.</summary>
    internal interface IDtoBuilder
    {
        IDtoTypeBuilder<T> ForType<T>();
    }

    /// <summary>
    /// Per-type builder — selects which companion DTOs to generate and (via
    /// <c>Property</c>) overrides per-property settings without touching the model.
    /// </summary>
    internal interface IDtoTypeBuilder<T>
    {
        /// <summary>Equivalent to <c>[CreateDto]</c> on the class.</summary>
        IDtoTypeBuilder<T> CreateDto(Action<CreateDtoOptions>? configure = null);

        /// <summary>Equivalent to <c>[UpdateDto]</c> on the class.</summary>
        IDtoTypeBuilder<T> UpdateDto(Action<UpdateDtoOptions>? configure = null);

        /// <summary>Equivalent to <c>[CreateOrUpdateDto]</c> — single DTO usable for both.</summary>
        IDtoTypeBuilder<T> CreateOrUpdateDto(Action<CreateOrUpdateDtoOptions>? configure = null);

        /// <summary>Equivalent to <c>[ResponseDto]</c>.</summary>
        IDtoTypeBuilder<T> ResponseDto(Action<ResponseDtoOptions>? configure = null);

        /// <summary>Equivalent to <c>[QueryDto]</c>.</summary>
        IDtoTypeBuilder<T> QueryDto(Action<QueryDtoOptions>? configure = null);

        /// <summary>
        /// Configures the <c>[CrudApi]</c> attribute that's still on the class — sets
        /// route / operations / auth policies. Doesn't add the attribute itself
        /// (the attribute is the runtime-visible marker that says 'this is an endpoint').
        /// </summary>
        IDtoTypeBuilder<T> CrudApi(Action<CrudApiOptions> configure);

        /// <summary>Begin per-property overrides for <typeparamref name=""T""/>.</summary>
        IDtoPropertyBuilder<T, TProp> Property<TProp>(Expression<Func<T, TProp>> selector);
    }

    /// <summary>Per-property fluent overrides. Mirrors the per-property attributes.</summary>
    internal interface IDtoPropertyBuilder<TClass, TProp>
    {
        /// <summary>Equivalent to <c>[DtoIgnore]</c> (no args) — exclude from every DTO variant.</summary>
        IDtoPropertyBuilder<TClass, TProp> Ignore();

        /// <summary>Equivalent to <c>[DtoIgnore(targets)]</c>.</summary>
        IDtoPropertyBuilder<TClass, TProp> IgnoreIn(DtoTarget targets);

        /// <summary>Equivalent to <c>[DtoOnly(targets)]</c>.</summary>
        IDtoPropertyBuilder<TClass, TProp> OnlyIn(DtoTarget targets);

        /// <summary>Equivalent to <c>[DtoName(name)]</c>.</summary>
        IDtoPropertyBuilder<TClass, TProp> RenameTo(string name);

        /// <summary>Equivalent to <c>[Flatten]</c>.</summary>
        IDtoPropertyBuilder<TClass, TProp> Flatten();

        /// <summary>Continue with another property on the same owning type.</summary>
        IDtoPropertyBuilder<TClass, TNext> Property<TNext>(Expression<Func<TClass, TNext>> selector);
    }

    internal sealed class CreateDtoOptions
    {
        public string? Name { get; set; }
        public Type? Validator { get; set; }
    }

    internal sealed class UpdateDtoOptions
    {
        public string? Name { get; set; }
        public Type? Validator { get; set; }
    }

    internal sealed class CreateOrUpdateDtoOptions
    {
        public string? Name { get; set; }
        public Type? CreateValidator { get; set; }
        public Type? UpdateValidator { get; set; }
    }

    internal sealed class ResponseDtoOptions
    {
        public string? Name { get; set; }
    }

    internal sealed class QueryDtoOptions
    {
        public string? Name { get; set; }
        public bool Sortable { get; set; } = true;
        public string? DefaultSort { get; set; }
        public SortDirection DefaultSortDirection { get; set; } = SortDirection.Asc;
    }

    internal sealed class CrudApiOptions
    {
        public string? Route { get; set; }
        public string? RoutePrefix { get; set; }
        public string KeyProperty { get; set; } = ""Id"";
        public CrudOperations Operations { get; set; } = CrudOperations.All;
        public ApiStyle Style { get; set; } = ApiStyle.MinimalApi;
        public string? AuthorizePolicy { get; set; }
        public string? GetByIdPolicy { get; set; }
        public string? GetListPolicy { get; set; }
        public string? CreatePolicy { get; set; }
        public string? UpdatePolicy { get; set; }
        public string? DeletePolicy { get; set; }
    }
}
";
}
