using System.Text;

namespace ZibStack.NET.Dto;

public partial class DtoGenerator
{
    // CrudOperations flag values (must match enum)
    private const int OpGetById = 1;
    private const int OpGetList = 2;
    private const int OpCreate = 4;
    private const int OpUpdate = 8;
    private const int OpDelete = 16;
    private const int OpBulkCreate = 32;
    private const int OpBulkDelete = 64;

    // ApiStyle values (must match enum)
    private const int StyleMinimalApi = 0;
    private const int StyleController = 1;
    private const int StyleBoth = 2;

    private static string GenerateMinimalApiSource(CrudApiInfo info)
    {
        var sb = new StringBuilder();
        var entity = info.ClassName;
        var fqEntity = info.Namespace is not null ? $"{info.Namespace}.{entity}" : entity;
        var keyType = info.KeyTypeName;
        var storeType = $"ZibStack.NET.Dto.ICrudStore<{fqEntity}, {keyType}>";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [CrudApi] on {entity}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using ZibStack.NET.Dto;");

        if (info.Namespace is not null)
        {
            sb.AppendLine($"using {info.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace ?? "ZibStack.NET.Dto.Generated"};");
        sb.AppendLine();
        sb.AppendLine($"public static class {entity}Endpoints");
        sb.AppendLine("{");
        sb.AppendLine($"    public static RouteGroupBuilder Map{entity}Endpoints(this IEndpointRouteBuilder app, string? prefix = null, Action<RouteGroupBuilder>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var group = app.MapGroup(prefix ?? \"{info.Route}\")");
        sb.AppendLine($"            .WithTags(\"{entity}\");");
        sb.AppendLine();

        if (info.AuthorizePolicy is not null)
        {
            sb.AppendLine($"        group.RequireAuthorization(\"{info.AuthorizePolicy}\");");
            sb.AppendLine();
        }

        sb.AppendLine("        configure?.Invoke(group);");
        sb.AppendLine();

        // GET {id}
        if ((info.Operations & OpGetById) != 0)
        {
            sb.AppendLine($"        group.MapGet(\"{{id}}\", async ({keyType} id, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entity);");
            }
            var getByIdChain = $"}}).WithName(\"Get{entity}\")";
            if (info.GetByIdPolicy is not null)
                getByIdChain += $".RequireAuthorization(\"{info.GetByIdPolicy}\")";
            sb.AppendLine($"        {getByIdChain};");
            sb.AppendLine();
        }

        // GET list
        if ((info.Operations & OpGetList) != 0)
        {
            // Use ListResponseName (from [ListIgnore]) if available, otherwise ResponseName
            var listResponseType = info.ListResponseName ?? info.ResponseName;
            var fqListResponse = info.HasResponseDto && listResponseType is not null
                ? (info.Namespace is not null ? $"{info.Namespace}.{listResponseType}" : listResponseType)
                : null;

            if (info.HasQueryDto && info.QueryName is not null)
            {
                var fqQuery = info.Namespace is not null ? $"{info.Namespace}.{info.QueryName}" : info.QueryName;
                sb.AppendLine($"        group.MapGet(\"\", ([Microsoft.AspNetCore.Http.AsParameters] {fqQuery} query,");
                sb.AppendLine($"            {storeType} store, int page = 1, int pageSize = 20, CancellationToken ct = default) =>");
                sb.AppendLine("        {");
                sb.AppendLine("            var q = query.Apply(store.Query());");
                if (fqListResponse is not null)
                {
                    sb.AppendLine($"            var projected = {fqListResponse}.ProjectFrom(q);");
                    sb.AppendLine($"            return PaginatedResponse<{fqListResponse}>.CreateAsync(projected, page, pageSize, ct);");
                }
                else
                {
                    sb.AppendLine($"            return PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct);");
                }
                sb.AppendLine($"        }}).WithName(\"Get{entity}List\"){(info.GetListPolicy is not null ? $".RequireAuthorization(\"{info.GetListPolicy}\")" : "")};");
            }
            else
            {
                sb.AppendLine($"        group.MapGet(\"\", ({storeType} store, int page = 1, int pageSize = 20, CancellationToken ct = default) =>");
                sb.AppendLine("        {");
                sb.AppendLine("            var q = store.Query();");
                if (fqListResponse is not null)
                {
                    sb.AppendLine($"            var projected = {fqListResponse}.ProjectFrom(q);");
                    sb.AppendLine($"            return PaginatedResponse<{fqListResponse}>.CreateAsync(projected, page, pageSize, ct);");
                }
                else
                {
                    sb.AppendLine($"            return PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct);");
                }
                sb.AppendLine($"        }}).WithName(\"Get{entity}List\"){(info.GetListPolicy is not null ? $".RequireAuthorization(\"{info.GetListPolicy}\")" : "")};");
            }
            sb.AppendLine();
        }

        // POST
        if ((info.Operations & OpCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine($"        group.MapPost(\"\", async ({fqCreate} request, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var validation = request.{validateMethod}();");
            sb.AppendLine("            if (!validation.IsValid) return Results.ValidationProblem(validation.ToDictionary());");
            sb.AppendLine("            var entity = request.ToEntity();");
            sb.AppendLine("            await store.CreateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.CreatedAtRoute(\"Get{entity}\", new {{ id = entity.{info.KeyPropertyName} }}, {fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine($"            return Results.CreatedAtRoute(\"Get{entity}\", new {{ id = entity.{info.KeyPropertyName} }}, entity);");
            }
            var postChain = "        })";
            if (info.CreatePolicy is not null)
                postChain += $".RequireAuthorization(\"{info.CreatePolicy}\")";
            sb.AppendLine(postChain + ";");
            sb.AppendLine();
        }

        // PATCH
        if ((info.Operations & OpUpdate) != 0 && info.UpdateRequestName is not null)
        {
            var fqUpdate = info.Namespace is not null ? $"{info.Namespace}.{info.UpdateRequestName}" : info.UpdateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForUpdate" : "Validate";
            sb.AppendLine($"        group.MapPatch(\"{{id}}\", async ({keyType} id, {fqUpdate} request, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            sb.AppendLine($"            var validation = request.{validateMethod}();");
            sb.AppendLine("            if (!validation.IsValid) return Results.ValidationProblem(validation.ToDictionary());");
            sb.AppendLine("            request.ApplyTo(entity);");
            sb.AppendLine("            await store.UpdateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entity);");
            }
            var patchChain = "        })";
            if (info.UpdatePolicy is not null)
                patchChain += $".RequireAuthorization(\"{info.UpdatePolicy}\")";
            sb.AppendLine(patchChain + ";");
            sb.AppendLine();
        }

        // DELETE
        if ((info.Operations & OpDelete) != 0)
        {
            sb.AppendLine($"        group.MapDelete(\"{{id}}\", async ({keyType} id, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("            if (entity is null) return Results.Problem(statusCode: 404, title: \"Not Found\");");
            sb.AppendLine("            await store.DeleteAsync(entity, ct);");
            sb.AppendLine("            return Results.NoContent();");
            var deleteChain = "        })";
            if (info.DeletePolicy is not null)
                deleteChain += $".RequireAuthorization(\"{info.DeletePolicy}\")";
            sb.AppendLine(deleteChain + ";");
            sb.AppendLine();
        }

        // BULK CREATE
        if ((info.Operations & OpBulkCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine($"        group.MapPost(\"bulk\", async (List<{fqCreate}> requests, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var allErrors = new DtoValidationResult();");
            sb.AppendLine("            for (var i = 0; i < requests.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var validation = requests[i].{validateMethod}();");
            sb.AppendLine("                allErrors.Merge(validation, $\"[{i}]\");");
            sb.AppendLine("            }");
            sb.AppendLine("            if (!allErrors.IsValid) return Results.ValidationProblem(allErrors.ToDictionary());");
            sb.AppendLine($"            var entities = new List<{fqEntity}>();");
            sb.AppendLine("            foreach (var request in requests)");
            sb.AppendLine("            {");
            sb.AppendLine("                var entity = request.ToEntity();");
            sb.AppendLine("                await store.CreateAsync(entity, ct);");
            sb.AppendLine("                entities.Add(entity);");
            sb.AppendLine("            }");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"            return Results.Ok(entities.Select(e => {fqResponse}.FromEntity(e)).ToList());");
            }
            else
            {
                sb.AppendLine("            return Results.Ok(entities);");
            }
            var bulkCreateChain = "        })";
            if (info.CreatePolicy is not null)
                bulkCreateChain += $".RequireAuthorization(\"{info.CreatePolicy}\")";
            sb.AppendLine(bulkCreateChain + ";");
            sb.AppendLine();
        }

        // BULK DELETE
        if ((info.Operations & OpBulkDelete) != 0)
        {
            sb.AppendLine($"        group.MapPost(\"bulk-delete\", async (List<{keyType}> ids, {storeType} store, CancellationToken ct) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var deleted = 0;");
            sb.AppendLine("            foreach (var id in ids)");
            sb.AppendLine("            {");
            sb.AppendLine("                var entity = await store.GetByIdAsync(id, ct);");
            sb.AppendLine("                if (entity is not null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    await store.DeleteAsync(entity, ct);");
            sb.AppendLine("                    deleted++;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return Results.Ok(new { deleted });");
            var bulkDeleteChain = "        })";
            if (info.DeletePolicy is not null)
                bulkDeleteChain += $".RequireAuthorization(\"{info.DeletePolicy}\")";
            sb.AppendLine(bulkDeleteChain + ";");
            sb.AppendLine();
        }

        sb.AppendLine("        return group;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateControllerSource(CrudApiInfo info)
    {
        var sb = new StringBuilder();
        var entity = info.ClassName;
        var fqEntity = info.Namespace is not null ? $"{info.Namespace}.{entity}" : entity;
        var keyType = info.KeyTypeName;
        var storeType = $"ZibStack.NET.Dto.ICrudStore<{fqEntity}, {keyType}>";
        var controllerName = $"{entity}CrudController";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [CrudApi] on {entity}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using ZibStack.NET.Dto;");

        if (info.Namespace is not null)
        {
            sb.AppendLine($"using {info.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace ?? "ZibStack.NET.Dto.Generated"};");
        sb.AppendLine();

        if (info.AuthorizePolicy is not null)
            sb.AppendLine($"[Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.AuthorizePolicy}\")]");

        sb.AppendLine("[ApiController]");
        sb.AppendLine($"[Route(\"{info.Route}\")]");
        sb.AppendLine($"public partial class {controllerName} : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {storeType} _store;");
        sb.AppendLine();
        sb.AppendLine($"    public {controllerName}({storeType} store) => _store = store;");

        // GET {id}
        if ((info.Operations & OpGetById) != 0)
        {
            sb.AppendLine();
            if (info.GetByIdPolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.GetByIdPolicy}\")]");
            sb.AppendLine("    [HttpGet(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> GetById({keyType} id, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("        return Ok(entity);");
            }
            sb.AppendLine("    }");
        }

        // GET list
        if ((info.Operations & OpGetList) != 0)
        {
            sb.AppendLine();
            if (info.GetListPolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.GetListPolicy}\")]");
            if (info.HasQueryDto && info.QueryName is not null)
            {
                var fqQuery = info.Namespace is not null ? $"{info.Namespace}.{info.QueryName}" : info.QueryName;
                sb.AppendLine("    [HttpGet]");
                sb.AppendLine($"    public async Task<IActionResult> GetList([FromQuery] {fqQuery} query, int page = 1, int pageSize = 20, CancellationToken ct = default)");
                sb.AppendLine("    {");
                sb.AppendLine("        var q = query.Apply(_store.Query());");
            }
            else
            {
                sb.AppendLine("    [HttpGet]");
                sb.AppendLine("    public async Task<IActionResult> GetList(int page = 1, int pageSize = 20, CancellationToken ct = default)");
                sb.AppendLine("    {");
                sb.AppendLine("        var q = _store.Query();");
            }

            var ctrlListType = info.ListResponseName ?? info.ResponseName;
            var fqCtrlList = info.HasResponseDto && ctrlListType is not null
                ? (info.Namespace is not null ? $"{info.Namespace}.{ctrlListType}" : ctrlListType)
                : null;
            if (fqCtrlList is not null)
            {
                sb.AppendLine($"        var projected = {fqCtrlList}.ProjectFrom(q);");
                sb.AppendLine($"        var result = await PaginatedResponse<{fqCtrlList}>.CreateAsync(projected, page, pageSize, ct);");
            }
            else
            {
                sb.AppendLine($"        var result = await PaginatedResponse<{fqEntity}>.CreateAsync(q, page, pageSize, ct);");
            }
            sb.AppendLine("        return Ok(result);");
            sb.AppendLine("    }");
        }

        // POST
        if ((info.Operations & OpCreate) != 0 && info.CreateRequestName is not null)
        {
            var fqCreate = info.Namespace is not null ? $"{info.Namespace}.{info.CreateRequestName}" : info.CreateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForCreate" : "Validate";
            sb.AppendLine();
            if (info.CreatePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.CreatePolicy}\")]");
            sb.AppendLine("    [HttpPost]");
            sb.AppendLine($"    public async Task<IActionResult> Create([FromBody] {fqCreate} request, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var validation = request.{validateMethod}();");
            sb.AppendLine("        if (!validation.IsValid) { foreach (var kv in validation.Errors) foreach (var msg in kv.Value) ModelState.AddModelError(kv.Key, msg); return ValidationProblem(); }");
            sb.AppendLine("        var entity = request.ToEntity();");
            sb.AppendLine("        await _store.CreateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return CreatedAtAction(nameof(GetById), new {{ id = entity.{info.KeyPropertyName} }}, {fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine($"        return CreatedAtAction(nameof(GetById), new {{ id = entity.{info.KeyPropertyName} }}, entity);");
            }
            sb.AppendLine("    }");
        }

        // PATCH
        if ((info.Operations & OpUpdate) != 0 && info.UpdateRequestName is not null)
        {
            var fqUpdate = info.Namespace is not null ? $"{info.Namespace}.{info.UpdateRequestName}" : info.UpdateRequestName;
            var validateMethod = info.IsCombinedDto ? "ValidateForUpdate" : "Validate";
            sb.AppendLine();
            if (info.UpdatePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.UpdatePolicy}\")]");
            sb.AppendLine("    [HttpPatch(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> Update({keyType} id, [FromBody] {fqUpdate} request, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            sb.AppendLine($"        var validation = request.{validateMethod}();");
            sb.AppendLine("        if (!validation.IsValid) { foreach (var kv in validation.Errors) foreach (var msg in kv.Value) ModelState.AddModelError(kv.Key, msg); return ValidationProblem(); }");
            sb.AppendLine("        request.ApplyTo(entity);");
            sb.AppendLine("        await _store.UpdateAsync(entity, ct);");
            if (info.HasResponseDto && info.ResponseName is not null)
            {
                var fqResponse = info.Namespace is not null ? $"{info.Namespace}.{info.ResponseName}" : info.ResponseName;
                sb.AppendLine($"        return Ok({fqResponse}.FromEntity(entity));");
            }
            else
            {
                sb.AppendLine("        return Ok(entity);");
            }
            sb.AppendLine("    }");
        }

        // DELETE
        if ((info.Operations & OpDelete) != 0)
        {
            sb.AppendLine();
            if (info.DeletePolicy is not null)
                sb.AppendLine($"    [Microsoft.AspNetCore.Authorization.Authorize(Policy = \"{info.DeletePolicy}\")]");
            sb.AppendLine("    [HttpDelete(\"{id}\")]");
            sb.AppendLine($"    public async Task<IActionResult> Delete({keyType} id, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        var entity = await _store.GetByIdAsync(id, ct);");
            sb.AppendLine("        if (entity is null) return NotFound();");
            sb.AppendLine("        await _store.DeleteAsync(entity, ct);");
            sb.AppendLine("        return NoContent();");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
