using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.Dto;

public partial class DtoGenerator
{
    // ─── Embedded sources ──────────────────────────────────────────────

    private const string CreateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? Validator { get; set; }
    }
}
";

    private const string UpdateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class UpdateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? Validator { get; set; }
    }
}
";

    private const string CreateOrUpdateDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateOrUpdateDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        public System.Type? CreateValidator { get; set; }
        public System.Type? UpdateValidator { get; set; }
    }
}
";

    private const string CreateDtoForAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial record with PatchField properties, Validate(), and ToEntity()
    /// for an external type you don't control. The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class CreateDtoForAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public CreateDtoForAttribute(System.Type targetType) => TargetType = targetType;
        public string[]? Ignore { get; set; }
        public string[]? Required { get; set; }
    }
}
";

    private const string UpdateDtoForAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial record with PatchField properties, Validate(), and ApplyTo()
    /// for an external type you don't control. The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class UpdateDtoForAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public UpdateDtoForAttribute(System.Type targetType) => TargetType = targetType;
        public string[]? Ignore { get; set; }
        public string[]? Immutable { get; set; }
    }
}
";

    private const string PartialFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial class with PatchField properties for all public properties of the target type,
    /// plus an ApplyTo method. Similar to TypeScript's Partial&lt;T&gt;.
    /// The decorated class must be partial.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class PartialFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public PartialFromAttribute(System.Type targetType) => TargetType = targetType;
    }
}
";

    private const string IntersectFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generates a partial record that intersects properties from multiple types.
    /// Apply multiple times to combine types (like TypeScript's &amp; operator).
    /// The decorated class must be a partial record.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class IntersectFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public IntersectFromAttribute(System.Type targetType) => TargetType = targetType;
    }
}
";

    private const string DtoIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class DtoIgnoreAttribute : System.Attribute { }
}
";

    private const string DtoNameAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class DtoNameAttribute : System.Attribute
    {
        public string Name { get; }
        public DtoNameAttribute(string name) => Name = name;
    }
}
";

    private const string CreateOnlyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class CreateOnlyAttribute : System.Attribute { }
}
";

    private const string UpdateOnlyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class UpdateOnlyAttribute : System.Attribute { }
}
";

    private const string ResponseDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class ResponseDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
    }
}
";

    private const string ResponseIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Excludes a property from the generated Response DTO.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class ResponseIgnoreAttribute : System.Attribute { }
}
";

    private const string PickFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Like TypeScript Pick&lt;T, K&gt;. Generates a partial record with only the listed properties.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class PickFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public string[] Properties { get; }
        public PickFromAttribute(System.Type targetType, params string[] properties)
        {
            TargetType = targetType;
            Properties = properties;
        }
    }
}
";

    private const string OmitFromAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Like TypeScript Omit&lt;T, K&gt;. Generates a partial record with all properties except the listed ones.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class OmitFromAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public string[] Properties { get; }
        public OmitFromAttribute(System.Type targetType, params string[] properties)
        {
            TargetType = targetType;
            Properties = properties;
        }
    }
}
";

    private const string QueryDtoAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Dto
{
    /// <summary>Generates a query/filter DTO with all properties nullable + ApplyFilter(IQueryable).</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class QueryDtoAttribute : System.Attribute
    {
        public string? Name { get; set; }
        /// <summary>When true, adds SortBy and SortDirection properties + ApplySort(IQueryable) method.</summary>
        public bool Sortable { get; set; }
        /// <summary>Default sort property name (used when SortBy is null).</summary>
        public string? DefaultSort { get; set; }
        /// <summary>Default sort direction when SortDirection is null. Defaults to Asc.</summary>
        public ZibStack.NET.Dto.SortDirection DefaultSortDirection { get; set; }
    }
}
";

    private const string RenamePropertyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Renames a property from the source type in the generated DTO.
    /// Use with [CreateDtoFor] / [UpdateDtoFor]. ToEntity() and ApplyTo() map back to the original name.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class RenamePropertyAttribute : System.Attribute
    {
        public string OriginalName { get; }
        public string NewName { get; }
        public RenamePropertyAttribute(string originalName, string newName)
        {
            OriginalName = originalName;
            NewName = newName;
        }
    }
}
";

    private const string ImmutableAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Property is visible in Update DTO but skipped in ApplyTo().
    /// Useful for properties that can be set at creation but not changed later.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class ImmutableAttribute : System.Attribute { }
}
";

    private const string FlattenAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Flattens a nested object's properties into the parent DTO.
    /// Address.Street becomes AddressStreet, Address.City becomes AddressCity, etc.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class FlattenAttribute : System.Attribute { }
}
";

    private const string PaginatedResponseSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Generic paginated response wrapper. Use with any ResponseDto or entity type.
    /// </summary>
    public record PaginatedResponse<T>
    {
        public System.Collections.Generic.IReadOnlyList<T> Items { get; init; } = System.Array.Empty<T>();
        public int TotalCount { get; init; }
        public int Page { get; init; }
        public int PageSize { get; init; }
        public int TotalPages => PageSize > 0 ? (int)System.Math.Ceiling((double)TotalCount / PageSize) : 0;
        public bool HasNextPage => Page < TotalPages;
        public bool HasPreviousPage => Page > 1;

        public static PaginatedResponse<T> Create(
            System.Collections.Generic.IReadOnlyList<T> items,
            int totalCount,
            int page,
            int pageSize)
        {
            return new PaginatedResponse<T>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize,
            };
        }

        public static async System.Threading.Tasks.Task<PaginatedResponse<T>> CreateAsync(
            System.Linq.IQueryable<T> query,
            int page,
            int pageSize,
            System.Threading.CancellationToken cancellationToken = default)
        {
            var totalCount = query.Count();
            var items = query
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            return Create(items, totalCount, page, pageSize);
        }

        /// <summary>Maps items to a different type while preserving pagination metadata.</summary>
        public PaginatedResponse<TOut> Map<TOut>(System.Func<T, TOut> selector)
        {
            var mapped = new System.Collections.Generic.List<TOut>(Items.Count);
            foreach (var item in Items)
                mapped.Add(selector(item));

            return new PaginatedResponse<TOut>
            {
                Items = mapped,
                TotalCount = TotalCount,
                Page = Page,
                PageSize = PageSize,
            };
        }
    }
}
";

    private const string SortDirectionSource = @"// <auto-generated />
namespace ZibStack.NET.Dto
{
    /// <summary>Sort direction for sortable query DTOs.</summary>
    public enum SortDirection
    {
        Asc,
        Desc
    }
}
";

    private const string DtoValidatorInterfaceSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Implement this interface to provide custom validation for a generated request class.
    /// Set via [Dto(CreateValidator = typeof(...))] or [Dto(UpdateValidator = typeof(...))].
    /// </summary>
    public interface IDtoValidator<T>
    {
        System.Collections.Generic.List<string> Validate(T instance);
    }

    public interface ICanCreate<T>
    {
        T ToEntity();
    }

    public interface ICanApply<T>
    {
        void ApplyTo(T target);
    }

    public interface ICanValidate
    {
        System.Collections.Generic.List<string> Validate();
    }
}
";

    private const string FluentDtoValidatorSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Base class that bridges FluentValidation with ZibStack.NET.Dto validation.
    /// Extend this instead of AbstractValidator to use with [Dto(CreateValidator/UpdateValidator)].
    /// </summary>
    public abstract class FluentDtoValidator<T> : FluentValidation.AbstractValidator<T>, IDtoValidator<T>
    {
        System.Collections.Generic.List<string> IDtoValidator<T>.Validate(T instance)
        {
            var result = base.Validate(instance);
            var errors = new System.Collections.Generic.List<string>();
            foreach (var failure in result.Errors)
                errors.Add(failure.ErrorMessage);
            return errors;
        }
    }
}
";

    private const string PatchFieldSchemaFilterSource = @"// <auto-generated />
#nullable enable

namespace ZibStack.NET.Dto
{
    /// <summary>
    /// Swagger/Swashbuckle schema filter that unwraps PatchField&lt;T&gt; to its inner type.
    /// Register via: options.SchemaFilter&lt;PatchFieldSchemaFilter&gt;();
    /// </summary>
    public sealed class PatchFieldSchemaFilter : Swashbuckle.AspNetCore.SwaggerGen.ISchemaFilter
    {
        public void Apply(Microsoft.OpenApi.Models.OpenApiSchema schema, Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext context)
        {
            var type = context.Type;
            if (!type.IsGenericType || type.GetGenericTypeDefinition() != typeof(PatchField<>))
                return;

            var innerType = type.GetGenericArguments()[0];
            var innerSchema = context.SchemaGenerator.GenerateSchema(innerType, context.SchemaRepository);

            schema.Type = innerSchema.Type;
            schema.Format = innerSchema.Format;
            schema.Reference = innerSchema.Reference;
            schema.Items = innerSchema.Items;
            schema.Properties = innerSchema.Properties;
            schema.Nullable = innerSchema.Nullable || (innerType.IsClass && !innerType.IsValueType);
            schema.Enum = innerSchema.Enum;
        }
    }
}
";
}
