using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.Dto;

public partial class DtoGenerator
{
    // ─── Code generation ───────────────────────────────────────────────

    private static string GenerateSource(DtoClassInfo classInfo, bool hasFluentValidation)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [{classInfo.Kind}Dto] on {classInfo.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (classInfo.Namespace is not null)
        {
            sb.AppendLine($"namespace {classInfo.Namespace};");
            sb.AppendLine();
        }

        switch (classInfo.Kind)
        {
            case DtoKind.Create:
                GenerateCreateRequestClass(sb, classInfo);
                if (hasFluentValidation)
                {
                    sb.AppendLine();
                    GenerateFluentBaseValidator(sb, classInfo, isCreate: true, combined: false);
                }
                break;

            case DtoKind.Update:
                GenerateUpdateRequestClass(sb, classInfo);
                if (hasFluentValidation)
                {
                    sb.AppendLine();
                    GenerateFluentBaseValidator(sb, classInfo, isCreate: false, combined: false);
                }
                break;

            case DtoKind.Combined:
                GenerateCombinedRequestClass(sb, classInfo);
                if (hasFluentValidation)
                {
                    sb.AppendLine();
                    GenerateFluentBaseValidator(sb, classInfo, isCreate: true, combined: true);
                    sb.AppendLine();
                    GenerateFluentBaseValidator(sb, classInfo, isCreate: false, combined: true);
                }
                break;
        }

        return sb.ToString();
    }

    private static void GenerateCreateRequestClass(StringBuilder sb, DtoClassInfo classInfo)
    {
        var props = classInfo.Properties.Where(p => !p.IsUpdateOnly).ToList();

        sb.AppendLine($"public record {classInfo.RequestName} : ZibStack.NET.Dto.ICanCreate<{classInfo.ClassName}>, ZibStack.NET.Dto.ICanValidate");
        sb.AppendLine("{");

        foreach (var prop in props)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{GetPropTypeName(prop, isCreate: true)}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        // Validate()
        sb.AppendLine("    public List<string> Validate()");
        sb.AppendLine("    {");

        if (classInfo.CreateValidatorTypeName is not null)
        {
            sb.AppendLine($"        return new {classInfo.CreateValidatorTypeName}().Validate(this);");
        }
        else
        {
            sb.AppendLine("        var errors = new List<string>();");
            foreach (var prop in props)
            {
                if (prop.IsRequired)
                {
                    sb.AppendLine($"        if (!{prop.PropertyName}.HasValue)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' is required.\");");

                    if (NeedsNullCheck(prop))
                    {
                        sb.AppendLine($"        else if ({prop.PropertyName}.Value is null)");
                        sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                    }
                }
                else if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                }
            }
            sb.AppendLine("        return errors;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // ToEntity()
        GenerateToEntityMethod(sb, props, classInfo.ClassName);
        sb.AppendLine();

        sb.AppendLine("}");
    }

    private static void GenerateUpdateRequestClass(StringBuilder sb, DtoClassInfo classInfo)
    {
        var props = classInfo.Properties.Where(p => !p.IsCreateOnly).ToList();

        sb.AppendLine($"public record {classInfo.RequestName} : ZibStack.NET.Dto.ICanApply<{classInfo.ClassName}>, ZibStack.NET.Dto.ICanValidate");
        sb.AppendLine("{");

        foreach (var prop in props)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{GetPropTypeName(prop, isCreate: false)}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        // Validate()
        sb.AppendLine("    public List<string> Validate()");
        sb.AppendLine("    {");

        if (classInfo.UpdateValidatorTypeName is not null)
        {
            sb.AppendLine($"        return new {classInfo.UpdateValidatorTypeName}().Validate(this);");
        }
        else
        {
            sb.AppendLine("        var errors = new List<string>();");
            foreach (var prop in props)
            {
                if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                }
            }
            sb.AppendLine("        return errors;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // ApplyTo()
        GenerateApplyToMethod(sb, props, classInfo.ClassName);
        sb.AppendLine();

        // Diff()
        GenerateDiffMethod(sb, props, classInfo.ClassName);
        sb.AppendLine();

        // ApplyWithChanges()
        GenerateApplyWithChangesMethod(sb, props, classInfo.ClassName);

        sb.AppendLine("}");
    }

    private static void GenerateCombinedRequestClass(StringBuilder sb, DtoClassInfo classInfo)
    {
        var allProps = classInfo.Properties;

        sb.AppendLine($"public record {classInfo.RequestName} : ZibStack.NET.Dto.ICanCreate<{classInfo.ClassName}>, ZibStack.NET.Dto.ICanApply<{classInfo.ClassName}>");
        sb.AppendLine("{");

        foreach (var prop in allProps)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            // Combined uses update nested names (supports partial update)
            sb.AppendLine($"    public PatchField<{GetPropTypeName(prop, isCreate: false)}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        // ValidateForCreate()
        var createProps = allProps.Where(p => !p.IsUpdateOnly).ToList();
        sb.AppendLine("    public List<string> ValidateForCreate()");
        sb.AppendLine("    {");

        if (classInfo.CreateValidatorTypeName is not null)
        {
            sb.AppendLine($"        return new {classInfo.CreateValidatorTypeName}().Validate(this);");
        }
        else
        {
            sb.AppendLine("        var errors = new List<string>();");
            foreach (var prop in createProps)
            {
                if (prop.IsRequired)
                {
                    sb.AppendLine($"        if (!{prop.PropertyName}.HasValue)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' is required.\");");
                    if (NeedsNullCheck(prop))
                    {
                        sb.AppendLine($"        else if ({prop.PropertyName}.Value is null)");
                        sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                    }
                }
                else if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                }
            }
            sb.AppendLine("        return errors;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // ValidateForUpdate()
        var updateProps = allProps.Where(p => !p.IsCreateOnly).ToList();
        sb.AppendLine("    public List<string> ValidateForUpdate()");
        sb.AppendLine("    {");

        if (classInfo.UpdateValidatorTypeName is not null)
        {
            sb.AppendLine($"        return new {classInfo.UpdateValidatorTypeName}().Validate(this);");
        }
        else
        {
            sb.AppendLine("        var errors = new List<string>();");
            foreach (var prop in updateProps)
            {
                if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                }
            }
            sb.AppendLine("        return errors;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // ToEntity()
        GenerateToEntityMethod(sb, createProps, classInfo.ClassName);
        sb.AppendLine();

        // ApplyTo()
        GenerateApplyToMethod(sb, updateProps, classInfo.ClassName);
        sb.AppendLine();

        // Diff()
        GenerateDiffMethod(sb, updateProps, classInfo.ClassName);
        sb.AppendLine();

        // ApplyWithChanges()
        GenerateApplyWithChangesMethod(sb, updateProps, classInfo.ClassName);

        sb.AppendLine("}");
    }

    /// <summary>Non-nullable reference types need null validation.</summary>
    private static void EmitAutoNestedDto(StringBuilder sb, DtoClassInfo nested)
    {
        var nestedSource = GenerateSource(nested, false);
        var lines = nestedSource.Split('\n');
        var skip = true;
        foreach (var line in lines)
        {
            if (skip && (line.TrimStart().StartsWith("//") || line.TrimStart().StartsWith("#") ||
                line.TrimStart().StartsWith("using ") || line.TrimStart().StartsWith("namespace ") ||
                string.IsNullOrWhiteSpace(line)))
                continue;
            skip = false;
            sb.AppendLine(line.TrimEnd());
        }
    }

    private static void EmitValidationAttributes(StringBuilder sb, List<string> attrs)
    {
        foreach (var attr in attrs)
            sb.AppendLine($"    {attr}");
    }

    private static string GetPropTypeName(DtoPropertyInfo prop, bool isCreate)
    {
        var nestedName = isCreate ? prop.NestedCreateDtoName : prop.NestedUpdateDtoName;
        if (nestedName is not null)
        {
            return prop.IsNullable ? $"{nestedName}?" : nestedName;
        }
        return prop.DisplayTypeName;
    }

    private static bool IsValueTypeName(string typeName)
    {
        return typeName is "int" or "long" or "short" or "byte" or "float" or "double" or "decimal"
            or "bool" or "char" or "uint" or "ulong" or "ushort" or "sbyte"
            or "System.Int32" or "System.Int64" or "System.Int16" or "System.Byte"
            or "System.Single" or "System.Double" or "System.Decimal" or "System.Boolean"
            or "System.Char" or "System.DateTime" or "System.DateTimeOffset"
            or "System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "System.Guid"
            || typeName.EndsWith("?");
    }

    private static bool NeedsNullCheck(DtoPropertyInfo prop)
        => !prop.IsValueType && !prop.IsNullable;

    /// <summary>Non-nullable reference types need ! when assigning from PatchField.Value.</summary>
    private static bool NeedsNullForgiving(DtoPropertyInfo prop)
        => !prop.IsValueType && !prop.IsNullable;

    private static void GenerateToEntityMethod(StringBuilder sb, List<DtoPropertyInfo> props, string typeName)
    {
        var normalProps = props.Where(p => !p.IsFlattened).ToList();
        var flatProps = props.Where(p => p.IsFlattened).ToList();

        sb.AppendLine($"    public {typeName} ToEntity()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var entity = new {typeName}");
        sb.AppendLine("        {");
        foreach (var prop in normalProps)
        {
            if (prop.NestedCreateDtoName is null)
            {
                var defaultVal = prop.IsValueType ? "default" : (prop.IsNullable ? "default" : "default!");
                sb.AppendLine($"            {prop.SourcePropertyName} = {prop.PropertyName}.HasValue ? {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")} : {defaultVal},");
                continue;
            }

            if (prop.IsNullable)
                sb.AppendLine($"            {prop.SourcePropertyName} = {prop.PropertyName}.HasValue && {prop.PropertyName}.Value is not null ? {prop.PropertyName}.Value.ToEntity() : default,");
            else
                sb.AppendLine($"            {prop.SourcePropertyName} = {prop.PropertyName}.HasValue ? {prop.PropertyName}.Value!.ToEntity() : default!,");
        }
        sb.AppendLine("        };");

        // Apply flattened properties
        if (flatProps.Count > 0)
        {
            // Group by top-level property (first segment of FlattenEntityPath)
            var groups = flatProps.GroupBy(p => p.FlattenEntityPath!.Split('.')[0]);
            foreach (var g in groups)
            {
                sb.AppendLine($"        if (entity.{g.Key} is not null)");
                sb.AppendLine("        {");
                foreach (var fp in g)
                {
                    sb.AppendLine($"            if ({fp.PropertyName}.HasValue) entity.{fp.FlattenEntityPath} = {fp.PropertyName}.Value{(NeedsNullForgiving(fp) ? "!" : "")};");
                }
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine("        return entity;");
        sb.AppendLine("    }");
    }

    private static void GenerateApplyToMethod(StringBuilder sb, List<DtoPropertyInfo> props, string typeName)
    {
        sb.AppendLine($"    public void ApplyTo({typeName} target)");
        sb.AppendLine("    {");
        foreach (var prop in props)
        {
            if (prop.IsImmutable) continue;

            if (prop.IsFlattened)
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue && target.{prop.FlattenEntityPath!.Split('.')[0]} is not null) target.{prop.FlattenEntityPath} = {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")};");
                continue;
            }

            if (prop.NestedUpdateDtoName is null)
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue) target.{prop.SourcePropertyName} = {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")};");
                continue;
            }

            sb.AppendLine($"        if ({prop.PropertyName}.HasValue)");
            sb.AppendLine("        {");
            if (prop.IsNullable)
            {
                sb.AppendLine($"            if ({prop.PropertyName}.Value is null)");
                sb.AppendLine($"                target.{prop.SourcePropertyName} = null;");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                if (prop.NestedCreateDtoName is not null)
                {
                    // Has ToEntity — can create from scratch
                    sb.AppendLine($"                if (target.{prop.SourcePropertyName} is null) target.{prop.SourcePropertyName} = {prop.PropertyName}.Value.ToEntity();");
                }
                else
                {
                    sb.AppendLine($"                if (target.{prop.SourcePropertyName} is not null)");
                }
                sb.AppendLine($"                {(prop.NestedCreateDtoName is not null ? "else " : "    ")}{prop.PropertyName}.Value.ApplyTo(target.{prop.SourcePropertyName});");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine($"            if (target.{prop.SourcePropertyName} is not null) {prop.PropertyName}.Value!.ApplyTo(target.{prop.SourcePropertyName});");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");
    }

    private static void GenerateDiffMethod(StringBuilder sb, List<DtoPropertyInfo> props, string typeName)
    {
        sb.AppendLine($"    public List<string> Diff({typeName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        var changes = new List<string>();");
        foreach (var prop in props)
        {
            // Skip nested DTO props — can't compare different types
            if (prop.NestedUpdateDtoName is not null || prop.NestedCreateDtoName is not null)
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue)");
                sb.AppendLine($"            changes.Add(\"{prop.JsonName}\");");
                continue;
            }
            sb.AppendLine($"        if ({prop.PropertyName}.HasValue && !System.Collections.Generic.EqualityComparer<{prop.DisplayTypeName}>.Default.Equals({prop.PropertyName}.Value, entity.{prop.SourcePropertyName}))");
            sb.AppendLine($"            changes.Add(\"{prop.JsonName}\");");
        }
        sb.AppendLine("        return changes;");
        sb.AppendLine("    }");
    }

    private static string GenerateResponseDtoSource(ResponseDtoInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [ResponseDto] on {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public record {info.ResponseName}");
        sb.AppendLine("{");

        // Properties — plain, no PatchField
        foreach (var prop in info.Properties)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            var needsDefault = !prop.DisplayTypeName.EndsWith("?") && !IsValueTypeName(prop.DisplayTypeName);
            sb.AppendLine($"    public {prop.DisplayTypeName} {prop.PropertyName} {{ get; init; }}{(needsDefault ? " = default!;" : "")}");
        }

        sb.AppendLine();

        // FromEntity
        sb.AppendLine($"    public static {info.ResponseName} FromEntity({info.ClassName} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {info.ResponseName}");
        sb.AppendLine("        {");
        foreach (var prop in info.Properties)
        {
            if (prop.IsFlattened)
            {
                sb.AppendLine($"            {prop.PropertyName} = {prop.FlattenSource},");
                continue;
            }

            if (!prop.IsNestedResponse)
            {
                sb.AppendLine($"            {prop.PropertyName} = entity.{prop.PropertyName},");
                continue;
            }

            if (prop.IsNullable)
                sb.AppendLine($"            {prop.PropertyName} = entity.{prop.PropertyName} is not null ? {prop.NestedResponseName}.FromEntity(entity.{prop.PropertyName}) : null,");
            else
                sb.AppendLine($"            {prop.PropertyName} = {prop.NestedResponseName}.FromEntity(entity.{prop.PropertyName}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ProjectFrom (IQueryable)
        sb.AppendLine($"    public static IQueryable<{info.ResponseName}> ProjectFrom(IQueryable<{info.ClassName}> query)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return query.Select(x => new {info.ResponseName}");
        sb.AppendLine("        {");
        foreach (var prop in info.Properties)
        {
            if (prop.IsFlattened)
            {
                sb.AppendLine($"            {prop.PropertyName} = {prop.FlattenProjection},");
                continue;
            }

            if (!prop.IsNestedResponse)
                sb.AppendLine($"            {prop.PropertyName} = x.{prop.PropertyName},");
        }
        sb.AppendLine("        });");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateQueryDtoSource(QueryDtoInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [QueryDto] on {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        if (info.Sortable)
            sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public record {info.QueryName}");
        sb.AppendLine("{");

        // All properties nullable
        foreach (var prop in info.Properties)
        {
            sb.AppendLine($"    public {prop.NullableTypeName} {prop.PropertyName} {{ get; init; }}");
        }

        // Sorting properties
        if (info.Sortable)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Property name to sort by. Case-insensitive.</summary>");
            sb.AppendLine("    public string? SortBy { get; init; }");
            sb.AppendLine("    /// <summary>Sort direction. Defaults to Asc.</summary>");
            sb.AppendLine("    public SortDirection? SortDirection { get; init; }");
        }

        sb.AppendLine();

        // ApplyFilter
        sb.AppendLine($"    public IQueryable<{info.ClassName}> ApplyFilter(IQueryable<{info.ClassName}> query)");
        sb.AppendLine("    {");
        foreach (var prop in info.Properties)
        {
            sb.AppendLine($"        if ({prop.PropertyName} is not null)");
            if (prop.IsValueType)
                sb.AppendLine($"            query = query.Where(x => x.{prop.PropertyName} == {prop.PropertyName}.Value);");
            else
                sb.AppendLine($"            query = query.Where(x => x.{prop.PropertyName} == {prop.PropertyName});");
        }
        sb.AppendLine("        return query;");
        sb.AppendLine("    }");

        // ApplySort
        if (info.Sortable)
        {
            sb.AppendLine();
            sb.AppendLine($"    public IQueryable<{info.ClassName}> ApplySort(IQueryable<{info.ClassName}> query)");
            sb.AppendLine("    {");

            var defaultSortStr = info.DefaultSort is not null ? $"\"{info.DefaultSort}\"" : "null";
            var defaultDirStr = info.DefaultSortDirection == 1 ? "ZibStack.NET.Dto.SortDirection.Desc" : "ZibStack.NET.Dto.SortDirection.Asc";
            sb.AppendLine($"        var sortBy = SortBy ?? {defaultSortStr};");
            sb.AppendLine($"        var direction = SortDirection ?? {defaultDirStr};");
            sb.AppendLine();
            sb.AppendLine("        if (sortBy is null) return query;");
            sb.AppendLine();
            sb.AppendLine("        return (sortBy.ToLowerInvariant(), direction) switch");
            sb.AppendLine("        {");
            foreach (var prop in info.Properties)
            {
                var lower = prop.PropertyName.ToLowerInvariant();
                sb.AppendLine($"            (\"{lower}\", ZibStack.NET.Dto.SortDirection.Asc) => query.OrderBy(x => x.{prop.PropertyName}),");
                sb.AppendLine($"            (\"{lower}\", ZibStack.NET.Dto.SortDirection.Desc) => query.OrderByDescending(x => x.{prop.PropertyName}),");
            }
            sb.AppendLine("            _ => query,");
            sb.AppendLine("        };");
            sb.AppendLine("    }");

            // Convenience: ApplyFilterAndSort
            sb.AppendLine();
            sb.AppendLine($"    public IQueryable<{info.ClassName}> Apply(IQueryable<{info.ClassName}> query)");
            sb.AppendLine("    {");
            sb.AppendLine("        query = ApplyFilter(query);");
            sb.AppendLine("        query = ApplySort(query);");
            sb.AppendLine("        return query;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateApplyWithChangesMethod(StringBuilder sb, List<DtoPropertyInfo> props, string typeName)
    {
        sb.AppendLine($"    public (System.Collections.Generic.List<string> ChangedFields, {typeName} Entity) ApplyWithChanges({typeName} target)");
        sb.AppendLine("    {");
        sb.AppendLine("        var changed = new System.Collections.Generic.List<string>();");
        foreach (var prop in props)
        {
            if (prop.IsImmutable) continue;

            if (prop.NestedUpdateDtoName is null)
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!System.Collections.Generic.EqualityComparer<{prop.DisplayTypeName}>.Default.Equals({prop.PropertyName}.Value, target.{prop.SourcePropertyName}))");
                sb.AppendLine($"                changed.Add(\"{prop.JsonName}\");");
                sb.AppendLine($"            target.{prop.SourcePropertyName} = {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")};");
                sb.AppendLine("        }");
                continue;
            }

            // Nested — just track that it was sent, delegate to ApplyTo
            sb.AppendLine($"        if ({prop.PropertyName}.HasValue)");
            sb.AppendLine("        {");
            sb.AppendLine($"            changed.Add(\"{prop.JsonName}\");");
            if (prop.IsNullable)
            {
                sb.AppendLine($"            if ({prop.PropertyName}.Value is null)");
                sb.AppendLine($"                target.{prop.SourcePropertyName} = null;");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                if (prop.NestedCreateDtoName is not null)
                {
                    sb.AppendLine($"                if (target.{prop.SourcePropertyName} is null) target.{prop.SourcePropertyName} = {prop.PropertyName}.Value.ToEntity();");
                    sb.AppendLine($"                else {prop.PropertyName}.Value.ApplyTo(target.{prop.SourcePropertyName});");
                }
                else
                {
                    sb.AppendLine($"                if (target.{prop.SourcePropertyName} is not null) {prop.PropertyName}.Value.ApplyTo(target.{prop.SourcePropertyName});");
                }
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine($"            {prop.PropertyName}.Value!.ApplyTo(target.{prop.SourcePropertyName});");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine("        return (changed, target);");
        sb.AppendLine("    }");
    }

    private static void GenerateFluentBaseValidator(StringBuilder sb, DtoClassInfo classInfo, bool isCreate, bool combined)
    {
        var requestName = combined
            ? classInfo.RequestName
            : (isCreate ? classInfo.RequestName : classInfo.RequestName);
        var validatorSuffix = isCreate ? "CreateBaseValidator" : "UpdateBaseValidator";
        var props = isCreate
            ? classInfo.Properties.Where(p => !p.IsUpdateOnly).ToList()
            : classInfo.Properties.Where(p => !p.IsCreateOnly).ToList();

        sb.AppendLine($"public class {requestName}{validatorSuffix} : ZibStack.NET.Dto.FluentDtoValidator<{requestName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {requestName}{validatorSuffix}()");
        sb.AppendLine("    {");

        foreach (var prop in props)
        {
            var jsonName = prop.JsonName;

            if (isCreate && prop.IsRequired)
            {
                sb.AppendLine($"        RuleFor(x => x.{prop.PropertyName}).Must(f => f.HasValue).WithMessage(\"Property '{jsonName}' is required.\");");

                if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        RuleFor(x => x.{prop.PropertyName}).Must(f => !f.HasValue || f.Value is not null).WithMessage(\"Property '{jsonName}' cannot be null.\");");
                }
            }
            else if (NeedsNullCheck(prop))
            {
                sb.AppendLine($"        RuleFor(x => x.{prop.PropertyName}).Must(f => !f.HasValue || f.Value is not null).WithMessage(\"Property '{jsonName}' cannot be null.\");");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string GenerateCreateDtoForSource(DtoForInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [CreateDtoFor] on {info.ClassName} (target: {info.TargetTypeName})");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName} : ZibStack.NET.Dto.ICanCreate<{info.TargetTypeName}>, ZibStack.NET.Dto.ICanValidate");
        sb.AppendLine("{");

        foreach (var prop in info.Properties)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{prop.DisplayTypeName}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        // Validate()
        sb.AppendLine("    public List<string> Validate()");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new List<string>();");
        foreach (var prop in info.Properties)
        {
            if (prop.IsRequired)
            {
                sb.AppendLine($"        if (!{prop.PropertyName}.HasValue)");
                sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' is required.\");");
                if (NeedsNullCheck(prop))
                {
                    sb.AppendLine($"        else if ({prop.PropertyName}.Value is null)");
                    sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
                }
            }
            else if (NeedsNullCheck(prop))
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
            }
        }
        sb.AppendLine("        return errors;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ToEntity()
        GenerateToEntityMethod(sb, info.Properties, info.TargetTypeName);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateUpdateDtoForSource(DtoForInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [UpdateDtoFor] on {info.ClassName} (target: {info.TargetTypeName})");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName} : ZibStack.NET.Dto.ICanApply<{info.TargetTypeName}>, ZibStack.NET.Dto.ICanValidate");
        sb.AppendLine("{");

        foreach (var prop in info.Properties)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{prop.DisplayTypeName}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        // Validate()
        sb.AppendLine("    public List<string> Validate()");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new List<string>();");
        foreach (var prop in info.Properties)
        {
            if (NeedsNullCheck(prop))
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue && {prop.PropertyName}.Value is null)");
                sb.AppendLine($"            errors.Add(\"Property '{prop.JsonName}' cannot be null.\");");
            }
        }
        sb.AppendLine("        return errors;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ApplyTo()
        GenerateApplyToMethod(sb, info.Properties, info.TargetTypeName);
        sb.AppendLine();

        // Diff()
        GenerateDiffMethod(sb, info.Properties, info.TargetTypeName);
        sb.AppendLine();

        // ApplyWithChanges()
        GenerateApplyWithChangesMethod(sb, info.Properties, info.TargetTypeName);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GeneratePartialFromSource(PartialFromInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [PartialFrom] on {info.ClassName} (target: {info.TargetTypeName})");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName}");
        sb.AppendLine("{");

        foreach (var prop in info.Properties)
        {
            EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{prop.DisplayTypeName}> {prop.PropertyName} {{ get; init; }}");
        }

        sb.AppendLine();

        sb.AppendLine($"    public void ApplyTo({info.TargetTypeName} target)");
        sb.AppendLine("    {");
        foreach (var prop in info.Properties)
        {
            sb.AppendLine($"        if ({prop.PropertyName}.HasValue) target.{prop.PropertyName} = {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")};");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateIntersectSource(IntersectInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Dto from [IntersectFrom] on {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using ZibStack.NET.Dto;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial {info.TypeKeyword} {info.ClassName}");
        sb.AppendLine("{");

        // Properties — deduplicate by name (first wins)
        var seen = new HashSet<string>();
        foreach (var target in info.TargetTypes)
        {
            foreach (var prop in target.Properties)
            {
                if (seen.Add(prop.PropertyName))
                {
                    EmitValidationAttributes(sb, prop.ValidationAttributes);
            sb.AppendLine($"    public PatchField<{prop.DisplayTypeName}> {prop.PropertyName} {{ get; init; }}");
                }
            }
        }

        // ApplyTo per target type
        foreach (var target in info.TargetTypes)
        {
            sb.AppendLine();
            sb.AppendLine($"    public void ApplyTo({target.TypeName} target)");
            sb.AppendLine("    {");
            foreach (var prop in target.Properties)
            {
                sb.AppendLine($"        if ({prop.PropertyName}.HasValue) target.{prop.PropertyName} = {prop.PropertyName}.Value{(NeedsNullForgiving(prop) ? "!" : "")};");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GeneratePatchFieldSource(bool hasStj, bool hasNewtonsoft)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace ZibStack.NET.Dto");
        sb.AppendLine("{");

        sb.AppendLine(@"    /// <summary>
    /// Wraps a value that may or may not have been provided in a request.
    /// HasValue is true when the property was present in the JSON body.
    /// Register the appropriate converter in your serializer options.
    /// </summary>
    public readonly struct PatchField<T>
    {
        private readonly T _value;
        private readonly bool _hasValue;

        public bool HasValue => _hasValue;
        public T Value => _value;

        public PatchField(T value)
        {
            _value = value;
            _hasValue = true;
        }

        public static implicit operator PatchField<T>(T value) => new(value);
        public static implicit operator T(PatchField<T> field) => field.Value;

        public override string ToString()
            => _hasValue ? $""Value({_value})"" : ""Undefined"";
    }");

        if (hasStj)
        {
            sb.AppendLine();
            sb.AppendLine(@"    /// <summary>
    /// System.Text.Json converter for PatchField&lt;T&gt;.
    /// Register via: options.Converters.Add(new PatchFieldJsonConverterFactory());
    /// </summary>
    public sealed class PatchFieldJsonConverterFactory : System.Text.Json.Serialization.JsonConverterFactory
    {
        public override bool CanConvert(Type typeToConvert)
            => typeToConvert.IsGenericType
               && typeToConvert.GetGenericTypeDefinition() == typeof(PatchField<>);

        public override System.Text.Json.Serialization.JsonConverter CreateConverter(Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var innerType = typeToConvert.GetGenericArguments()[0];
            var converterType = typeof(PatchFieldJsonConverter<>).MakeGenericType(innerType);
            return (System.Text.Json.Serialization.JsonConverter)Activator.CreateInstance(converterType)!;
        }
    }

    public sealed class PatchFieldJsonConverter<T> : System.Text.Json.Serialization.JsonConverter<PatchField<T>>
    {
        public override PatchField<T> Read(ref System.Text.Json.Utf8JsonReader reader, Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var value = System.Text.Json.JsonSerializer.Deserialize<T>(ref reader, options)!;
            return new PatchField<T>(value);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, PatchField<T> value, System.Text.Json.JsonSerializerOptions options)
        {
            if (value.HasValue)
                System.Text.Json.JsonSerializer.Serialize(writer, value.Value, options);
            else
                writer.WriteNullValue();
        }
    }");
        }

        if (hasNewtonsoft)
        {
            sb.AppendLine();
            sb.AppendLine(@"    /// <summary>
    /// Newtonsoft.Json converter for PatchField&lt;T&gt;.
    /// Register via: settings.Converters.Add(new PatchFieldNewtonsoftConverter());
    /// </summary>
    public sealed class PatchFieldNewtonsoftConverter : Newtonsoft.Json.JsonConverter
    {
        public override bool CanConvert(Type objectType)
            => objectType.IsGenericType
               && objectType.GetGenericTypeDefinition() == typeof(PatchField<>);

        public override object? ReadJson(Newtonsoft.Json.JsonReader reader, Type objectType, object? existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var innerType = objectType.GetGenericArguments()[0];
            var value = serializer.Deserialize(reader, innerType);
            return Activator.CreateInstance(objectType, new[] { value });
        }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object? value, Newtonsoft.Json.JsonSerializer serializer)
        {
            if (value is null) { writer.WriteNull(); return; }
            var type = value.GetType();
            var hasValue = (bool)type.GetProperty(""HasValue"")!.GetValue(value)!;
            if (hasValue)
                serializer.Serialize(writer, type.GetProperty(""Value"")!.GetValue(value));
            else
                writer.WriteNull();
        }
    }");
        }

        sb.AppendLine();
        sb.AppendLine(@"    /// <summary>
    /// Maps properties from a source object to a target object by matching property names.
    /// Only properties that exist on both types are mapped.
    /// </summary>
    public static class DtoMapper
    {
        public static TTarget Map<TSource, TTarget>(TSource source) where TTarget : new()
        {
            var target = new TTarget();
            MapTo(source, target);
            return target;
        }

        public static void MapTo<TSource, TTarget>(TSource source, TTarget target)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            if (target is null) throw new System.ArgumentNullException(nameof(target));

            var sourceProps = typeof(TSource).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
            var targetProps = typeof(TTarget).GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);

            foreach (var sp in sourceProps)
            {
                if (!sp.CanRead) continue;
                foreach (var tp in targetProps)
                {
                    if (tp.Name != sp.Name || !tp.CanWrite) continue;
                    if (!tp.PropertyType.IsAssignableFrom(sp.PropertyType)) continue;
                    tp.SetValue(target, sp.GetValue(source));
                    break;
                }
            }
        }
    }");

        sb.AppendLine("}");
        return sb.ToString();
    }
}
