using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZibStack.NET.Aop.Generator;

public static class AopEmitter
{
    public static string Emit(
        InterceptedClassModel classModel,
        IReadOnlyList<CallSiteModel> callSites,
        IReadOnlyDictionary<string, IAspectEmitter> emitters)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8603");
        sb.AppendLine();

        // Collect usings from all emitters used
        var usings = new HashSet<string>
        {
            "System", "System.Diagnostics", "System.Runtime.CompilerServices"
        };
        foreach (var method in classModel.Methods)
        {
            foreach (var aspect in method.Aspects)
            {
                if (emitters.TryGetValue(aspect.AttributeFullName, out var emitter))
                {
                    foreach (var u in emitter.RequiredUsings)
                        usings.Add(u);
                }
            }
            // Runtime handlers need Aop namespace
            if (method.Aspects.Any(a => a.HandlerTypeName != null))
                usings.Add("ZibStack.NET.Aop");
        }

        foreach (var u in usings.OrderBy(x => x))
            sb.AppendLine($"using {u};");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(classModel.Namespace))
        {
            sb.AppendLine($"using {classModel.Namespace};");
            sb.AppendLine();
        }

        // InterceptsLocation attribute
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace ZibStack.Generated");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        // Wrapper name includes a hash segment for interface proxies so that a real class
        // named the same as the interface can coexist with its interface-proxy in the same
        // namespace without producing duplicate static-class definitions.
        var arityTag = classModel.TypeParameters.Count > 0
            ? $"_{classModel.TypeParameters.Count}"
            : "";
        var wrapperName = classModel.IsInterfaceProxy
            ? $"__{classModel.ClassName}{arityTag}_IfaceAop"
            : $"__{classModel.ClassName}{arityTag}_Aop";
        sb.AppendLine($"    internal static class {wrapperName}");
        sb.AppendLine("    {");

        // Reset per-class state in each emitter before any emission. This is critical —
        // the same emitter instance is reused across incremental generator runs and across
        // different class-emissions within a single run; without this reset, state like
        // "I already wrote __cachedLogger for this class" leaks across and produces
        // generated files that reference undefined members.
        foreach (var emitter in emitters.Values)
            emitter.BeginClass(classModel);

        // Per-method: class members from emitters
        foreach (var method in classModel.Methods)
        {
            foreach (var aspect in method.Aspects)
            {
                if (emitters.TryGetValue(aspect.AttributeFullName, out var emitter))
                    emitter.EmitClassMembers(sb, classModel, method, aspect, "        ");
            }
            sb.AppendLine();
        }

        // Per-method: interceptor methods
        foreach (var method in classModel.Methods)
        {
            var methodCallSites = callSites
                .Where(cs => cs.MethodName == method.MethodName
                    && cs.ContainingClassName == classModel.ClassName)
                .ToList();

            if (methodCallSites.Count == 0)
                continue;

            EmitInterceptorMethod(sb, classModel, method, methodCallSites, emitters);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitInterceptorMethod(
        StringBuilder sb,
        InterceptedClassModel classModel,
        InterceptedMethodModel method,
        List<CallSiteModel> callSites,
        IReadOnlyDictionary<string, IAspectEmitter> emitters)
    {
        // InterceptsLocation attributes
        foreach (var cs in callSites)
            sb.AppendLine($"        {cs.InterceptsLocationAttributeSyntax}");

        // Receiver type: for a generic class/interface we need to reproduce the open
        // generic signature and attach the same type parameters to the extension method
        // itself so the compiler can infer them from the `this` argument. Method-level
        // type parameters come after class-level ones.
        string receiverType = classModel.ClassName;
        var allTypeParams = new List<TypeParameterModel>();
        allTypeParams.AddRange(classModel.TypeParameters);
        allTypeParams.AddRange(method.MethodTypeParameters);
        string methodTypeParamSuffix = "";
        string whereClauses = "";
        if (classModel.TypeParameters.Count > 0)
        {
            var tpNames = string.Join(", ", classModel.TypeParameters.Select(t => t.Name));
            receiverType = $"{classModel.ClassName}<{tpNames}>";
        }
        if (allTypeParams.Count > 0)
        {
            methodTypeParamSuffix = $"<{string.Join(", ", allTypeParams.Select(t => t.Name))}>";
            var sbWhere = new StringBuilder();
            foreach (var tp in allTypeParams)
            {
                if (tp.Constraints.Count == 0) continue;
                sbWhere.Append($" where {tp.Name} : {string.Join(", ", tp.Constraints)}");
            }
            whereClauses = sbWhere.ToString();
        }

        // Method signature
        var asyncKeyword = method.IsAsync ? "async " : "";
        var paramList = string.Join(", ",
            method.Parameters.Select(p => $"{p.FullyQualifiedType} {p.Name}"));
        var fullParamList = paramList.Length > 0
            ? $"this {receiverType} @this, {paramList}"
            : $"this {receiverType} @this";

        sb.AppendLine($"        internal static {asyncKeyword}{method.ReturnType} {method.MethodName}_Aop{methodTypeParamSuffix}({fullParamList}){whereClauses}");
        sb.AppendLine("        {");

        var indent = "            ";

        // If the method has a CancellationToken parameter, create a linked CTS
        // upfront so handlers can signal cancellation via AspectContext that the
        // method body actually observes through its own awaits. The linked source
        // means cancellation flows BOTH ways: caller-side cancellation still
        // propagates, and handler-side cancellation (e.g. TimeoutHandler.CancelAfter)
        // also reaches the body.
        if (method.CancellationTokenParameterIndex.HasValue)
        {
            var ctParam = method.Parameters[method.CancellationTokenParameterIndex.Value];
            sb.AppendLine($"{indent}using var __linkedCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({ctParam.Name});");
        }

        // Separate aspects into before/after handlers and around handlers
        var beforeAfterAspects = method.Aspects.Where(a => !a.IsAroundHandler).ToList();
        var aroundAspects = method.Aspects.Where(a => a.IsAroundHandler).ToList();

        // Emit OnBefore for non-around aspects (ascending order)
        foreach (var aspect in beforeAfterAspects)
        {
            if (emitters.TryGetValue(aspect.AttributeFullName, out var emitter))
                emitter.EmitBefore(sb, classModel, method, aspect, indent);
            else if (aspect.HandlerTypeName != null)
                EmitRuntimeHandlerBefore(sb, classModel, method, aspect, indent);
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}var __sw = global::System.Diagnostics.Stopwatch.StartNew();");

        // Declare around handler instances + contexts before the proceed chain
        foreach (var aspect in aroundAspects)
        {
            if (aspect.HandlerTypeName != null)
                EmitRuntimeHandlerBefore(sb, classModel, method, aspect, indent);
        }

        // Build the proceed chain for around handlers. If the method has a CT param,
        // pass `__linkedCts.Token` in its slot so the body sees cancellation that
        // any handler signals via __linkedCts (e.g. TimeoutHandler.CancelAfter).
        var callArgs = string.Join(", ",
            method.Parameters.Select((p, i) =>
                method.CancellationTokenParameterIndex == i ? "__linkedCts.Token" : p.Name));
        // Pass method-level type arguments explicitly. Inference usually works when a
        // method type parameter appears in the parameter list, but fails when it only
        // appears in the return type (e.g. `T Create<T>() where T : new()`), so we always
        // spell them out to stay on the safe path.
        var methodTypeArgs = method.MethodTypeParameters.Count > 0
            ? $"<{string.Join(", ", method.MethodTypeParameters.Select(t => t.Name))}>"
            : "";
        var originalCall = $"@this.{method.MethodName}{methodTypeArgs}({callArgs})";

        if (aroundAspects.Count > 0)
        {
            // Build nested Around calls: outermost around wraps inner, innermost wraps original call
            if (method.IsAsync)
            {
                // Async: Func<ValueTask<object?>>
                sb.AppendLine($"{indent}global::System.Func<global::System.Threading.Tasks.ValueTask<object?>> __proceed = async () =>");
                sb.AppendLine($"{indent}{{");
                if (method.ReturnsVoid)
                {
                    sb.AppendLine($"{indent}    await {originalCall}.ConfigureAwait(false);");
                    sb.AppendLine($"{indent}    return null;");
                }
                else
                    sb.AppendLine($"{indent}    return await {originalCall}.ConfigureAwait(false);");
                sb.AppendLine($"{indent}}};");

                // Wrap with each around handler (innermost first, outermost last)
                foreach (var aspect in aroundAspects)
                {
                    var handlerVar = GetHandlerVarName(aspect);
                    var ctxVar = GetContextVarName(aspect);
                    sb.AppendLine($"{indent}var __prevProceed_{handlerVar} = __proceed;");
                    if (aspect.GenericAroundTypeArg is not null && aspect.IsAsyncAroundHandler)
                    {
                        // Generic async: IAsyncAroundAspectHandler<T>
                        var t = aspect.GenericAroundTypeArg;
                        sb.AppendLine($"{indent}__proceed = async () => await {handlerVar}.AroundAsync({ctxVar}, async () => ({t}?)await __prevProceed_{handlerVar}());");
                    }
                    else if (aspect.GenericAroundTypeArg is not null && !aspect.IsAsyncAroundHandler)
                    {
                        // Generic sync-only around handler on async method — not supported
                        sb.AppendLine($"{indent}#error IAroundAspectHandler<T> cannot be used on async methods. Implement IAsyncAroundAspectHandler<T> on the handler, or add IAsyncAroundAspectHandler.");
                    }
                    else if (aspect.IsAsyncAroundHandler)
                        sb.AppendLine($"{indent}__proceed = () => {handlerVar}.AroundAsync({ctxVar}, __prevProceed_{handlerVar});");
                    else
                    {
                        // Sync-only around handler on async method — not supported
                        sb.AppendLine($"{indent}#error IAroundAspectHandler cannot be used on async methods. Implement IAsyncAroundAspectHandler on the handler.");
                    }
                }

                // Execute the chain
                sb.AppendLine($"{indent}try");
                sb.AppendLine($"{indent}{{");
                if (method.ReturnsVoid)
                    sb.AppendLine($"{indent}    await __proceed().ConfigureAwait(false);");
                else
                {
                    // await on ValueTask<object?> yields object? — cast to the *unwrapped* return type,
                    // not the full Task<T>/ValueTask<T> wrapper.
                    var castType = GetUnwrappedReturnType(method);
                    sb.AppendLine($"{indent}    var __result = ({castType})(await __proceed().ConfigureAwait(false))!;");
                }
            }
            else
            {
                // Sync: Func<object?>
                sb.AppendLine($"{indent}global::System.Func<object?> __proceed = () =>");
                sb.AppendLine($"{indent}{{");
                if (method.ReturnsVoid)
                {
                    sb.AppendLine($"{indent}    {originalCall};");
                    sb.AppendLine($"{indent}    return null;");
                }
                else
                    sb.AppendLine($"{indent}    return {originalCall};");
                sb.AppendLine($"{indent}}};");

                foreach (var aspect in aroundAspects)
                {
                    var handlerVar = GetHandlerVarName(aspect);
                    var ctxVar = GetContextVarName(aspect);
                    sb.AppendLine($"{indent}var __prevProceed_{handlerVar} = __proceed;");
                    if (aspect.GenericAroundTypeArg is not null)
                    {
                        var t = aspect.GenericAroundTypeArg;
                        sb.AppendLine($"{indent}__proceed = () => {handlerVar}.Around({ctxVar}, () => ({t}?)__prevProceed_{handlerVar}());");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}__proceed = () => {handlerVar}.Around({ctxVar}, __prevProceed_{handlerVar});");
                    }
                }

                sb.AppendLine($"{indent}try");
                sb.AppendLine($"{indent}{{");
                if (method.ReturnsVoid)
                    sb.AppendLine($"{indent}    __proceed();");
                else
                    sb.AppendLine($"{indent}    var __result = ({method.ReturnType})__proceed()!;");
            }
        }
        else
        {
            // No around handlers — direct call (original behavior)
            sb.AppendLine($"{indent}try");
            sb.AppendLine($"{indent}{{");

            if (method.IsAsync)
                originalCall = $"await {originalCall}.ConfigureAwait(false)";

            if (method.ReturnsVoid)
                sb.AppendLine($"{indent}    {originalCall};");
            else
                sb.AppendLine($"{indent}    var __result = {originalCall};");
        }

        sb.AppendLine($"{indent}    __sw.Stop();");

        // OnAfter for non-around aspects (reversed)
        foreach (var aspect in beforeAfterAspects.AsEnumerable().Reverse())
        {
            if (emitters.TryGetValue(aspect.AttributeFullName, out var emitter))
                emitter.EmitAfter(sb, classModel, method, aspect, indent + "    ");
            else if (aspect.HandlerTypeName != null)
                EmitRuntimeHandlerAfter(sb, method, aspect, indent + "    ");
        }

        if (!method.ReturnsVoid)
            sb.AppendLine($"{indent}    return __result;");

        sb.AppendLine($"{indent}}}");
        // Use named exception variable only if there are before/after aspects that need it
        if (beforeAfterAspects.Count > 0)
            sb.AppendLine($"{indent}catch (global::System.Exception __ex)");
        else
            sb.AppendLine($"{indent}catch");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    __sw.Stop();");

        // OnException for non-around aspects (reversed)
        foreach (var aspect in beforeAfterAspects.AsEnumerable().Reverse())
        {
            if (emitters.TryGetValue(aspect.AttributeFullName, out var emitter))
                emitter.EmitOnException(sb, classModel, method, aspect, indent + "    ");
            else if (aspect.HandlerTypeName != null)
                EmitRuntimeHandlerOnException(sb, method, aspect, indent + "    ");
        }

        sb.AppendLine($"{indent}    throw;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine("        }");
    }

    // === Runtime handler emission (for [AspectHandler]-based aspects) ===

    /// <summary>
    /// Expands a KeyTemplate string like <c>"order:{order.Customer.Id}:{status}"</c> into
    /// a C# interpolated string <c>$"order:{order.Customer.Id}:{status}"</c>.
    /// Literal braces in the template are escaped for interpolation.
    /// </summary>
    private static string ExpandKeyTemplate(string template, InterceptedMethodModel method)
    {
        // The template uses {expr} placeholders that map directly to C# expressions.
        // We need to:
        // 1. Escape any literal {{ or }} (user wants a literal brace in the key)
        //    — these are already doubled in the attribute string, leave as-is
        // 2. Pass {expr} through as-is — C# interpolation handles them
        //
        // The result is just $"<template>" — the C# compiler validates expressions.
        // We only need to ensure the template is safe as an interpolated string.

        return $"$\"{template}\"";
    }

    /// <summary>
    /// For async methods, extracts the inner type from Task&lt;T&gt; / ValueTask&lt;T&gt;.
    /// For sync methods, returns ReturnType as-is.
    /// </summary>
    private static string GetUnwrappedReturnType(InterceptedMethodModel method)
    {
        if (!method.IsAsync) return method.ReturnType;

        var rt = method.ReturnType;
        // Matches: global::System.Threading.Tasks.Task<X> or Task<X> or ValueTask<X>
        var openIdx = rt.IndexOf('<');
        var closeIdx = rt.LastIndexOf('>');
        if (openIdx >= 0 && closeIdx > openIdx)
            return rt.Substring(openIdx + 1, closeIdx - openIdx - 1);

        return method.ReturnType;
    }

    private static string? FormatPropertyValue(object? value)
    {
        switch (value)
        {
            case null: return "null";
            case string s: return $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
            case bool b: return b ? "true" : "false";
            case int i: return $"{i}";
            case long l: return $"{l}L";
            case double d: return $"{d.ToString(System.Globalization.CultureInfo.InvariantCulture)}d";
            case float f: return $"{f.ToString(System.Globalization.CultureInfo.InvariantCulture)}f";
            case decimal m: return $"{m.ToString(System.Globalization.CultureInfo.InvariantCulture)}m";
            case Microsoft.CodeAnalysis.ITypeSymbol ts:
                return $"typeof({ts.ToDisplayString(Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat)})";
            case System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.TypedConstant> arr:
                return FormatTypedConstantArray(arr);
            default: return null;
        }
    }

    private static string? FormatTypedConstantArray(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.TypedConstant> arr)
    {
        if (arr.IsDefaultOrEmpty) return "null";

        // Check if it's a Type[] array
        if (arr[0].Kind == Microsoft.CodeAnalysis.TypedConstantKind.Type)
        {
            var types = arr.Select(tc => tc.Value as Microsoft.CodeAnalysis.ITypeSymbol)
                .Where(t => t is not null)
                .Select(t => $"typeof({t!.ToDisplayString(Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat)})");
            return $"new global::System.Type[] {{ {string.Join(", ", types)} }}";
        }

        // Fallback: primitive array
        var elements = arr.Select(tc => FormatPropertyValue(tc.Value)).Where(v => v is not null);
        return $"new object[] {{ {string.Join(", ", elements)} }}";
    }

    private static string SafeName(AspectInfo aspect) =>
        aspect.AttributeFullName.Replace(".", "_").Replace("+", "_");

    private static string GetHandlerVarName(AspectInfo aspect) => $"__handler_{SafeName(aspect)}";
    private static string GetContextVarName(AspectInfo aspect) => $"__ctx_{SafeName(aspect)}";

    private static void EmitRuntimeHandlerBefore(StringBuilder sb, InterceptedClassModel classModel, InterceptedMethodModel method, AspectInfo aspect, string indent)
    {
        var handlerVar = GetHandlerVarName(aspect);
        var ctxVar = GetContextVarName(aspect);

        sb.AppendLine($"{indent}var {handlerVar} = global::ZibStack.NET.Aop.AspectServiceProvider.Resolve<{aspect.HandlerTypeName}>();");
        sb.AppendLine($"{indent}var {ctxVar} = new global::ZibStack.NET.Aop.AspectContext");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    ClassName = \"{classModel.ClassName}\",");
        sb.AppendLine($"{indent}    MethodName = \"{method.MethodName}\",");

        // Build parameters array
        if (method.Parameters.Count == 0)
        {
            sb.AppendLine($"{indent}    Parameters = global::System.Array.Empty<global::ZibStack.NET.Aop.AspectParameterInfo>()");
        }
        else
        {
            sb.AppendLine($"{indent}    Parameters = new global::ZibStack.NET.Aop.AspectParameterInfo[]");
            sb.AppendLine($"{indent}    {{");
            foreach (var p in method.Parameters)
            {
                var sensitive = p.IsSensitive ? "true" : "false";
                var noLog = p.IsNoLog ? "true" : "false";
                var value = p.IsNoLog ? "null" : p.Name;
                sb.AppendLine($"{indent}        new() {{ Name = \"{p.Name}\", Value = {value}, IsSensitive = {sensitive}, IsNoLog = {noLog} }},");
            }
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine($"{indent}}};");

        // Expose the CTS the outer interceptor created for methods with a CancellationToken
        // parameter. Handlers (notably TimeoutHandler) read this to signal cooperative
        // cancellation that the method body actually sees.
        if (method.CancellationTokenParameterIndex.HasValue)
        {
            sb.AppendLine($"{indent}{ctxVar}.CancellationTokenSource = __linkedCts;");
        }

        // Populate context.Properties with attribute named arguments (e.g. DurationSeconds, MaxAttempts, Roles)
        foreach (var kvp in aspect.Properties)
        {
            if (kvp.Key == "Order") continue; // Order is a base AspectAttribute property, not a user property
            if (kvp.Key == "KeyTemplate") continue; // handled below — expanded to interpolated string
            var valueExpr = FormatPropertyValue(kvp.Value);
            if (valueExpr != null)
                sb.AppendLine($"{indent}{ctxVar}.Properties[\"{kvp.Key}\"] = {valueExpr};");
        }

        // KeyTemplate → compile-time expansion to interpolated string cache key.
        // Template "{order.Customer.Id}:{status}" → $"{order.Customer.Id}:{status}"
        // Invalid parameter references are caught by the C# compiler (CS1061 / CS0103).
        if (aspect.Properties.TryGetValue("KeyTemplate", out var ktObj) && ktObj is string keyTemplate && keyTemplate.Length > 0)
        {
            var interpolated = ExpandKeyTemplate(keyTemplate, method);
            sb.AppendLine($"{indent}{ctxVar}.Properties[\"__cacheKey\"] = {interpolated};");
        }

        // Around handlers don't have OnBefore — they wrap via Around/AroundAsync
        if (!aspect.IsAroundHandler)
        {
            if (method.IsAsync && aspect.IsAsyncHandler)
            {
                // Async method + handler has IAsyncAspectHandler → use async path
                sb.AppendLine($"{indent}await {handlerVar}.OnBeforeAsync({ctxVar}).ConfigureAwait(false);");
            }
            else if (!method.IsAsync && aspect.HasSyncHandler)
            {
                // Sync method + handler has IAspectHandler → use sync path
                sb.AppendLine($"{indent}{handlerVar}.OnBefore({ctxVar});");
            }
            else if (!method.IsAsync && aspect.IsAsyncHandler && !aspect.HasSyncHandler)
            {
                // Sync method + handler is async-only → error
                sb.AppendLine($"{indent}// ERROR: IAsyncAspectHandler cannot be used on sync method. Add IAspectHandler to the handler.");
            }
            else if (aspect.HasSyncHandler)
            {
                // Fallback: sync handler on async method (works, just not async-optimized)
                sb.AppendLine($"{indent}{handlerVar}.OnBefore({ctxVar});");
            }
        }
    }

    private static void EmitRuntimeHandlerAfter(StringBuilder sb, InterceptedMethodModel method, AspectInfo aspect, string indent)
    {
        var handlerVar = GetHandlerVarName(aspect);
        var ctxVar = GetContextVarName(aspect);

        sb.AppendLine($"{indent}{ctxVar}.ElapsedMilliseconds = __sw.ElapsedMilliseconds;");
        if (!method.ReturnsVoid)
            sb.AppendLine($"{indent}{ctxVar}.ReturnValue = __result;");
        EmitHandlerCall(sb, method, aspect, handlerVar, ctxVar, indent,
            asyncCall: $"await {handlerVar}.OnAfterAsync({ctxVar}).ConfigureAwait(false);",
            syncCall: $"{handlerVar}.OnAfter({ctxVar});");
    }

    private static void EmitRuntimeHandlerOnException(StringBuilder sb, InterceptedMethodModel method, AspectInfo aspect, string indent)
    {
        var handlerVar = GetHandlerVarName(aspect);
        var ctxVar = GetContextVarName(aspect);

        sb.AppendLine($"{indent}{ctxVar}.ElapsedMilliseconds = __sw.ElapsedMilliseconds;");
        EmitHandlerCall(sb, method, aspect, handlerVar, ctxVar, indent,
            asyncCall: $"await {handlerVar}.OnExceptionAsync({ctxVar}, __ex).ConfigureAwait(false);",
            syncCall: $"{handlerVar}.OnException({ctxVar}, __ex);");
    }

    /// <summary>
    /// Picks async or sync call based on method context and handler capabilities.
    /// Handlers implementing both IAspectHandler and IAsyncAspectHandler get the right one
    /// depending on whether the target method is async.
    /// </summary>
    private static void EmitHandlerCall(StringBuilder sb, InterceptedMethodModel method, AspectInfo aspect,
        string handlerVar, string ctxVar, string indent, string asyncCall, string syncCall)
    {
        if (method.IsAsync && aspect.IsAsyncHandler)
            sb.AppendLine($"{indent}{asyncCall}");
        else if (aspect.HasSyncHandler)
            sb.AppendLine($"{indent}{syncCall}");
        else if (method.IsAsync && !aspect.IsAsyncHandler && !aspect.HasSyncHandler)
            sb.AppendLine($"{indent}// ERROR: handler implements neither IAspectHandler nor IAsyncAspectHandler.");
        else
            sb.AppendLine($"{indent}// ERROR: IAsyncAspectHandler cannot be used on sync method. Add IAspectHandler to the handler.");
    }
}
