namespace ZibStack.NET.UI;

public partial class UiGenerator
{
    // ─── Form class-level attributes ─────────────────────────────────────

    private const string FormAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Marks a class for form metadata generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class FormAttribute : System.Attribute
    {
        /// <summary>Custom form name. Defaults to the class name.</summary>
        public string? Name { get; set; }
        /// <summary>Form layout hint: Vertical, Horizontal, or Inline.</summary>
        public string? Layout { get; set; }
    }
}
";

    private const string FormGroupAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Defines a visual group for form fields.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class FormGroupAttribute : System.Attribute
    {
        public string Name { get; }
        public string? Label { get; set; }
        public int Order { get; set; }
        public FormGroupAttribute(string name) => Name = name;
    }
}
";

    // ─── Form property-level attributes ──────────────────────────────────

    private const string FormFieldAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Customizes how a property is displayed in a form.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormFieldAttribute : System.Attribute
    {
        public string? Label { get; set; }
        public string? Placeholder { get; set; }
        public string? HelpText { get; set; }
        public int Order { get; set; } = -1;
        public string? Group { get; set; }
    }
}
";

    private const string FormIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Excludes a property from form generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormIgnoreAttribute : System.Attribute { }
}
";

    private const string FormHiddenAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Includes in form data but not rendered visually.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormHiddenAttribute : System.Attribute { }
}
";

    private const string FormOrderAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Sets the display order of a form field.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormOrderAttribute : System.Attribute
    {
        public int Order { get; }
        public FormOrderAttribute(int order) => Order = order;
    }
}
";

    private const string FormReadOnlyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a form field as read-only.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormReadOnlyAttribute : System.Attribute { }
}
";

    private const string FormDisabledAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a form field as disabled.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormDisabledAttribute : System.Attribute { }
}
";

    private const string FormSectionAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Assigns a property to a form group.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormSectionAttribute : System.Attribute
    {
        public string Group { get; }
        public FormSectionAttribute(string group) => Group = group;
    }
}
";

    // ─── UI control hint attributes ──────────────────────────────────────

    private const string TextAreaAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a multi-line text area.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TextAreaAttribute : System.Attribute
    {
        public int Rows { get; set; } = 3;
    }
}
";

    private const string SelectAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a dropdown select. Pass an enum type or string options.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class SelectAttribute : System.Attribute
    {
        public System.Type? EnumType { get; }
        public string[]? Options { get; }
        public SelectAttribute() { }
        public SelectAttribute(System.Type enumType) => EnumType = enumType;
        public SelectAttribute(params string[] options) => Options = options;
    }
}
";

    private const string RadioGroupAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a radio button group.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class RadioGroupAttribute : System.Attribute
    {
        public System.Type? EnumType { get; }
        public string[]? Options { get; }
        public RadioGroupAttribute() { }
        public RadioGroupAttribute(System.Type enumType) => EnumType = enumType;
        public RadioGroupAttribute(params string[] options) => Options = options;
    }
}
";

    private const string CheckboxAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a checkbox / toggle.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class CheckboxAttribute : System.Attribute { }
}
";

    private const string DatePickerAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a date picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class DatePickerAttribute : System.Attribute
    {
        public string? Min { get; set; }
        public string? Max { get; set; }
    }
}
";

    private const string TimePickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a time picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TimePickerAttribute : System.Attribute { }
}
";

    private const string DateTimePickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a date and time picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class DateTimePickerAttribute : System.Attribute { }
}
";

    private const string FilePickerAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a file upload input.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FilePickerAttribute : System.Attribute
    {
        public string? Accept { get; set; }
        public bool Multiple { get; set; }
    }
}
";

    private const string ColorPickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a color picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ColorPickerAttribute : System.Attribute { }
}
";

    private const string RichTextAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a rich text editor.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class RichTextAttribute : System.Attribute { }
}
";

    private const string SliderAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a range slider.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class SliderAttribute : System.Attribute
    {
        public double Min { get; set; }
        public double Max { get; set; } = 100;
        public double Step { get; set; } = 1;
    }
}
";

    private const string PasswordInputAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a password (masked) input.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class PasswordInputAttribute : System.Attribute { }
}
";

    // ─── Conditional attribute ───────────────────────────────────────────

    private const string FormConditionalAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Show/hide this field based on another field's value.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FormConditionalAttribute : System.Attribute
    {
        public string Field { get; }
        public string Value { get; }
        /// <summary>Comparison operator: Equals, NotEquals, Contains, GreaterThan, LessThan. Default: Equals.</summary>
        public string Operator { get; set; } = ""Equals"";
        public FormConditionalAttribute(string field, string value)
        {
            Field = field;
            Value = value;
        }
    }
}
";

    // ─── Table attributes ────────────────────────────────────────────────

    private const string TableAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Marks a class for table/grid metadata generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class TableAttribute : System.Attribute
    {
        /// <summary>Custom table name. Defaults to the class name.</summary>
        public string? Name { get; set; }
        /// <summary>Default page size. Default: 20.</summary>
        public int DefaultPageSize { get; set; } = 20;
        /// <summary>Available page sizes. Default: 10, 20, 50, 100.</summary>
        public int[]? PageSizes { get; set; }
        /// <summary>Default sort column name.</summary>
        public string? DefaultSort { get; set; }
        /// <summary>Default sort direction: Asc or Desc. Default: Asc.</summary>
        public string DefaultSortDirection { get; set; } = ""Asc"";
    }
}
";

    private const string TableColumnAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Customizes how a property is displayed as a table column.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TableColumnAttribute : System.Attribute
    {
        public string? Label { get; set; }
        public bool Sortable { get; set; }
        public bool Filterable { get; set; }
        public string? Format { get; set; }
        public int Order { get; set; } = -1;
        public bool IsVisible { get; set; } = true;
        public string? Width { get; set; }
    }
}
";

    private const string TableIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Excludes a property from table generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TableIgnoreAttribute : System.Attribute { }
}
";
}
