using System.Linq;
using System.Text;

namespace ZibStack.NET.UI;

public partial class UiGenerator
{
    private static string GenerateTableDescriptor(TableClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.UI for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.UI;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName} : ITableDescriptorProvider");
        sb.AppendLine("{");

        // Static descriptor
        sb.AppendLine("    private static readonly TableDescriptor _tableDescriptor = new TableDescriptor(");
        sb.AppendLine($"        name: \"{EscapeString(info.TableName)}\",");

        // Columns
        sb.AppendLine("        columns: new TableColumnDescriptor[]");
        sb.AppendLine("        {");
        foreach (var col in info.Columns)
        {
            EmitTableColumn(sb, col);
        }
        sb.AppendLine("        },");

        // Pagination
        var pageSizesStr = string.Join(", ", info.PageSizes);
        sb.AppendLine($"        pagination: new PaginationDescriptor({info.DefaultPageSize}, new[] {{ {pageSizesStr} }}),");

        // DefaultSort
        if (info.DefaultSort != null)
        {
            var sortCol = ToCamelCase(info.DefaultSort);
            sb.AppendLine($"        defaultSort: new SortDescriptor(\"{EscapeString(sortCol)}\", \"{EscapeString(info.DefaultSortDirection)}\")");
        }
        else
        {
            sb.AppendLine("        defaultSort: null");
        }

        sb.AppendLine("    );");

        sb.AppendLine();
        sb.AppendLine("    public static TableDescriptor GetTableDescriptor() => _tableDescriptor;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitTableColumn(StringBuilder sb, TableColumnInfo col)
    {
        sb.AppendLine($"            new TableColumnDescriptor(");
        sb.AppendLine($"                name: \"{EscapeString(col.JsonName)}\",");
        sb.AppendLine($"                type: \"{EscapeString(col.ColumnType)}\",");

        if (col.Label != null)
            sb.AppendLine($"                label: \"{EscapeString(col.Label)}\",");

        sb.AppendLine($"                sortable: {(col.Sortable ? "true" : "false")},");
        sb.AppendLine($"                filterable: {(col.Filterable ? "true" : "false")},");

        if (col.Format != null)
            sb.AppendLine($"                format: \"{EscapeString(col.Format)}\",");

        sb.AppendLine($"                order: {col.Order},");

        if (col.Width != null)
            sb.AppendLine($"                width: \"{EscapeString(col.Width)}\",");

        if (col.EnumValues.Count > 0)
        {
            var optionsStr = string.Join(", ", col.EnumValues.Select(v => $"\"{EscapeString(v)}\""));
            sb.AppendLine($"                options: new[] {{ {optionsStr} }},");
        }

        sb.AppendLine($"                isVisible: {(col.IsVisible ? "true" : "false")}),");
    }
}
