using System.Globalization;
using System.Linq;
using System.Text;

namespace ZibStack.NET.UI;

public partial class UiGenerator
{
    private static string GenerateFormJson(FormClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.UI — JSON schema for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly string _formSchemaJson =");

        // Build JSON
        var json = BuildFormJsonString(info);
        sb.AppendLine($"        @\"{EscapeVerbatimString(json)}\";");
        sb.AppendLine();
        sb.AppendLine("    public static string GetFormSchemaJson() => _formSchemaJson;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateTableJson(TableClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.UI — JSON schema for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly string _tableSchemaJson =");

        var json = BuildTableJsonString(info);
        sb.AppendLine($"        @\"{EscapeVerbatimString(json)}\";");
        sb.AppendLine();
        sb.AppendLine("    public static string GetTableSchemaJson() => _tableSchemaJson;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // ─── JSON builders ───────────────────────────────────────────────────

    private static string BuildFormJsonString(FormClassInfo info)
    {
        var sb = new StringBuilder();
        sb.Append("{");
        sb.Append($"\"name\":\"{JsonEscape(info.FormName)}\",");
        sb.Append($"\"layout\":\"{JsonEscape(info.Layout)}\",");

        // Groups
        sb.Append("\"groups\":[");
        for (int i = 0; i < info.Groups.Count; i++)
        {
            if (i > 0) sb.Append(",");
            var g = info.Groups[i];
            sb.Append("{");
            sb.Append($"\"name\":\"{JsonEscape(g.Name)}\"");
            if (g.Label != null) sb.Append($",\"label\":\"{JsonEscape(g.Label)}\"");
            sb.Append($",\"order\":{g.Order}");
            sb.Append("}");
        }
        sb.Append("],");

        // Fields
        sb.Append("\"fields\":[");
        for (int i = 0; i < info.Fields.Count; i++)
        {
            if (i > 0) sb.Append(",");
            BuildFieldJson(sb, info.Fields[i]);
        }
        sb.Append("]");
        sb.Append("}");

        return sb.ToString();
    }

    private static void BuildFieldJson(StringBuilder sb, FormFieldInfo field)
    {
        sb.Append("{");
        sb.Append($"\"name\":\"{JsonEscape(field.JsonName)}\"");
        sb.Append($",\"type\":\"{JsonEscape(field.FieldType)}\"");
        sb.Append($",\"uiHint\":\"{JsonEscape(field.UiHint)}\"");

        if (field.Label != null) sb.Append($",\"label\":\"{JsonEscape(field.Label)}\"");
        if (field.Placeholder != null) sb.Append($",\"placeholder\":\"{JsonEscape(field.Placeholder)}\"");
        if (field.HelpText != null) sb.Append($",\"helpText\":\"{JsonEscape(field.HelpText)}\"");
        if (field.Group != null) sb.Append($",\"group\":\"{JsonEscape(field.Group)}\"");

        sb.Append($",\"order\":{field.Order}");

        if (field.IsRequired) sb.Append(",\"required\":true");
        if (field.IsHidden) sb.Append(",\"hidden\":true");
        if (field.IsReadOnly) sb.Append(",\"readOnly\":true");
        if (field.IsDisabled) sb.Append(",\"disabled\":true");
        if (field.IsCreateOnly) sb.Append(",\"createOnly\":true");
        if (field.IsUpdateOnly) sb.Append(",\"updateOnly\":true");
        if (field.IsNullable) sb.Append(",\"nullable\":true");

        // Options
        if (field.Options.Count > 0)
        {
            sb.Append(",\"options\":[");
            for (int i = 0; i < field.Options.Count; i++)
            {
                if (i > 0) sb.Append(",");
                sb.Append($"{{\"value\":\"{JsonEscape(field.Options[i].Value)}\",\"label\":\"{JsonEscape(field.Options[i].Label)}\"}}");
            }
            sb.Append("]");
        }

        // Conditional
        if (field.Conditional != null)
        {
            sb.Append($",\"conditional\":{{\"field\":\"{JsonEscape(field.Conditional.FieldName)}\",\"operator\":\"{JsonEscape(field.Conditional.Operator)}\",\"value\":\"{JsonEscape(field.Conditional.Value)}\"}}");
        }

        // Validation
        if (field.ValidationRules.Count > 0)
        {
            sb.Append(",\"validation\":{");
            bool first = true;
            foreach (var rule in field.ValidationRules)
            {
                if (!first) sb.Append(",");
                first = false;
                switch (rule.Kind)
                {
                    case "required":
                        sb.Append("\"required\":true");
                        break;
                    case "minLength":
                        sb.Append($"\"minLength\":{(int)(rule.MinValue ?? 0)}");
                        break;
                    case "maxLength":
                        sb.Append($"\"maxLength\":{(int)(rule.MaxValue ?? 0)}");
                        break;
                    case "range":
                        sb.Append($"\"min\":{(rule.MinValue ?? 0).ToString(CultureInfo.InvariantCulture)},\"max\":{(rule.MaxValue ?? 0).ToString(CultureInfo.InvariantCulture)}");
                        break;
                    case "email":
                        sb.Append("\"email\":true");
                        break;
                    case "url":
                        sb.Append("\"url\":true");
                        break;
                    case "pattern":
                        if (rule.Pattern != null)
                            sb.Append($"\"pattern\":\"{JsonEscape(rule.Pattern)}\"");
                        break;
                    case "notEmpty":
                        sb.Append("\"notEmpty\":true");
                        break;
                }
            }
            sb.Append("}");
        }

        // Props
        if (field.Props.Count > 0)
        {
            sb.Append(",\"props\":{");
            bool first = true;
            foreach (var kv in field.Props)
            {
                if (!first) sb.Append(",");
                first = false;
                // Try to emit as number if possible
                if (double.TryParse(kv.Value, NumberStyles.Any, CultureInfo.InvariantCulture, out var numVal))
                    sb.Append($"\"{JsonEscape(kv.Key)}\":{kv.Value}");
                else if (kv.Value == "true" || kv.Value == "false")
                    sb.Append($"\"{JsonEscape(kv.Key)}\":{kv.Value}");
                else
                    sb.Append($"\"{JsonEscape(kv.Key)}\":\"{JsonEscape(kv.Value)}\"");
            }
            sb.Append("}");
        }

        sb.Append("}");
    }

    private static string BuildTableJsonString(TableClassInfo info)
    {
        var sb = new StringBuilder();
        sb.Append("{");
        sb.Append($"\"name\":\"{JsonEscape(info.TableName)}\",");

        // Columns
        sb.Append("\"columns\":[");
        for (int i = 0; i < info.Columns.Count; i++)
        {
            if (i > 0) sb.Append(",");
            var col = info.Columns[i];
            sb.Append("{");
            sb.Append($"\"name\":\"{JsonEscape(col.JsonName)}\"");
            sb.Append($",\"type\":\"{JsonEscape(col.ColumnType)}\"");
            if (col.Label != null) sb.Append($",\"label\":\"{JsonEscape(col.Label)}\"");
            sb.Append($",\"sortable\":{(col.Sortable ? "true" : "false")}");
            sb.Append($",\"filterable\":{(col.Filterable ? "true" : "false")}");
            if (col.Format != null) sb.Append($",\"format\":\"{JsonEscape(col.Format)}\"");
            sb.Append($",\"order\":{col.Order}");
            if (!col.IsVisible) sb.Append(",\"visible\":false");
            if (col.Width != null) sb.Append($",\"width\":\"{JsonEscape(col.Width)}\"");
            if (col.EnumValues.Count > 0)
            {
                sb.Append(",\"options\":[");
                sb.Append(string.Join(",", col.EnumValues.Select(v => $"\"{JsonEscape(v)}\"")));
                sb.Append("]");
            }
            sb.Append("}");
        }
        sb.Append("],");

        // Pagination
        sb.Append($"\"pagination\":{{\"defaultPageSize\":{info.DefaultPageSize},\"pageSizes\":[{string.Join(",", info.PageSizes)}]}},");

        // DefaultSort
        if (info.DefaultSort != null)
        {
            sb.Append($"\"defaultSort\":{{\"column\":\"{JsonEscape(ToCamelCase(info.DefaultSort))}\",\"direction\":\"{JsonEscape(info.DefaultSortDirection)}\"}}");
        }
        else
        {
            sb.Append("\"defaultSort\":null");
        }

        sb.Append("}");
        return sb.ToString();
    }

    // ─── Helpers ─────────────────────────────────────────────────────────

    private static string JsonEscape(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");

    private static string EscapeVerbatimString(string s)
        => s.Replace("\"", "\"\"");
}
