namespace ZibStack.NET.UI;

public partial class UiGenerator
{
    // ─── Form class-level attributes ─────────────────────────────────────

    private const string UiFormAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Marks a class for form metadata generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class UiFormAttribute : System.Attribute
    {
        /// <summary>Custom form name. Defaults to the class name.</summary>
        public string? Name { get; set; }
        /// <summary>Form layout hint: Vertical, Horizontal, or Inline.</summary>
        public string? Layout { get; set; }
    }
}
";

    private const string UiFormGroupAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Defines a visual group for form fields.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class UiFormGroupAttribute : System.Attribute
    {
        public string Name { get; }
        public string? Label { get; set; }
        public int Order { get; set; }
        public UiFormGroupAttribute(string name) => Name = name;
    }
}
";

    // ─── Form property-level attributes ──────────────────────────────────

    private const string UiFormFieldAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Customizes how a property is displayed in a form.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormFieldAttribute : System.Attribute
    {
        public string? Label { get; set; }
        public string? Placeholder { get; set; }
        public string? HelpText { get; set; }
        public int Order { get; set; } = -1;
        public string? Group { get; set; }
    }
}
";

    private const string UiFormIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Excludes a property from form generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormIgnoreAttribute : System.Attribute { }
}
";

    private const string UiFormHiddenAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Includes in form data but not rendered visually.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormHiddenAttribute : System.Attribute { }
}
";

    private const string UiFormOrderAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Sets the display order of a form field.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormOrderAttribute : System.Attribute
    {
        public int Order { get; }
        public UiFormOrderAttribute(int order) => Order = order;
    }
}
";

    private const string UiFormReadOnlyAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a form field as read-only.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormReadOnlyAttribute : System.Attribute { }
}
";

    private const string UiFormDisabledAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a form field as disabled.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormDisabledAttribute : System.Attribute { }
}
";

    private const string UiFormSectionAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Assigns a property to a form group.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormSectionAttribute : System.Attribute
    {
        public string Group { get; }
        public UiFormSectionAttribute(string group) => Group = group;
    }
}
";

    // ─── UI control hint attributes ──────────────────────────────────────

    private const string TextAreaAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a multi-line text area.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TextAreaAttribute : System.Attribute
    {
        public int Rows { get; set; } = 3;
    }
}
";

    private const string SelectAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a dropdown select. Pass an enum type or string options.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class SelectAttribute : System.Attribute
    {
        public System.Type? EnumType { get; }
        public string[]? Options { get; }
        public SelectAttribute() { }
        public SelectAttribute(System.Type enumType) => EnumType = enumType;
        public SelectAttribute(params string[] options) => Options = options;
    }
}
";

    private const string RadioGroupAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a radio button group.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class RadioGroupAttribute : System.Attribute
    {
        public System.Type? EnumType { get; }
        public string[]? Options { get; }
        public RadioGroupAttribute() { }
        public RadioGroupAttribute(System.Type enumType) => EnumType = enumType;
        public RadioGroupAttribute(params string[] options) => Options = options;
    }
}
";

    private const string CheckboxAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a checkbox / toggle.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class CheckboxAttribute : System.Attribute { }
}
";

    private const string DatePickerAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a date picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class DatePickerAttribute : System.Attribute
    {
        public string? Min { get; set; }
        public string? Max { get; set; }
    }
}
";

    private const string TimePickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a time picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class TimePickerAttribute : System.Attribute { }
}
";

    private const string DateTimePickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a date and time picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class DateTimePickerAttribute : System.Attribute { }
}
";

    private const string FilePickerAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Render as a file upload input.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class FilePickerAttribute : System.Attribute
    {
        public string? Accept { get; set; }
        public bool Multiple { get; set; }
    }
}
";

    private const string ColorPickerAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a color picker.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ColorPickerAttribute : System.Attribute { }
}
";

    private const string RichTextAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a rich text editor.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class RichTextAttribute : System.Attribute { }
}
";

    private const string SliderAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a range slider.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class SliderAttribute : System.Attribute
    {
        public double Min { get; set; }
        public double Max { get; set; } = 100;
        public double Step { get; set; } = 1;
    }
}
";

    private const string PasswordInputAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Render as a password (masked) input.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class PasswordInputAttribute : System.Attribute { }
}
";

    // ─── Conditional attribute ───────────────────────────────────────────

    private const string UiFormConditionalAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Show/hide this field based on another field's value.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiFormConditionalAttribute : System.Attribute
    {
        public string Field { get; }
        public string Value { get; }
        /// <summary>Comparison operator: Equals, NotEquals, Contains, GreaterThan, LessThan. Default: Equals.</summary>
        public string Operator { get; set; } = ""Equals"";
        public UiFormConditionalAttribute(string field, string value)
        {
            Field = field;
            Value = value;
        }
    }
}
";

    // ─── Table attributes ────────────────────────────────────────────────

    private const string UiTableAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Marks a class for table/grid metadata generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class UiTableAttribute : System.Attribute
    {
        /// <summary>Custom table name. Defaults to the class name.</summary>
        public string? Name { get; set; }
        /// <summary>Default page size. Default: 20.</summary>
        public int DefaultPageSize { get; set; } = 20;
        /// <summary>Available page sizes. Default: 10, 20, 50, 100.</summary>
        public int[]? PageSizes { get; set; }
        /// <summary>Default sort column name.</summary>
        public string? DefaultSort { get; set; }
        /// <summary>Default sort direction: Asc or Desc. Default: Asc.</summary>
        public string DefaultSortDirection { get; set; } = ""Asc"";
        /// <summary>Canonical URL where this table's schema JSON is served. Used by [ChildTable] to resolve drill-down URLs.</summary>
        public string? SchemaUrl { get; set; }
    }
}
";

    private const string UiTableColumnAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Customizes how a property is displayed as a table column.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiTableColumnAttribute : System.Attribute
    {
        public string? Label { get; set; }
        public bool Sortable { get; set; }
        public bool Filterable { get; set; }
        public string? Format { get; set; }
        public int Order { get; set; } = -1;
        public bool IsVisible { get; set; } = true;
        public string? Width { get; set; }
    }
}
";

    private const string UiTableIgnoreAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Excludes a property from table generation.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class UiTableIgnoreAttribute : System.Attribute { }
}
";

    // ─── Relationship attributes ─────────────────────────────────────────

    private const string OneToManyAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Declares a one-to-many relationship on a navigation property (e.g. ICollection&lt;T&gt;).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class OneToManyAttribute : System.Attribute
    {
        /// <summary>Foreign key property name on the child type. Auto-detected by convention if omitted.</summary>
        public string? ForeignKey { get; set; }
        /// <summary>UI display label for the relationship.</summary>
        public string? Label { get; set; }
        /// <summary>Override table schema URL for the child. Resolved from child's [UiTable] if omitted.</summary>
        public string? SchemaUrl { get; set; }
        /// <summary>Override form schema URL for the child. Resolved from child's [UiForm] if omitted.</summary>
        public string? FormSchemaUrl { get; set; }
    }
}
";

    private const string OneToOneAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Declares a one-to-one relationship on a navigation property.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false)]
    internal sealed class OneToOneAttribute : System.Attribute
    {
        /// <summary>Foreign key property name. For OneToOne, looked up on the parent type by convention.</summary>
        public string? ForeignKey { get; set; }
        /// <summary>UI display label for the relationship.</summary>
        public string? Label { get; set; }
        /// <summary>Override table schema URL. Resolved from target's [UiTable] if omitted.</summary>
        public string? SchemaUrl { get; set; }
        /// <summary>Override form schema URL. Resolved from target's [UiForm] if omitted.</summary>
        public string? FormSchemaUrl { get; set; }
    }
}
";

    // ─── ERP: Child tables (drill-down) ──────────────────────────────────

    private const string EntityAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Opt-in: generates IEntityTypeConfiguration&lt;T&gt; for EF Core from this model's properties and relationships.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class EntityAttribute : System.Attribute
    {
        /// <summary>Override the database table name. Defaults to the class name.</summary>
        public string? TableName { get; set; }
        /// <summary>Database schema (e.g. ""dbo"").</summary>
        public string? Schema { get; set; }
    }
}
";

    private const string ChildTableAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Defines a child table relationship for hierarchical drill-down.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class ChildTableAttribute : System.Attribute
    {
        public System.Type TargetType { get; }
        public string ForeignKey { get; set; } = """";
        public string Label { get; set; } = """";
        public string? SchemaUrl { get; set; }
        public ChildTableAttribute(System.Type targetType) => TargetType = targetType;
    }
}
";

    // ─── ERP: Row actions (wstawki) ──────────────────────────────────────

    private const string RowActionAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Defines a per-row action button (e.g. ""Show postal codes"").</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class RowActionAttribute : System.Attribute
    {
        public string Name { get; }
        public string Label { get; set; } = """";
        public string? Icon { get; set; }
        public string Endpoint { get; set; } = """";
        public string Method { get; set; } = ""GET"";
        public string? Confirmation { get; set; }
        public string? Permission { get; set; }
        public RowActionAttribute(string name) => Name = name;
    }
}
";

    // ─── ERP: Toolbar actions (narzędzia) ────────────────────────────────

    private const string ToolbarActionAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>Defines a global toolbar action (e.g. ""Calculate payroll"", ""Export"").</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class ToolbarActionAttribute : System.Attribute
    {
        public string Name { get; }
        public string Label { get; set; } = """";
        public string? Icon { get; set; }
        public string Endpoint { get; set; } = """";
        public string Method { get; set; } = ""POST"";
        public string? Confirmation { get; set; }
        public string? Permission { get; set; }
        /// <summary>Selection mode: none, single, or multiple.</summary>
        public string SelectionMode { get; set; } = ""none"";
        public ToolbarActionAttribute(string name) => Name = name;
    }
}
";

    // ─── ERP: Permissions ────────────────────────────────────────────────

    private const string PermissionAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Required permission to view this form/table.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class PermissionAttribute : System.Attribute
    {
        public string Name { get; }
        public PermissionAttribute(string name) => Name = name;
    }
}
";

    private const string ColumnPermissionAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Required permission to see a specific column.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class ColumnPermissionAttribute : System.Attribute
    {
        public string Column { get; }
        public string Permission { get; }
        public ColumnPermissionAttribute(string column, string permission)
        {
            Column = column;
            Permission = permission;
        }
    }
}
";

    private const string DataFilterAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a property as a data filter scope (e.g. user can only see their own VoivodeshipId).</summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
    internal sealed class DataFilterAttribute : System.Attribute
    {
        public string PropertyName { get; }
        public DataFilterAttribute(string propertyName) => PropertyName = propertyName;
    }
}
";

    // ─── ERP: Computed columns ───────────────────────────────────────────

    private const string ComputedAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Marks a column as computed/virtual (not directly from DB).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ComputedAttribute : System.Attribute { }
}
";

    // ─── ERP: Column styling ─────────────────────────────────────────────

    private const string ColumnStyleAttributeSource = @"// <auto-generated />
namespace ZibStack.NET.UI
{
    /// <summary>Conditional styling for a column. Severity: danger, warning, success, info, muted.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true, AllowMultiple = true)]
    internal sealed class ColumnStyleAttribute : System.Attribute
    {
        public string When { get; set; } = """";
        public string Severity { get; set; } = """";
    }
}
";

    private const string ImTiredOfCrudAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.UI
{
    /// <summary>
    /// Meta-attribute: one attribute on your model generates everything.
    /// Implies [CrudApi] + [UiForm] + [UiTable] + [Validate].
    /// Explicit attributes always override. Add [UiFormField], [UiTableColumn], validation attrs etc. on properties for fine control.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false)]
    internal sealed class ImTiredOfCrudAttribute : System.Attribute
    {
        /// <summary>API route (default: api/{pluralized-name}).</summary>
        public string? Route { get; set; }

        /// <summary>Route prefix (e.g. ""v2"" → api/v2/players).</summary>
        public string? RoutePrefix { get; set; }

        /// <summary>Key property name (default: ""Id"").</summary>
        public string KeyProperty { get; set; } = ""Id"";

        /// <summary>Which CRUD operations (default: All).</summary>
        public int Operations { get; set; } = 31; // CrudOperations.All

        /// <summary>Default sort column for table and query.</summary>
        public string? DefaultSort { get; set; }

        /// <summary>Default page size for list endpoints.</summary>
        public int DefaultPageSize { get; set; } = 20;
    }
}
";
}
