using Microsoft.CodeAnalysis;

namespace ZibStack.NET.Log.Generator;

/// <summary>
/// Source generator for ZibStack.NET.Log. Handles ONLY interpolated-string logging
/// interception (<c>logger.LogInformation($"...")</c>). The [Log] aspect attribute
/// is now handled by the AOP generator in ZibStack.NET.Aop.
/// </summary>
[Generator]
public sealed class ZibLogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Optional global using for ZibStack.NET.Log
        var emitGlobalUsing = context.AnalyzerConfigOptionsProvider.Select(static (opts, _) =>
        {
            if (opts.GlobalOptions.TryGetValue("build_property.ZibLogEmitGlobalUsing", out var value)
                && bool.TryParse(value, out var parsed))
            {
                return parsed;
            }
            return false;
        });

        context.RegisterSourceOutput(emitGlobalUsing, static (spc, enabled) =>
        {
            if (!enabled) return;
            spc.AddSource("ZibStackLogGlobalUsing.g.cs",
                "// <auto-generated/>\nglobal using ZibStack.NET.Log;\n");
        });
    }
}
