using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZibStack.NET.Log.Generator;

internal static class ZibLogEmitter
{
    private static readonly string[] LogLevelNames =
    {
        "Trace", "Debug", "Information", "Warning", "Error", "Critical", "None"
    };

    public static string Emit(ClassModel classModel, IReadOnlyList<CallSiteModel> callSites)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8603 // Possible null reference return");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(classModel.Namespace))
        {
            sb.AppendLine($"using {classModel.Namespace};");
            sb.AppendLine();
        }

        // InterceptsLocation attribute (new InterceptableLocation-based API)
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace ZibStack.Generated");
        sb.AppendLine("{");
        sb.AppendLine();

        sb.AppendLine($"    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"    internal static class __{classModel.ClassName}_ZibLog");
        sb.AppendLine("    {");

        // UnsafeAccessor for logger field
        EmitUnsafeAccessor(sb, classModel);
        sb.AppendLine();

        // Emit sanitizer methods for types with [Sensitive]/[NoLog] properties
        var emittedSanitizers = new HashSet<string>();
        foreach (var method in classModel.Methods)
        {
            foreach (var param in method.Parameters)
            {
                if (param.SanitizedType != null)
                    EmitSanitizer(sb, param.SanitizedType, emittedSanitizers);
            }
            if (method.SanitizedReturnType != null)
                EmitSanitizer(sb, method.SanitizedReturnType, emittedSanitizers);
        }

        // EventId counter
        int eventId = 1;

        foreach (var method in classModel.Methods)
        {
            var methodCallSites = callSites
                .Where(cs => cs.MethodName == method.MethodName
                    && cs.ContainingClassName == classModel.ClassName)
                .ToList();

            if (methodCallSites.Count == 0)
                continue;

            // LoggerMessage.Define delegates
            EmitLogDelegates(sb, classModel, method, ref eventId);
            sb.AppendLine();

            // Interceptor method
            EmitInterceptorMethod(sb, classModel, method, methodCallSites);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitUnsafeAccessor(StringBuilder sb, ClassModel classModel)
    {
        sb.AppendLine($"        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = \"{classModel.LoggerFieldName}\")]");
        sb.AppendLine($"        private static extern ref {classModel.LoggerFieldType} __GetLogger({classModel.ClassName} @this);");
    }

    private static string GetParamLogType(ParameterModel p, int objectLogging)
    {
        if (p.IsSensitive) return "string";
        if (p.SanitizedType != null)
        {
            // Destructure: Dictionary passed as object for Serilog destructuring
            if (objectLogging == 1) return "object";
            return "string";
        }
        // In JSON mode, complex types are serialized to string
        if (objectLogging == 2 && p.IsComplexType) return "string";
        return p.FullyQualifiedType;
    }

    private static void EmitLogDelegates(StringBuilder sb, ClassModel classModel, MethodModel method, ref int eventId)
    {
        // Entry delegate
        var entryParams = GetLoggableEntryParameters(method);
        var entryTypeArgs = entryParams.Count > 0
            ? $"<{string.Join(", ", entryParams.Select(p => GetParamLogType(p, method.ObjectLogging)))}>"
            : "";
        var entryMessage = method.EntryMessage ?? BuildEntryMessage(classModel, method);

        if (entryParams.Count <= 6)
        {
            var delegateType = entryParams.Count > 0
                ? $"global::System.Action<global::Microsoft.Extensions.Logging.ILogger, {string.Join(", ", entryParams.Select(p => GetParamLogType(p, method.ObjectLogging)))}, global::System.Exception?>"
                : "global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?>";

            sb.AppendLine($"        private static readonly {delegateType} __log{method.MethodName}Entry =");
            sb.AppendLine($"            global::Microsoft.Extensions.Logging.LoggerMessage.Define{entryTypeArgs}(");
            sb.AppendLine($"                global::Microsoft.Extensions.Logging.LogLevel.{GetLogLevelName(method.EntryExitLevel)},");
            sb.AppendLine($"                new global::Microsoft.Extensions.Logging.EventId({eventId++}, \"{method.MethodName}_Entry\"),");
            sb.AppendLine($"                \"{EscapeString(entryMessage)}\");");
        }
        else
        {
            // Fallback: too many parameters for LoggerMessage.Define (max 6)
            // We'll handle this in the interceptor method directly
            eventId++;
        }

        // Exit delegate
        if (method.MeasureElapsed || (method.LogReturnValue && !method.ReturnsVoid && !method.NoLogReturn))
        {
            var exitParts = new List<string>();
            var exitTypeArgs = new List<string>();

            if (method.MeasureElapsed)
            {
                exitTypeArgs.Add("long");
            }
            if (method.LogReturnValue && !method.ReturnsVoid && !method.NoLogReturn)
            {
                // Destructure + sanitized: pass Dictionary as object for Serilog
                if (method.ObjectLogging == 1 && method.SanitizedReturnType != null)
                    exitTypeArgs.Add("object");
                else
                    exitTypeArgs.Add("string?");
            }

            var exitMessage = method.ExitMessage ?? BuildExitMessage(classModel, method);
            var exitTypeArgsStr = exitTypeArgs.Count > 0
                ? $"<{string.Join(", ", exitTypeArgs)}>"
                : "";
            var exitDelegateType = exitTypeArgs.Count > 0
                ? $"global::System.Action<global::Microsoft.Extensions.Logging.ILogger, {string.Join(", ", exitTypeArgs)}, global::System.Exception?>"
                : "global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?>";

            sb.AppendLine($"        private static readonly {exitDelegateType} __log{method.MethodName}Exit =");
            sb.AppendLine($"            global::Microsoft.Extensions.Logging.LoggerMessage.Define{exitTypeArgsStr}(");
            sb.AppendLine($"                global::Microsoft.Extensions.Logging.LogLevel.{GetLogLevelName(method.EntryExitLevel)},");
            sb.AppendLine($"                new global::Microsoft.Extensions.Logging.EventId({eventId++}, \"{method.MethodName}_Exit\"),");
            sb.AppendLine($"                \"{EscapeString(exitMessage)}\");");
        }
        else
        {
            var exitMessage = method.ExitMessage ?? $"Exited {classModel.ClassName}.{method.MethodName}";
            sb.AppendLine($"        private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?> __log{method.MethodName}Exit =");
            sb.AppendLine($"            global::Microsoft.Extensions.Logging.LoggerMessage.Define(");
            sb.AppendLine($"                global::Microsoft.Extensions.Logging.LogLevel.{GetLogLevelName(method.EntryExitLevel)},");
            sb.AppendLine($"                new global::Microsoft.Extensions.Logging.EventId({eventId++}, \"{method.MethodName}_Exit\"),");
            sb.AppendLine($"                \"{EscapeString(exitMessage)}\");");
        }

        // Error delegate
        var errorMessage = method.ExceptionMessage ?? BuildErrorMessage(classModel, method);
        if (method.MeasureElapsed)
        {
            sb.AppendLine($"        private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, long, global::System.Exception?> __log{method.MethodName}Error =");
            sb.AppendLine($"            global::Microsoft.Extensions.Logging.LoggerMessage.Define<long>(");
            sb.AppendLine($"                global::Microsoft.Extensions.Logging.LogLevel.{GetLogLevelName(method.ExceptionLevel)},");
            sb.AppendLine($"                new global::Microsoft.Extensions.Logging.EventId({eventId++}, \"{method.MethodName}_Error\"),");
            sb.AppendLine($"                \"{EscapeString(errorMessage)}\");");
        }
        else
        {
            sb.AppendLine($"        private static readonly global::System.Action<global::Microsoft.Extensions.Logging.ILogger, global::System.Exception?> __log{method.MethodName}Error =");
            sb.AppendLine($"            global::Microsoft.Extensions.Logging.LoggerMessage.Define(");
            sb.AppendLine($"                global::Microsoft.Extensions.Logging.LogLevel.{GetLogLevelName(method.ExceptionLevel)},");
            sb.AppendLine($"                new global::Microsoft.Extensions.Logging.EventId({eventId++}, \"{method.MethodName}_Error\"),");
            sb.AppendLine($"                \"{EscapeString(errorMessage)}\");");
        }
    }

    private static void EmitInterceptorMethod(
        StringBuilder sb, ClassModel classModel, MethodModel method,
        List<CallSiteModel> callSites)
    {
        // InterceptsLocation attributes (generated by InterceptableLocation API)
        foreach (var cs in callSites)
        {
            sb.AppendLine($"        {cs.InterceptsLocationAttributeSyntax}");
        }

        // Method signature
        var asyncKeyword = method.IsAsync ? "async " : "";
        var paramList = string.Join(", ",
            method.Parameters.Select(p => $"{p.FullyQualifiedType} {p.Name}"));
        var fullParamList = paramList.Length > 0
            ? $"this {classModel.ClassName} @this, {paramList}"
            : $"this {classModel.ClassName} @this";

        sb.AppendLine($"        internal static {asyncKeyword}{method.ReturnType} {method.MethodName}_ZibLog({fullParamList})");
        sb.AppendLine("        {");

        // Get logger (copy to local - ref not allowed in async methods)
        sb.AppendLine($"            var __logger = __GetLogger(@this);");
        sb.AppendLine();

        // Log entry
        var entryParams = GetLoggableEntryParameters(method);
        if (entryParams.Count <= 6)
        {
            var entryArgs = string.Join("",
                entryParams.Select(p => FormatEntryArg(p, method.ObjectLogging)));
            sb.AppendLine($"            __log{method.MethodName}Entry(__logger{entryArgs}, null);");
        }
        else
        {
            // Fallback for >6 params
            var logLevelName = GetLogLevelName(method.EntryExitLevel);
            var entryMessage = BuildEntryMessage(classModel, method);
            var entryArgsList = string.Join(", ",
                entryParams.Select(p => p.IsSensitive ? "(object)\"***\"" : $"(object){p.Name}"));
            sb.AppendLine($"            if (__logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.{logLevelName}))");
            sb.AppendLine("            {");
            sb.AppendLine($"                __logger.Log(global::Microsoft.Extensions.Logging.LogLevel.{logLevelName}, \"{EscapeString(entryMessage)}\", {entryArgsList});");
            sb.AppendLine("            }");
        }

        sb.AppendLine();

        // Stopwatch
        if (method.MeasureElapsed)
        {
            sb.AppendLine("            var __sw = global::System.Diagnostics.Stopwatch.StartNew();");
        }

        // Try block
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        // Call original method
        var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
        var originalCall = $"@this.{method.MethodName}({callArgs})";
        if (method.IsAsync)
            originalCall = $"await {originalCall}.ConfigureAwait(false)";

        if (method.ReturnsVoid && !method.IsAsync)
        {
            sb.AppendLine($"                {originalCall};");
        }
        else if (method.ReturnsVoid && method.IsAsync)
        {
            sb.AppendLine($"                {originalCall};");
        }
        else
        {
            sb.AppendLine($"                var __result = {originalCall};");
        }

        // Stop timer
        if (method.MeasureElapsed)
        {
            sb.AppendLine("                __sw.Stop();");
        }

        // Log exit
        if (method.ReturnsVoid)
        {
            if (method.MeasureElapsed)
            {
                sb.AppendLine($"                __log{method.MethodName}Exit(__logger, __sw.ElapsedMilliseconds, null);");
            }
            else
            {
                sb.AppendLine($"                __log{method.MethodName}Exit(__logger, null);");
            }
        }
        else
        {
            var exitArgs = new List<string>();
            if (method.MeasureElapsed) exitArgs.Add("__sw.ElapsedMilliseconds");
            if (method.LogReturnValue) exitArgs.Add(FormatReturnValue(method));

            if (exitArgs.Count > 0)
                sb.AppendLine($"                __log{method.MethodName}Exit(__logger, {string.Join(", ", exitArgs)}, null);");
            else
                sb.AppendLine($"                __log{method.MethodName}Exit(__logger, null);");

            sb.AppendLine("                return __result;");
        }

        sb.AppendLine("            }");

        // Catch block
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");

        if (method.MeasureElapsed)
        {
            sb.AppendLine("                __sw.Stop();");
            sb.AppendLine($"                __log{method.MethodName}Error(__logger, __sw.ElapsedMilliseconds, __ex);");
        }
        else
        {
            sb.AppendLine($"                __log{method.MethodName}Error(__logger, __ex);");
        }

        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static List<ParameterModel> GetLoggableEntryParameters(MethodModel method)
    {
        if (!method.LogParameters)
            return new List<ParameterModel>();

        return method.Parameters.Where(p => !p.IsNoLog).ToList();
    }

    private static string FormatEntryArg(ParameterModel p, int objectLogging)
    {
        if (p.IsSensitive) return ", \"***\"";
        if (p.SanitizedType != null)
        {
            // Destructure: pass Dictionary (Serilog destructures it as an object)
            if (objectLogging == 1) return $", __SanitizeDict_{p.SanitizedType.SafeName}({p.Name})";
            // JSON/ToString: pass serialized string
            return $", __Sanitize_{p.SanitizedType.SafeName}({p.Name})";
        }
        if (objectLogging == 2 && p.IsComplexType) // JSON
            return $", global::System.Text.Json.JsonSerializer.Serialize({p.Name})";
        return $", {p.Name}";
    }

    private static string FormatReturnValue(MethodModel method)
    {
        if (method.SensitiveReturn)
            return "\"***\"";
        if (method.SanitizedReturnType != null)
        {
            if (method.ObjectLogging == 1) return $"__SanitizeDict_{method.SanitizedReturnType.SafeName}(__result)";
            return $"__Sanitize_{method.SanitizedReturnType.SafeName}(__result)";
        }
        if (method.ObjectLogging == 2 && method.HasComplexReturnType) // JSON
            return $"global::System.Text.Json.JsonSerializer.Serialize(__result)";
        return "((object?)__result)?.ToString()";
    }

    private static string BuildEntryMessage(ClassModel classModel, MethodModel method)
    {
        var sb = new StringBuilder();
        sb.Append($"Entering {classModel.ClassName}.{method.MethodName}(");

        if (method.LogParameters)
        {
            var parts = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (param.IsNoLog)
                    continue;
                if (param.IsSensitive)
                    parts.Add($"{param.Name}: {{__sensitive_{param.Name}}}");
                else if (method.ObjectLogging == 1 && param.IsComplexType) // Destructure
                    parts.Add($"{param.Name}: {{@{param.Name}}}");
                else
                    parts.Add($"{param.Name}: {{{param.Name}}}");
            }
            sb.Append(string.Join(", ", parts));
        }

        sb.Append(')');
        return sb.ToString();
    }

    private static string BuildExitMessage(ClassModel classModel, MethodModel method)
    {
        var sb = new StringBuilder();
        sb.Append($"Exited {classModel.ClassName}.{method.MethodName}");

        var parts = new List<string>();
        if (method.MeasureElapsed)
            parts.Add("in {ElapsedMs}ms");
        if (method.LogReturnValue && !method.ReturnsVoid && !method.NoLogReturn)
        {
            if (method.ObjectLogging == 1 && method.HasComplexReturnType) // Destructure
                parts.Add("-> {@Result}");
            else
                parts.Add("-> {Result}");
        }

        if (parts.Count > 0)
        {
            sb.Append(" ");
            sb.Append(string.Join(" ", parts));
        }

        return sb.ToString();
    }

    private static string BuildErrorMessage(ClassModel classModel, MethodModel method)
    {
        if (method.MeasureElapsed)
            return $"{classModel.ClassName}.{method.MethodName} failed after {{ElapsedMs}}ms";
        return $"{classModel.ClassName}.{method.MethodName} failed";
    }

    private static void EmitSanitizer(StringBuilder sb, SanitizedTypeModel model, HashSet<string> emitted)
    {
        if (!emitted.Add(model.SafeName))
            return;

        // First emit sanitizers for nested types
        foreach (var prop in model.Properties)
        {
            if (prop.NestedProperties != null)
            {
                var nestedModel = new SanitizedTypeModel(prop.FullyQualifiedType,
                    prop.FullyQualifiedType
                        .Replace("global::", "").Replace(".", "_")
                        .Replace("<", "_").Replace(">", "_")
                        .Replace(",", "_").Replace(" ", ""),
                    prop.NestedProperties);
                EmitSanitizer(sb, nestedModel, emitted);
            }
        }

        // Returns Dictionary for proper JSON nesting (nested objects stay as objects, not escaped strings)
        EmitSanitizeToDict(sb, model);

        // Returns string (JSON) for use in log messages
        sb.AppendLine($"        private static string __Sanitize_{model.SafeName}({model.FullyQualifiedType} __obj)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (__obj == null) return \"null\";");
        sb.AppendLine($"            return global::System.Text.Json.JsonSerializer.Serialize(__SanitizeDict_{model.SafeName}(__obj));");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitSanitizeToDict(StringBuilder sb, SanitizedTypeModel model)
    {
        sb.AppendLine($"        private static global::System.Collections.Generic.Dictionary<string, object?> __SanitizeDict_{model.SafeName}({model.FullyQualifiedType} __obj)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var __dict = new global::System.Collections.Generic.Dictionary<string, object?>();");

        foreach (var prop in model.Properties)
        {
            if (prop.IsNoLog)
                continue;

            if (prop.IsSensitive)
            {
                sb.AppendLine($"            __dict[\"{prop.Name}\"] = \"***\";");
            }
            else if (prop.NestedProperties != null)
            {
                var nestedSafeName = prop.FullyQualifiedType
                    .Replace("global::", "").Replace(".", "_")
                    .Replace("<", "_").Replace(">", "_")
                    .Replace(",", "_").Replace(" ", "");
                sb.AppendLine($"            __dict[\"{prop.Name}\"] = __obj.{prop.Name} != null ? __SanitizeDict_{nestedSafeName}(__obj.{prop.Name}) : null;");
            }
            else
            {
                sb.AppendLine($"            __dict[\"{prop.Name}\"] = __obj.{prop.Name};");
            }
        }

        sb.AppendLine("            return __dict;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string GetLogLevelName(int level)
    {
        if (level >= 0 && level < LogLevelNames.Length)
            return LogLevelNames[level];
        return "Information";
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

}
