using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using ZibStack.NET.Aop.Generator;

namespace ZibStack.NET.Log.Generator;

/// <summary>
/// Source generator for ZibStack.NET.Log. Uses the shared AOP pipeline
/// with LogAspectEmitter for zero-overhead inline logging code generation.
/// Supports multi-aspect: [Log] can coexist with other aspects on the same method.
/// </summary>
[Generator]
public sealed class ZibLogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Optional global using for ZibStack.NET.Log — off by default so the package
        // doesn't pollute consumer namespaces or force symbol resolution on existing
        // ILogger call sites. Users opt in by setting
        //     <ZibLogEmitGlobalUsing>true</ZibLogEmitGlobalUsing>
        // in their .csproj (or <ZibLogStrict>true</ZibLogStrict>, which implies it
        // via build/.props).
        var emitGlobalUsing = context.AnalyzerConfigOptionsProvider.Select(static (opts, _) =>
        {
            if (opts.GlobalOptions.TryGetValue("build_property.ZibLogEmitGlobalUsing", out var value)
                && bool.TryParse(value, out var parsed))
            {
                return parsed;
            }
            return false;
        });

        context.RegisterSourceOutput(emitGlobalUsing, static (spc, enabled) =>
        {
            if (!enabled) return;
            spc.AddSource("ZibStackLogGlobalUsing.g.cs",
                "// <auto-generated/>\nglobal using ZibStack.NET.Log;\n");
        });

        var emitters = new Dictionary<string, IAspectEmitter>
        {
            { "ZibStack.NET.Log.LogAttribute", new LogAspectEmitter() }
        };

        var classDataProviders = new List<IClassDataProvider>
        {
            new LogClassDataProvider()
        };

        AopPipeline.Register(context, emitters, classDataProviders);
    }
}
