using ZibStack.NET.Dto;
using Xunit;

namespace ZibStack.NET.Dto.Tests;

public class DtoTargetTests
{
    // ── [DtoIgnore] (All) ─────────────────────────────────────────

    [Fact]
    public void DtoIgnore_All_ExcludedFromCreate()
        => Assert.Null(typeof(CreateDtoTargetTestModelRequest).GetProperty("InternalId"));

    [Fact]
    public void DtoIgnore_All_ExcludedFromUpdate()
        => Assert.Null(typeof(UpdateDtoTargetTestModelRequest).GetProperty("InternalId"));

    [Fact]
    public void DtoIgnore_All_ExcludedFromResponse()
        => Assert.Null(typeof(DtoTargetTestModelResponse).GetProperty("InternalId"));

    [Fact]
    public void DtoIgnore_All_ExcludedFromQuery()
        => Assert.Null(typeof(DtoTargetTestModelQuery).GetProperty("InternalId"));

    // ── [DtoIgnore(Create | Update | Query)] — keep in Response ──

    [Fact]
    public void DtoIgnore_WriteAndQuery_ExcludedFromCreate()
        => Assert.Null(typeof(CreateDtoTargetTestModelRequest).GetProperty("Id"));

    [Fact]
    public void DtoIgnore_WriteAndQuery_ExcludedFromUpdate()
        => Assert.Null(typeof(UpdateDtoTargetTestModelRequest).GetProperty("Id"));

    [Fact]
    public void DtoIgnore_WriteAndQuery_ExcludedFromQuery()
        => Assert.Null(typeof(DtoTargetTestModelQuery).GetProperty("Id"));

    [Fact]
    public void DtoIgnore_WriteAndQuery_PresentInResponse()
        => Assert.NotNull(typeof(DtoTargetTestModelResponse).GetProperty("Id"));

    // ── [DtoIgnore(Response)] ─────────────────────────────────────

    [Fact]
    public void DtoIgnore_Response_PresentInCreate()
        => Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("Secret"));

    [Fact]
    public void DtoIgnore_Response_PresentInUpdate()
        => Assert.NotNull(typeof(UpdateDtoTargetTestModelRequest).GetProperty("Secret"));

    [Fact]
    public void DtoIgnore_Response_ExcludedFromResponse()
        => Assert.Null(typeof(DtoTargetTestModelResponse).GetProperty("Secret"));

    // ── [DtoIgnore(Query)] ────────────────────────────────────────

    [Fact]
    public void DtoIgnore_Query_PresentInCreate()
        => Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("LargeBlob"));

    [Fact]
    public void DtoIgnore_Query_PresentInResponse()
        => Assert.NotNull(typeof(DtoTargetTestModelResponse).GetProperty("LargeBlob"));

    [Fact]
    public void DtoIgnore_Query_ExcludedFromQuery()
        => Assert.Null(typeof(DtoTargetTestModelQuery).GetProperty("LargeBlob"));

    // ── [DtoIgnore(Create)] ───────────────────────────────────────

    [Fact]
    public void DtoIgnore_Create_ExcludedFromCreate()
        => Assert.Null(typeof(CreateDtoTargetTestModelRequest).GetProperty("AutoGenerated"));

    [Fact]
    public void DtoIgnore_Create_PresentInUpdate()
        => Assert.NotNull(typeof(UpdateDtoTargetTestModelRequest).GetProperty("AutoGenerated"));

    [Fact]
    public void DtoIgnore_Create_PresentInResponse()
        => Assert.NotNull(typeof(DtoTargetTestModelResponse).GetProperty("AutoGenerated"));

    // ── [DtoIgnore(Update)] ───────────────────────────────────────

    [Fact]
    public void DtoIgnore_Update_PresentInCreate()
        => Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("ImmutableField"));

    [Fact]
    public void DtoIgnore_Update_ExcludedFromUpdate()
        => Assert.Null(typeof(UpdateDtoTargetTestModelRequest).GetProperty("ImmutableField"));

    [Fact]
    public void DtoIgnore_Update_PresentInResponse()
        => Assert.NotNull(typeof(DtoTargetTestModelResponse).GetProperty("ImmutableField"));

    // ── [DtoOnly(Create)] ─────────────────────────────────────────

    [Fact]
    public void DtoOnly_Create_PresentInCreate()
        => Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("SetupKey"));

    [Fact]
    public void DtoOnly_Create_ExcludedFromUpdate()
        => Assert.Null(typeof(UpdateDtoTargetTestModelRequest).GetProperty("SetupKey"));

    [Fact]
    public void DtoOnly_Create_ExcludedFromResponse()
        => Assert.Null(typeof(DtoTargetTestModelResponse).GetProperty("SetupKey"));

    [Fact]
    public void DtoOnly_Create_ExcludedFromQuery()
        => Assert.Null(typeof(DtoTargetTestModelQuery).GetProperty("SetupKey"));

    // ── [DtoOnly(Update)] ─────────────────────────────────────────

    [Fact]
    public void DtoOnly_Update_ExcludedFromCreate()
        => Assert.Null(typeof(CreateDtoTargetTestModelRequest).GetProperty("RetireReason"));

    [Fact]
    public void DtoOnly_Update_PresentInUpdate()
        => Assert.NotNull(typeof(UpdateDtoTargetTestModelRequest).GetProperty("RetireReason"));

    [Fact]
    public void DtoOnly_Update_ExcludedFromResponse()
        => Assert.Null(typeof(DtoTargetTestModelResponse).GetProperty("RetireReason"));

    // ── [DtoOnly(Create | Update)] ────────────────────────────────

    [Fact]
    public void DtoOnly_CreateUpdate_PresentInCreate()
        => Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("WriteOnlyField"));

    [Fact]
    public void DtoOnly_CreateUpdate_PresentInUpdate()
        => Assert.NotNull(typeof(UpdateDtoTargetTestModelRequest).GetProperty("WriteOnlyField"));

    [Fact]
    public void DtoOnly_CreateUpdate_ExcludedFromResponse()
        => Assert.Null(typeof(DtoTargetTestModelResponse).GetProperty("WriteOnlyField"));

    [Fact]
    public void DtoOnly_CreateUpdate_ExcludedFromQuery()
        => Assert.Null(typeof(DtoTargetTestModelQuery).GetProperty("WriteOnlyField"));

    // ── No restrictions ───────────────────────────────────────────

    [Fact]
    public void NoRestrictions_PresentEverywhere()
    {
        Assert.NotNull(typeof(CreateDtoTargetTestModelRequest).GetProperty("Name"));
        Assert.NotNull(typeof(UpdateDtoTargetTestModelRequest).GetProperty("Name"));
        Assert.NotNull(typeof(DtoTargetTestModelResponse).GetProperty("Name"));
        Assert.NotNull(typeof(DtoTargetTestModelQuery).GetProperty("Name"));
    }
}
