using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.Validation;

[Generator]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string ZValidateAttributeFqn = "ZibStack.NET.Validation.ZValidateAttribute";

    private const string ZValidateAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Generates a compile-time <see cref=""IValidatable.Validate""/> method from validation
    /// attributes (<see cref=""ZRequiredAttribute""/>, <see cref=""ZRangeAttribute""/>, etc.)
    /// and optional fluent rules via <see cref=""IValidationConfigurator{T}""/>.
    /// <para>No reflection, no runtime overhead — validation code is emitted by the source generator.</para>
    /// <para>Supports nested object/collection validation and cross-field rules.</para>
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class ZValidateAttribute : System.Attribute { }
}
";

    private const string ValidationResultSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Result of a validation operation.</summary>
    public sealed class ValidationResult
    {
        public static readonly ValidationResult Success = new(System.Array.Empty<string>());

        public System.Collections.Generic.IReadOnlyList<string> Errors { get; }
        public bool IsValid => Errors.Count == 0;

        public ValidationResult(System.Collections.Generic.IReadOnlyList<string> errors)
        {
            Errors = errors;
        }
    }

    /// <summary>Interface implemented by all [ZValidate]-decorated types.</summary>
    public interface IValidatable
    {
        ValidationResult Validate(ValidationContext? context = null);
    }

    /// <summary>
    /// Runtime context passed through the validation chain. Carries parent reference,
    /// property path, root object, and a user-data bag.
    /// </summary>
    public sealed class ValidationContext
    {
        /// <summary>The object that triggered this nested validation.</summary>
        public object? Parent { get; set; }

        /// <summary>Dot-separated path from root (e.g. ""Order.Address.City"").</summary>
        public string Path { get; set; } = """";

        /// <summary>The top-level object that started the validation chain.</summary>
        public object? RootObject { get; set; }

        /// <summary>User-defined key-value bag for custom data.</summary>
        public System.Collections.Generic.Dictionary<string, object?> Items { get; } = new();

        internal ValidationContext ForNested(object parent, string propertyName)
        {
            var ctx = new ValidationContext
            {
                Parent = parent,
                Path = string.IsNullOrEmpty(Path) ? propertyName : Path + ""."" + propertyName,
                RootObject = RootObject ?? parent,
            };
            foreach (var kv in Items) ctx.Items[kv.Key] = kv.Value;
            return ctx;
        }
    }
}
";

    // Attribute sources for custom rules
    private const string ZRequiredAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Property must not be null (or empty/whitespace for strings).
    /// Fluent equivalent: <c>b.Property(x => x.Prop).Required()</c> via <see cref=""IValidationConfigurator{T}""/>.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRequiredAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZMinLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at least this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMinLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMinLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZMaxLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at most this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMaxLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMaxLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZRangeAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Numeric value must be within the specified range (inclusive).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRangeAttribute : System.Attribute
    {
        public double Min { get; }
        public double Max { get; }
        public string? Message { get; set; }
        public ZRangeAttribute(double min, double max) { Min = min; Max = max; }
    }
}
";

    private const string ZEmailAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid email address.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZEmailAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZUrlAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid URL.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZUrlAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string RegexAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must match the specified regex pattern.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMatchAttribute : System.Attribute
    {
        public string Pattern { get; }
        public string? Message { get; set; }
        public ZMatchAttribute(string pattern) => Pattern = pattern;
    }
}
";

    private const string ZNotEmptyAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Collection must contain at least one element. String must not be empty or whitespace.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZNotEmptyAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string CrossFieldInterfacesSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>
    /// Implement on a <c>[ZValidate]</c> class to define validation rules via fluent DSL.
    /// The generator parses <see cref=""Configure""/> at compile time — it is never invoked at runtime.
    /// <code>
    /// [ZValidate]
    /// public partial class MyForm : IValidationConfigurator&lt;MyForm&gt;
    /// {
    ///     public string Email { get; set; } = """";
    ///     public DateTime Start { get; set; }
    ///     public DateTime End { get; set; }
    ///
    ///     public void Configure(IValidationBuilder&lt;MyForm&gt; b)
    ///     {
    ///         b.Property(x => x.Email).Required().Email();
    ///         b.Rule(x => x.End > x.Start, ""End must be after Start"");
    ///     }
    /// }
    /// </code>
    /// </summary>
    public interface IValidationConfigurator<T>
    {
        /// <summary>Define validation rules for <typeparamref name=""T""/>. Parsed at compile time.</summary>
        void Configure(IValidationBuilder<T> b);
    }

    /// <summary>
    /// Fluent builder for validation rules. Supports per-property rules and cross-field expressions.
    /// </summary>
    public interface IValidationBuilder<T>
    {
        /// <summary>
        /// Add a cross-field rule with a predicate expression. Any valid C# expression works.
        /// <code>b.Rule(x => x.EndDate > x.StartDate, ""EndDate must be after StartDate"");</code>
        /// </summary>
        IValidationBuilder<T> Rule(System.Linq.Expressions.Expression<System.Func<T, bool>> predicate, string message);

        /// <summary>
        /// Begin a per-property rule chain. Supports both single-property rules and cross-field comparisons.
        /// <code>b.Property(x => x.Email).Required().Email();</code>
        /// </summary>
        IPropertyValidationBuilder<T> Property(System.Linq.Expressions.Expression<System.Func<T, object?>> selector);
    }

    /// <summary>
    /// Per-property validation builder. Chain rules fluently — each returns the builder for further chaining.
    /// </summary>
    public interface IPropertyValidationBuilder<T>
    {
        // ── Single-property rules (equivalent to [Z*] attributes) ───────

        /// <summary>Property must not be null (or empty/whitespace for strings). Equivalent to <c>[ZRequired]</c>.</summary>
        IPropertyValidationBuilder<T> Required(string? message = null);

        /// <summary>String/collection must have at least <paramref name=""length""/> characters/items. Equivalent to <c>[ZMinLength]</c>.</summary>
        IPropertyValidationBuilder<T> MinLength(int length, string? message = null);

        /// <summary>String/collection must have at most <paramref name=""length""/> characters/items. Equivalent to <c>[ZMaxLength]</c>.</summary>
        IPropertyValidationBuilder<T> MaxLength(int length, string? message = null);

        /// <summary>Numeric value must be within range (inclusive). Equivalent to <c>[ZRange]</c>.</summary>
        IPropertyValidationBuilder<T> Range(double min, double max, string? message = null);

        /// <summary>Must be a valid email address. Equivalent to <c>[ZEmail]</c>.</summary>
        IPropertyValidationBuilder<T> Email(string? message = null);

        /// <summary>Must be a valid absolute URL. Equivalent to <c>[ZUrl]</c>.</summary>
        IPropertyValidationBuilder<T> Url(string? message = null);

        /// <summary>Must match the regex <paramref name=""pattern""/>. Equivalent to <c>[ZMatch]</c>.</summary>
        IPropertyValidationBuilder<T> Match(string pattern, string? message = null);

        /// <summary>Collection must have items; string must not be whitespace. Equivalent to <c>[ZNotEmpty]</c>.</summary>
        IPropertyValidationBuilder<T> NotEmpty(string? message = null);

        // ── Cross-field comparisons ─────────────────────────────────────

        /// <summary>This property must be greater than <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> GreaterThan(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>This property must be greater than or equal to <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> GreaterThanOrEqual(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>This property must be less than <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> LessThan(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>This property must be less than or equal to <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> LessThanOrEqual(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>This property must equal <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> EqualTo(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>This property must not equal <paramref name=""other""/>.</summary>
        IPropertyValidationBuilder<T> NotEqualTo(System.Linq.Expressions.Expression<System.Func<T, object?>> other, string? message = null);

        /// <summary>Start a new property chain.</summary>
        IPropertyValidationBuilder<T> Property(System.Linq.Expressions.Expression<System.Func<T, object?>> selector);
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("ZValidateAttribute.g.cs", ZValidateAttributeSource);
            ctx.AddSource("ValidationResult.g.cs", ValidationResultSource);
            ctx.AddSource("ZRequiredAttribute.g.cs", ZRequiredAttributeSource);
            ctx.AddSource("ZMinLengthAttribute.g.cs", ZMinLengthAttributeSource);
            ctx.AddSource("ZMaxLengthAttribute.g.cs", ZMaxLengthAttributeSource);
            ctx.AddSource("ZRangeAttribute.g.cs", ZRangeAttributeSource);
            ctx.AddSource("ZEmailAttribute.g.cs", ZEmailAttributeSource);
            ctx.AddSource("ZUrlAttribute.g.cs", ZUrlAttributeSource);
            ctx.AddSource("ZMatchAttribute.g.cs", RegexAttributeSource);
            ctx.AddSource("ZNotEmptyAttribute.g.cs", ZNotEmptyAttributeSource);
            ctx.AddSource("IValidationConfigurator.g.cs", CrossFieldInterfacesSource);
        });

        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ZValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => ExtractValidationInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(targets, static (spc, info) =>
        {
            var source = GenerateValidation(info);
            spc.AddSource($"{info.HintName}.Validation.g.cs", source);

            if (info.IsPartial)
                spc.AddSource($"{info.HintName}.Validation.CodeMap.g.cs", GenerateCodeMap(info));
        });

        // [ImTiredOfCrud] (from ZibStack.NET.UI) → implies [ZValidate]
        var modelTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ZibStack.NET.UI.ImTiredOfCrudAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    // Skip if explicit [ZValidate] exists
                    var hasValidate = ((INamedTypeSymbol)ctx.TargetSymbol).GetAttributes()
                        .Any(a => a.AttributeClass?.ToDisplayString() == ZValidateAttributeFqn);
                    return hasValidate ? null : ExtractValidationInfo(ctx);
                })
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(modelTargets, static (spc, info) =>
        {
            var source = GenerateValidation(info);
            spc.AddSource($"{info.HintName}.Validation.Model.g.cs", source);

            if (info.IsPartial)
                spc.AddSource($"{info.HintName}.Validation.Model.CodeMap.g.cs", GenerateCodeMap(info));
        });
    }

    private static ValidationInfo? ExtractValidationInfo(GeneratorAttributeSyntaxContext context)
    {
        try
        {
            var symbol = (INamedTypeSymbol)context.TargetSymbol;
            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var isRecord = context.TargetNode is RecordDeclarationSyntax;
            var isStruct = context.TargetNode is StructDeclarationSyntax;

            var properties = new List<PropertyValidationInfo>();
            var nestedProps = new List<NestedValidatableInfo>();

            foreach (var member in symbol.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.DeclaredAccessibility != Accessibility.Public) continue;
                if (prop.GetMethod is null) continue;

                var rules = new List<ValidationRule>();
                var isNullableRef = prop.Type.NullableAnnotation == NullableAnnotation.Annotated;
                var isValueType = prop.Type.IsValueType;
                var typeName = prop.Type.ToDisplayString();

                foreach (var attr in prop.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.ToDisplayString();
                    if (attrName is null) continue;

                    var customMessage = attr.NamedArguments
                        .FirstOrDefault(a => a.Key == "Message").Value.Value as string;

                    switch (attrName)
                    {
                        case "ZibStack.NET.Validation.ZRequiredAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Required, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZMinLengthAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int minLen)
                                rules.Add(new ValidationRule(ValidationRuleKind.MinLength, customMessage, minValue: minLen));
                            break;

                        case "ZibStack.NET.Validation.ZMaxLengthAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int maxLen)
                                rules.Add(new ValidationRule(ValidationRuleKind.MaxLength, customMessage, maxValue: maxLen));
                            break;

                        case "ZibStack.NET.Validation.ZRangeAttribute":
                            if (attr.ConstructorArguments.Length >= 2)
                            {
                                var min = attr.ConstructorArguments[0].Value is double dmin ? dmin : 0;
                                var max = attr.ConstructorArguments[1].Value is double dmax ? dmax : 0;
                                rules.Add(new ValidationRule(ValidationRuleKind.Range, customMessage, minValue: min, maxValue: max));
                            }
                            break;

                        case "ZibStack.NET.Validation.ZEmailAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Email, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZUrlAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Url, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZMatchAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string pattern)
                                rules.Add(new ValidationRule(ValidationRuleKind.Match, customMessage, pattern: pattern));
                            break;

                        case "ZibStack.NET.Validation.ZNotEmptyAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.NotEmpty, customMessage));
                            break;
                    }
                }

                if (rules.Count > 0)
                {
                    properties.Add(new PropertyValidationInfo(
                        prop.Name, typeName, isNullableRef, isValueType, rules));
                }

                // Check if property type is IValidatable (has [ZValidate] or Configure method)
                var propType = prop.Type;
                if (propType.NullableAnnotation == NullableAnnotation.Annotated && propType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
                    propType = nts.TypeArguments[0]; // unwrap Nullable<T>

                // Check for collection: IEnumerable<T> where T is validatable
                var elementType = GetCollectionElementType(propType);
                var typeToCheck = elementType ?? propType;

                if (typeToCheck is INamedTypeSymbol namedCheck)
                {
                    bool isValidatable = namedCheck.GetAttributes()
                        .Any(a => a.AttributeClass?.ToDisplayString() == ZValidateAttributeFqn);
                    if (!isValidatable)
                        isValidatable = namedCheck.GetMembers().OfType<IMethodSymbol>()
                            .Any(m => m.Name == "Configure" && m.Parameters.Length == 1
                                && m.Parameters[0].Type.Name == "IValidationBuilder");
                    if (isValidatable)
                    {
                        nestedProps.Add(new NestedValidatableInfo
                        {
                            PropertyName = prop.Name,
                            IsNullable = isNullableRef || prop.Type.NullableAnnotation == NullableAnnotation.Annotated,
                            IsCollection = elementType != null,
                        });
                    }
                }
            }

            // Parse cross-field rules from Configure(IValidationBuilder<T>) method.
            // PostInit types (IValidationConfigurator, IValidationBuilder) aren't in
            // the semantic model yet, so we use syntax-only lookup: find a method named
            // "Configure" whose parameter type name contains "IValidationBuilder".
            var crossFieldRules = new List<CrossFieldRule>();
            if (context.TargetNode is TypeDeclarationSyntax tds)
            {
                foreach (var member in tds.Members)
                {
                    if (member is MethodDeclarationSyntax methodSyntax
                        && methodSyntax.Identifier.Text == "Configure"
                        && methodSyntax.Body is not null)
                    {
                        // Pass symbol so fluent rules can look up property types
                        ParseCrossFieldRules(methodSyntax.Body, context.SemanticModel, crossFieldRules, properties, symbol);
                        break;
                    }
                }
            }

            if (properties.Count == 0 && crossFieldRules.Count == 0 && nestedProps.Count == 0) return null;

            var hintName = symbol.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_");

            bool isPartial = symbol.DeclaringSyntaxReferences
                .Any(r => r.GetSyntax() is TypeDeclarationSyntax tds
                    && tds.Modifiers.Any(SyntaxKind.PartialKeyword));

            var info = new ValidationInfo(
                symbol.Name, ns, hintName, isRecord, properties, isPartial);
            info.CrossFieldRules.AddRange(crossFieldRules);
            info.NestedProperties.AddRange(nestedProps);
            return info;
        }
        catch
        {
            return null;
        }
    }

    private static string GenerateValidation(ValidationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Validation for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Validation;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName} : IValidatable");
        sb.AppendLine("{");
        sb.AppendLine("    public ValidationResult Validate(ValidationContext? context = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        context ??= new ValidationContext { RootObject = this };");
        sb.AppendLine("        var errors = new List<string>();");
        sb.AppendLine();

        foreach (var prop in info.Properties)
        {
            foreach (var rule in prop.Rules)
            {
                EmitRule(sb, prop, rule);
            }
        }

        // Nested IValidatable properties
        if (info.NestedProperties.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Nested validation");
            EmitNestedValidation(sb, info);
        }

        // Cross-field rules from IValidationConfigurator<T>
        if (info.CrossFieldRules.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Cross-field rules");
            EmitCrossFieldRules(sb, info);
        }

        sb.AppendLine();
        sb.AppendLine("        return errors.Count == 0 ? ValidationResult.Success : new ValidationResult(errors);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCodeMap(ValidationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated code map for <c>{info.ClassName}</c> (Validation):");
        sb.AppendLine("/// <list type=\"bullet\">");
        sb.AppendLine($"/// <item><description>Validate() method — compile-time validation from attributes</description></item>");
        sb.AppendLine($"/// <item><description>Implements <see cref=\"IValidatable\"/></description></item>");
        sb.AppendLine("/// </list>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"partial {keyword} {info.ClassName} {{ }}");

        return sb.ToString();
    }

    private static void EmitRule(StringBuilder sb, PropertyValidationInfo prop, ValidationRule rule)
    {
        var name = prop.PropertyName;
        var displayName = prop.PropertyName;

        switch (rule.Kind)
        {
            case ValidationRuleKind.Required:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is required.";
                if (prop.IsValueType)
                {
                    // For nullable value types
                    if (prop.TypeName.EndsWith("?"))
                        sb.AppendLine($"        if ({name} is null) errors.Add(\"{EscapeString(msg)}\");");
                }
                else
                {
                    sb.AppendLine($"        if ({name} is null) errors.Add(\"{EscapeString(msg)}\");");
                    if (prop.TypeName == "string" || prop.TypeName == "string?")
                        sb.AppendLine($"        else if (string.IsNullOrWhiteSpace({name})) errors.Add(\"{EscapeString(msg)}\");");
                }
                break;
            }

            case ValidationRuleKind.MinLength:
            {
                var len = (int)rule.MinValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at least {len} characters.";
                sb.AppendLine($"        if ({name} is not null && {name}.Length < {len}) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.MaxLength:
            {
                var len = (int)rule.MaxValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at most {len} characters.";
                sb.AppendLine($"        if ({name} is not null && {name}.Length > {len}) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Range:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be between {rule.MinValue} and {rule.MaxValue}.";
                if (prop.IsNullableRef || prop.TypeName.EndsWith("?"))
                {
                    sb.AppendLine($"        if ({name} is not null && ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue})) errors.Add(\"{EscapeString(msg)}\");");
                }
                else
                {
                    sb.AppendLine($"        if ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue}) errors.Add(\"{EscapeString(msg)}\");");
                }
                break;
            }

            case ValidationRuleKind.Email:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid email address.";
                sb.AppendLine($"        if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\")) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Url:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid URL.";
                sb.AppendLine($"        if ({name} is not null && !System.Uri.TryCreate({name}, System.UriKind.Absolute, out _)) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Match:
            {
                var msg = rule.CustomMessage ?? $"{displayName} does not match the required pattern.";
                sb.AppendLine($"        if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"{rule.Pattern!.Replace("\"", "\"\"")}\")) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.NotEmpty:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must not be empty.";
                if (prop.TypeName == "string" || prop.TypeName == "string?")
                    sb.AppendLine($"        if ({name} is not null && string.IsNullOrWhiteSpace({name})) errors.Add(\"{EscapeString(msg)}\");");
                else
                    sb.AppendLine($"        if ({name} is not null && ((System.Collections.ICollection){name}).Count == 0) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }
        }
    }

    private static void EmitCrossFieldRules(StringBuilder sb, ValidationInfo info)
    {
        foreach (var rule in info.CrossFieldRules)
        {
            var msg = EscapeString(rule.Message);
            switch (rule.Kind)
            {
                case CrossFieldRuleKind.Expression:
                    sb.AppendLine($"        if (!({rule.ExpressionText})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.GreaterThan:
                    sb.AppendLine($"        if (!({rule.LeftProperty} > {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.GreaterThanOrEqual:
                    sb.AppendLine($"        if (!({rule.LeftProperty} >= {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.LessThan:
                    sb.AppendLine($"        if (!({rule.LeftProperty} < {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.LessThanOrEqual:
                    sb.AppendLine($"        if (!({rule.LeftProperty} <= {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.EqualTo:
                    sb.AppendLine($"        if (!object.Equals({rule.LeftProperty}, {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
                case CrossFieldRuleKind.NotEqualTo:
                    sb.AppendLine($"        if (object.Equals({rule.LeftProperty}, {rule.RightProperty})) errors.Add(\"{msg}\");");
                    break;
            }
        }
    }

    /// <summary>
    /// Parses cross-field rules from IValidationConfigurator.Configure() body.
    /// Supports b.Rule(x => expr, "msg") and b.Property(x => x.Prop).GreaterThan(x => x.Other).
    /// </summary>
    private static void ParseCrossFieldRules(BlockSyntax body, SemanticModel sm, List<CrossFieldRule> rules, List<PropertyValidationInfo>? fluentProperties = null, INamedTypeSymbol? typeSymbol = null)
    {
        foreach (var stmt in body.Statements)
        {
            if (stmt is not ExpressionStatementSyntax es) continue;

            // Unwrap the call chain
            var expr = es.Expression;

            // Try b.Rule(x => ..., "msg")
            if (expr is InvocationExpressionSyntax ruleInv
                && ruleInv.Expression is MemberAccessExpressionSyntax ruleMae
                && ruleMae.Name.Identifier.Text == "Rule"
                && ruleInv.ArgumentList.Arguments.Count == 2)
            {
                var lambdaArg = ruleInv.ArgumentList.Arguments[0].Expression;
                var msgArg = ruleInv.ArgumentList.Arguments[1].Expression;
                var msgVal = sm.GetConstantValue(msgArg);
                if (msgVal.HasValue && msgVal.Value is string msg && lambdaArg is SimpleLambdaExpressionSyntax lambda)
                {
                    var paramName = lambda.Parameter.Identifier.Text;
                    var exprText = lambda.Body.ToString();
                    // Replace parameter references (x.Prop → Prop) for use inside the class
                    exprText = System.Text.RegularExpressions.Regex.Replace(
                        exprText, $@"\b{paramName}\.", "");
                    rules.Add(new CrossFieldRule
                    {
                        Kind = CrossFieldRuleKind.Expression,
                        ExpressionText = exprText,
                        Message = msg,
                    });
                }
                continue;
            }

            // Try b.Property(x => x.Left).GreaterThan(x => x.Right, "msg")
            // Walk the chain from outermost to innermost
            ParsePropertyChain(expr, sm, rules, fluentProperties, typeSymbol);
        }
    }

    private static void ParsePropertyChain(ExpressionSyntax expr, SemanticModel sm, List<CrossFieldRule> rules, List<PropertyValidationInfo>? fluentProperties = null, INamedTypeSymbol? typeSymbol = null)
    {
        // Collect chain calls in order
        var calls = new List<(string Method, InvocationExpressionSyntax Inv)>();
        var current = expr;
        while (current is InvocationExpressionSyntax inv
               && inv.Expression is MemberAccessExpressionSyntax mae)
        {
            calls.Add((mae.Name.Identifier.Text, inv));
            current = mae.Expression;
        }

        // Reverse: innermost call (Property) first, then comparisons
        calls.Reverse();
        string? leftProp = null;
        foreach (var (method, inv) in calls)
        {
            if (method == "Property" && inv.ArgumentList.Arguments.Count >= 1)
            {
                leftProp = ExtractPropertyName(inv.ArgumentList.Arguments[0].Expression);
            }
            else if (leftProp != null && IsComparisonMethod(method) && inv.ArgumentList.Arguments.Count >= 1)
            {
                var rightProp = ExtractPropertyName(inv.ArgumentList.Arguments[0].Expression);
                if (rightProp == null) continue;

                string? msg = null;
                if (inv.ArgumentList.Arguments.Count >= 2)
                {
                    var msgVal = sm.GetConstantValue(inv.ArgumentList.Arguments[1].Expression);
                    if (msgVal.HasValue) msg = msgVal.Value as string;
                }
                msg ??= $"{leftProp} must be {FormatComparison(method)} {rightProp}.";

                rules.Add(new CrossFieldRule
                {
                    Kind = method switch
                    {
                        "GreaterThan" => CrossFieldRuleKind.GreaterThan,
                        "GreaterThanOrEqual" => CrossFieldRuleKind.GreaterThanOrEqual,
                        "LessThan" => CrossFieldRuleKind.LessThan,
                        "LessThanOrEqual" => CrossFieldRuleKind.LessThanOrEqual,
                        "EqualTo" => CrossFieldRuleKind.EqualTo,
                        "NotEqualTo" => CrossFieldRuleKind.NotEqualTo,
                        _ => CrossFieldRuleKind.Expression,
                    },
                    LeftProperty = leftProp,
                    RightProperty = rightProp,
                    Message = msg,
                });
            }
            else if (leftProp != null && IsFluentValidationMethod(method) && fluentProperties != null)
            {
                // Per-property fluent rules: .Required(), .Email(), .MinLength(n), etc.
                string? msg = null;
                var args = inv.ArgumentList.Arguments;

                ValidationRule? rule = method switch
                {
                    "Required" => new ValidationRule(ValidationRuleKind.Required, GetOptionalMessage(args, 0, sm)),
                    "Email" => new ValidationRule(ValidationRuleKind.Email, GetOptionalMessage(args, 0, sm)),
                    "Url" => new ValidationRule(ValidationRuleKind.Url, GetOptionalMessage(args, 0, sm)),
                    "NotEmpty" => new ValidationRule(ValidationRuleKind.NotEmpty, GetOptionalMessage(args, 0, sm)),
                    "MinLength" when args.Count >= 1 && sm.GetConstantValue(args[0].Expression) is { HasValue: true, Value: int minLen }
                        => new ValidationRule(ValidationRuleKind.MinLength, GetOptionalMessage(args, 1, sm), minValue: minLen),
                    "MaxLength" when args.Count >= 1 && sm.GetConstantValue(args[0].Expression) is { HasValue: true, Value: int maxLen }
                        => new ValidationRule(ValidationRuleKind.MaxLength, GetOptionalMessage(args, 1, sm), maxValue: maxLen),
                    "Range" when args.Count >= 2
                        && sm.GetConstantValue(args[0].Expression) is { HasValue: true, Value: var minV }
                        && sm.GetConstantValue(args[1].Expression) is { HasValue: true, Value: var maxV }
                        => new ValidationRule(ValidationRuleKind.Range, GetOptionalMessage(args, 2, sm),
                            minValue: System.Convert.ToDouble(minV), maxValue: System.Convert.ToDouble(maxV)),
                    "Match" when args.Count >= 1 && sm.GetConstantValue(args[0].Expression) is { HasValue: true, Value: string pattern }
                        => new ValidationRule(ValidationRuleKind.Match, GetOptionalMessage(args, 1, sm), pattern: pattern),
                    _ => null,
                };

                if (rule != null)
                {
                    // Find or create PropertyValidationInfo for this property
                    var existing = fluentProperties.Find(p => p.PropertyName == leftProp);
                    if (existing != null)
                    {
                        existing.Rules.Add(rule);
                    }
                    else
                    {
                        // Look up actual property type from symbol
                        var propSymbol = typeSymbol?.GetMembers(leftProp).OfType<IPropertySymbol>().FirstOrDefault();
                        var typeName = propSymbol?.Type.ToDisplayString() ?? "object";
                        var isNullable = propSymbol?.Type.NullableAnnotation == NullableAnnotation.Annotated;
                        var isValue = propSymbol?.Type.IsValueType ?? false;
                        var propInfo = new PropertyValidationInfo(leftProp, typeName, isNullable, isValue, new List<ValidationRule> { rule });
                        fluentProperties.Add(propInfo);
                    }
                }
            }
        }
    }

    private static string? GetOptionalMessage(SeparatedSyntaxList<ArgumentSyntax> args, int index, SemanticModel sm)
    {
        if (args.Count <= index) return null;
        var cv = sm.GetConstantValue(args[index].Expression);
        return cv.HasValue ? cv.Value as string : null;
    }

    private static bool IsFluentValidationMethod(string name)
        => name is "Required" or "Email" or "Url" or "NotEmpty" or "MinLength" or "MaxLength" or "Range" or "Match";

    private static string? ExtractPropertyName(ExpressionSyntax expr)
    {
        if (expr is not SimpleLambdaExpressionSyntax lambda) return null;
        if (lambda.Body is MemberAccessExpressionSyntax mae)
            return mae.Name.Identifier.Text;
        return null;
    }

    private static bool IsComparisonMethod(string name)
        => name is "GreaterThan" or "GreaterThanOrEqual" or "LessThan" or "LessThanOrEqual" or "EqualTo" or "NotEqualTo";

    private static string FormatComparison(string method) => method switch
    {
        "GreaterThan" => "greater than",
        "GreaterThanOrEqual" => "greater than or equal to",
        "LessThan" => "less than",
        "LessThanOrEqual" => "less than or equal to",
        "EqualTo" => "equal to",
        "NotEqualTo" => "not equal to",
        _ => method,
    };

    private static void EmitNestedValidation(StringBuilder sb, ValidationInfo info)
    {
        for (int i = 0; i < info.NestedProperties.Count; i++)
        {
            var nested = info.NestedProperties[i];
            if (nested.IsCollection)
            {
                if (nested.IsNullable)
                    sb.AppendLine($"        if ({nested.PropertyName} is not null)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var __idx{i} = 0;");
                sb.AppendLine($"            foreach (var __item{i} in {nested.PropertyName})");
                sb.AppendLine($"            {{");
                sb.AppendLine($"                if (__item{i} is IValidatable __v{i})");
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    var __nested{i} = __v{i}.Validate(context.ForNested(this, \"{nested.PropertyName}[\" + __idx{i} + \"]\"));");
                sb.AppendLine($"                    if (!__nested{i}.IsValid)");
                sb.AppendLine($"                        foreach (var __e in __nested{i}.Errors) errors.Add(\"{nested.PropertyName}[\" + __idx{i} + \"].\" + __e);");
                sb.AppendLine($"                }}");
                sb.AppendLine($"                __idx{i}++;");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        if ({nested.PropertyName} is IValidatable __v{i})");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            var __nested{i} = __v{i}.Validate(context.ForNested(this, \"{nested.PropertyName}\"));");
                sb.AppendLine($"            if (!__nested{i}.IsValid)");
                sb.AppendLine($"                foreach (var __e in __nested{i}.Errors) errors.Add(\"{nested.PropertyName}.\" + __e);");
                sb.AppendLine($"        }}");
            }
        }
    }

    private static ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
            return array.ElementType;
        if (type is INamedTypeSymbol named)
        {
            // Check IEnumerable<T>, List<T>, ICollection<T>, etc.
            foreach (var iface in named.AllInterfaces)
            {
                if (iface.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"
                    && iface.TypeArguments.Length == 1)
                    return iface.TypeArguments[0];
            }
            // Also check if the type itself is generic IEnumerable
            if (named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"
                && named.TypeArguments.Length == 1)
                return named.TypeArguments[0];
        }
        return null;
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

// ─── Models ───────────────────────────────────────────────────────────

internal enum ValidationRuleKind
{
    Required,
    MinLength,
    MaxLength,
    Range,
    Email,
    Url,
    Match,
    NotEmpty,
}

internal sealed class ValidationRule
{
    public ValidationRuleKind Kind { get; }
    public string? CustomMessage { get; }
    public double MinValue { get; }
    public double MaxValue { get; }
    public string? Pattern { get; }

    public ValidationRule(ValidationRuleKind kind, string? customMessage = null, double minValue = 0, double maxValue = 0, string? pattern = null)
    {
        Kind = kind;
        CustomMessage = customMessage;
        MinValue = minValue;
        MaxValue = maxValue;
        Pattern = pattern;
    }
}

internal sealed class PropertyValidationInfo
{
    public string PropertyName { get; }
    public string TypeName { get; }
    public bool IsNullableRef { get; }
    public bool IsValueType { get; }
    public List<ValidationRule> Rules { get; }

    public PropertyValidationInfo(string propertyName, string typeName, bool isNullableRef, bool isValueType, List<ValidationRule> rules)
    {
        PropertyName = propertyName;
        TypeName = typeName;
        IsNullableRef = isNullableRef;
        IsValueType = isValueType;
        Rules = rules;
    }
}

internal sealed class ValidationInfo
{
    public string ClassName { get; }
    public string? Namespace { get; }
    public string HintName { get; }
    public bool IsRecord { get; }
    public bool IsPartial { get; }
    public List<PropertyValidationInfo> Properties { get; }

    public List<CrossFieldRule> CrossFieldRules { get; } = new();
    public List<NestedValidatableInfo> NestedProperties { get; } = new();

    public ValidationInfo(string className, string? ns, string hintName, bool isRecord, List<PropertyValidationInfo> properties, bool isPartial = false)
    {
        ClassName = className;
        Namespace = ns;
        HintName = hintName;
        IsRecord = isRecord;
        IsPartial = isPartial;
        Properties = properties;
    }
}

internal enum CrossFieldRuleKind
{
    /// <summary>Free-form expression: b.Rule(x => x.End > x.Start, "msg")</summary>
    Expression,
    /// <summary>Property comparison: b.Property(x => x.End).GreaterThan(x => x.Start)</summary>
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    EqualTo,
    NotEqualTo,
}

internal sealed class NestedValidatableInfo
{
    public string PropertyName { get; set; } = "";
    public bool IsNullable { get; set; }
    public bool IsCollection { get; set; }
}

internal sealed class CrossFieldRule
{
    public CrossFieldRuleKind Kind { get; set; }
    public string Message { get; set; } = "";
    /// <summary>For Expression kind: the raw C# expression text (e.g. "EndDate > StartDate").</summary>
    public string? ExpressionText { get; set; }
    /// <summary>For comparison kinds: left property name.</summary>
    public string? LeftProperty { get; set; }
    /// <summary>For comparison kinds: right property name.</summary>
    public string? RightProperty { get; set; }
}
