using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ZibStack.NET.Validation;

[Generator]
public sealed class ValidationGenerator : IIncrementalGenerator
{
    private const string ZValidateAttributeFqn = "ZibStack.NET.Validation.ZValidateAttribute";

    private const string ZValidateAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Generates a compile-time Validate() method based on validation attributes.</summary>
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
    internal sealed class ZValidateAttribute : System.Attribute { }
}
";

    private const string ValidationResultSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Result of a validation operation.</summary>
    public sealed class ValidationResult
    {
        public static readonly ValidationResult Success = new(System.Array.Empty<string>());

        public System.Collections.Generic.IReadOnlyList<string> Errors { get; }
        public bool IsValid => Errors.Count == 0;

        public ValidationResult(System.Collections.Generic.IReadOnlyList<string> errors)
        {
            Errors = errors;
        }
    }

    /// <summary>Interface implemented by all [ZValidate]-decorated types.</summary>
    public interface IValidatable
    {
        ValidationResult Validate();
    }
}
";

    // Attribute sources for custom rules
    private const string ZRequiredAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Property must not be null (or empty for strings).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRequiredAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZMinLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at least this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMinLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMinLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZMaxLengthAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String/collection must have at most this many characters/items.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMaxLengthAttribute : System.Attribute
    {
        public int Length { get; }
        public string? Message { get; set; }
        public ZMaxLengthAttribute(int length) => Length = length;
    }
}
";

    private const string ZRangeAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Numeric value must be within the specified range (inclusive).</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZRangeAttribute : System.Attribute
    {
        public double Min { get; }
        public double Max { get; }
        public string? Message { get; set; }
        public ZRangeAttribute(double min, double max) { Min = min; Max = max; }
    }
}
";

    private const string ZEmailAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid email address.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZEmailAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string ZUrlAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must be a valid URL.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZUrlAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    private const string RegexAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>String must match the specified regex pattern.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZMatchAttribute : System.Attribute
    {
        public string Pattern { get; }
        public string? Message { get; set; }
        public ZMatchAttribute(string pattern) => Pattern = pattern;
    }
}
";

    private const string ZNotEmptyAttributeSource = @"// <auto-generated />
#nullable enable
namespace ZibStack.NET.Validation
{
    /// <summary>Collection must contain at least one element. String must not be empty or whitespace.</summary>
    [System.AttributeUsage(System.AttributeTargets.Property, Inherited = true)]
    internal sealed class ZNotEmptyAttribute : System.Attribute
    {
        public string? Message { get; set; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("ZValidateAttribute.g.cs", ZValidateAttributeSource);
            ctx.AddSource("ValidationResult.g.cs", ValidationResultSource);
            ctx.AddSource("ZRequiredAttribute.g.cs", ZRequiredAttributeSource);
            ctx.AddSource("ZMinLengthAttribute.g.cs", ZMinLengthAttributeSource);
            ctx.AddSource("ZMaxLengthAttribute.g.cs", ZMaxLengthAttributeSource);
            ctx.AddSource("ZRangeAttribute.g.cs", ZRangeAttributeSource);
            ctx.AddSource("ZEmailAttribute.g.cs", ZEmailAttributeSource);
            ctx.AddSource("ZUrlAttribute.g.cs", ZUrlAttributeSource);
            ctx.AddSource("ZMatchAttribute.g.cs", RegexAttributeSource);
            ctx.AddSource("ZNotEmptyAttribute.g.cs", ZNotEmptyAttributeSource);
        });

        var targets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ZValidateAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => ExtractValidationInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(targets, static (spc, info) =>
        {
            var source = GenerateValidation(info);
            spc.AddSource($"{info.HintName}.Validation.g.cs", source);

            if (info.IsPartial)
                spc.AddSource($"{info.HintName}.Validation.CodeMap.g.cs", GenerateCodeMap(info));
        });

        // [ImTiredOfCrud] (from ZibStack.NET.UI) → implies [ZValidate]
        var modelTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ZibStack.NET.UI.ImTiredOfCrudAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    // Skip if explicit [ZValidate] exists
                    var hasValidate = ((INamedTypeSymbol)ctx.TargetSymbol).GetAttributes()
                        .Any(a => a.AttributeClass?.ToDisplayString() == ZValidateAttributeFqn);
                    return hasValidate ? null : ExtractValidationInfo(ctx);
                })
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(modelTargets, static (spc, info) =>
        {
            var source = GenerateValidation(info);
            spc.AddSource($"{info.HintName}.Validation.Model.g.cs", source);

            if (info.IsPartial)
                spc.AddSource($"{info.HintName}.Validation.Model.CodeMap.g.cs", GenerateCodeMap(info));
        });
    }

    private static ValidationInfo? ExtractValidationInfo(GeneratorAttributeSyntaxContext context)
    {
        try
        {
            var symbol = (INamedTypeSymbol)context.TargetSymbol;
            var ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();

            var isRecord = context.TargetNode is RecordDeclarationSyntax;
            var isStruct = context.TargetNode is StructDeclarationSyntax;

            var properties = new List<PropertyValidationInfo>();

            foreach (var member in symbol.GetMembers())
            {
                if (member is not IPropertySymbol prop) continue;
                if (prop.DeclaredAccessibility != Accessibility.Public) continue;
                if (prop.GetMethod is null) continue;

                var rules = new List<ValidationRule>();
                var isNullableRef = prop.Type.NullableAnnotation == NullableAnnotation.Annotated;
                var isValueType = prop.Type.IsValueType;
                var typeName = prop.Type.ToDisplayString();

                foreach (var attr in prop.GetAttributes())
                {
                    var attrName = attr.AttributeClass?.ToDisplayString();
                    if (attrName is null) continue;

                    var customMessage = attr.NamedArguments
                        .FirstOrDefault(a => a.Key == "Message").Value.Value as string;

                    switch (attrName)
                    {
                        case "ZibStack.NET.Validation.ZRequiredAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Required, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZMinLengthAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int minLen)
                                rules.Add(new ValidationRule(ValidationRuleKind.MinLength, customMessage, minValue: minLen));
                            break;

                        case "ZibStack.NET.Validation.ZMaxLengthAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int maxLen)
                                rules.Add(new ValidationRule(ValidationRuleKind.MaxLength, customMessage, maxValue: maxLen));
                            break;

                        case "ZibStack.NET.Validation.ZRangeAttribute":
                            if (attr.ConstructorArguments.Length >= 2)
                            {
                                var min = attr.ConstructorArguments[0].Value is double dmin ? dmin : 0;
                                var max = attr.ConstructorArguments[1].Value is double dmax ? dmax : 0;
                                rules.Add(new ValidationRule(ValidationRuleKind.Range, customMessage, minValue: min, maxValue: max));
                            }
                            break;

                        case "ZibStack.NET.Validation.ZEmailAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Email, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZUrlAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.Url, customMessage));
                            break;

                        case "ZibStack.NET.Validation.ZMatchAttribute":
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string pattern)
                                rules.Add(new ValidationRule(ValidationRuleKind.Match, customMessage, pattern: pattern));
                            break;

                        case "ZibStack.NET.Validation.ZNotEmptyAttribute":
                            rules.Add(new ValidationRule(ValidationRuleKind.NotEmpty, customMessage));
                            break;
                    }
                }

                if (rules.Count > 0)
                {
                    properties.Add(new PropertyValidationInfo(
                        prop.Name, typeName, isNullableRef, isValueType, rules));
                }
            }

            if (properties.Count == 0) return null;

            var hintName = symbol.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_");

            bool isPartial = symbol.DeclaringSyntaxReferences
                .Any(r => r.GetSyntax() is TypeDeclarationSyntax tds
                    && tds.Modifiers.Any(SyntaxKind.PartialKeyword));

            return new ValidationInfo(
                symbol.Name, ns, hintName, isRecord, properties, isPartial);
        }
        catch
        {
            return null;
        }
    }

    private static string GenerateValidation(ValidationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated by ZibStack.NET.Validation for {info.ClassName}");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZibStack.NET.Validation;");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine($"partial {keyword} {info.ClassName} : IValidatable");
        sb.AppendLine("{");
        sb.AppendLine("    public ValidationResult Validate()");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new List<string>();");
        sb.AppendLine();

        foreach (var prop in info.Properties)
        {
            foreach (var rule in prop.Rules)
            {
                EmitRule(sb, prop, rule);
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return errors.Count == 0 ? ValidationResult.Success : new ValidationResult(errors);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateCodeMap(ValidationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (info.Namespace is not null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var keyword = info.IsRecord ? "record" : "class";
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated code map for <c>{info.ClassName}</c> (Validation):");
        sb.AppendLine("/// <list type=\"bullet\">");
        sb.AppendLine($"/// <item><description>Validate() method — compile-time validation from attributes</description></item>");
        sb.AppendLine($"/// <item><description>Implements <see cref=\"IValidatable\"/></description></item>");
        sb.AppendLine("/// </list>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"partial {keyword} {info.ClassName} {{ }}");

        return sb.ToString();
    }

    private static void EmitRule(StringBuilder sb, PropertyValidationInfo prop, ValidationRule rule)
    {
        var name = prop.PropertyName;
        var displayName = prop.PropertyName;

        switch (rule.Kind)
        {
            case ValidationRuleKind.Required:
            {
                var msg = rule.CustomMessage ?? $"{displayName} is required.";
                if (prop.IsValueType)
                {
                    // For nullable value types
                    if (prop.TypeName.EndsWith("?"))
                        sb.AppendLine($"        if ({name} is null) errors.Add(\"{EscapeString(msg)}\");");
                }
                else
                {
                    sb.AppendLine($"        if ({name} is null) errors.Add(\"{EscapeString(msg)}\");");
                    if (prop.TypeName == "string" || prop.TypeName == "string?")
                        sb.AppendLine($"        else if (string.IsNullOrWhiteSpace({name})) errors.Add(\"{EscapeString(msg)}\");");
                }
                break;
            }

            case ValidationRuleKind.MinLength:
            {
                var len = (int)rule.MinValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at least {len} characters.";
                sb.AppendLine($"        if ({name} is not null && {name}.Length < {len}) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.MaxLength:
            {
                var len = (int)rule.MaxValue;
                var msg = rule.CustomMessage ?? $"{displayName} must be at most {len} characters.";
                sb.AppendLine($"        if ({name} is not null && {name}.Length > {len}) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Range:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be between {rule.MinValue} and {rule.MaxValue}.";
                if (prop.IsNullableRef || prop.TypeName.EndsWith("?"))
                {
                    sb.AppendLine($"        if ({name} is not null && ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue})) errors.Add(\"{EscapeString(msg)}\");");
                }
                else
                {
                    sb.AppendLine($"        if ((double){name} < {rule.MinValue} || (double){name} > {rule.MaxValue}) errors.Add(\"{EscapeString(msg)}\");");
                }
                break;
            }

            case ValidationRuleKind.Email:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid email address.";
                sb.AppendLine($"        if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\")) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Url:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must be a valid URL.";
                sb.AppendLine($"        if ({name} is not null && !System.Uri.TryCreate({name}, System.UriKind.Absolute, out _)) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.Match:
            {
                var msg = rule.CustomMessage ?? $"{displayName} does not match the required pattern.";
                sb.AppendLine($"        if ({name} is not null && !System.Text.RegularExpressions.Regex.IsMatch({name}, @\"{rule.Pattern!.Replace("\"", "\"\"")}\")) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }

            case ValidationRuleKind.NotEmpty:
            {
                var msg = rule.CustomMessage ?? $"{displayName} must not be empty.";
                if (prop.TypeName == "string" || prop.TypeName == "string?")
                    sb.AppendLine($"        if ({name} is not null && string.IsNullOrWhiteSpace({name})) errors.Add(\"{EscapeString(msg)}\");");
                else
                    sb.AppendLine($"        if ({name} is not null && ((System.Collections.ICollection){name}).Count == 0) errors.Add(\"{EscapeString(msg)}\");");
                break;
            }
        }
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

// ─── Models ───────────────────────────────────────────────────────────

internal enum ValidationRuleKind
{
    Required,
    MinLength,
    MaxLength,
    Range,
    Email,
    Url,
    Match,
    NotEmpty,
}

internal sealed class ValidationRule
{
    public ValidationRuleKind Kind { get; }
    public string? CustomMessage { get; }
    public double MinValue { get; }
    public double MaxValue { get; }
    public string? Pattern { get; }

    public ValidationRule(ValidationRuleKind kind, string? customMessage = null, double minValue = 0, double maxValue = 0, string? pattern = null)
    {
        Kind = kind;
        CustomMessage = customMessage;
        MinValue = minValue;
        MaxValue = maxValue;
        Pattern = pattern;
    }
}

internal sealed class PropertyValidationInfo
{
    public string PropertyName { get; }
    public string TypeName { get; }
    public bool IsNullableRef { get; }
    public bool IsValueType { get; }
    public List<ValidationRule> Rules { get; }

    public PropertyValidationInfo(string propertyName, string typeName, bool isNullableRef, bool isValueType, List<ValidationRule> rules)
    {
        PropertyName = propertyName;
        TypeName = typeName;
        IsNullableRef = isNullableRef;
        IsValueType = isValueType;
        Rules = rules;
    }
}

internal sealed class ValidationInfo
{
    public string ClassName { get; }
    public string? Namespace { get; }
    public string HintName { get; }
    public bool IsRecord { get; }
    public bool IsPartial { get; }
    public List<PropertyValidationInfo> Properties { get; }

    public ValidationInfo(string className, string? ns, string hintName, bool isRecord, List<PropertyValidationInfo> properties, bool isPartial = false)
    {
        ClassName = className;
        Namespace = ns;
        HintName = hintName;
        IsRecord = isRecord;
        IsPartial = isPartial;
        Properties = properties;
    }
}
